package enlace_datos.entidades.gestiones.judiciales;

import enlace_datos.entidades.gestiones.SisSolicitudImpl;

import enlace_datos.util.myEntityImpl;
import enlace_datos.util.utils_DB;

import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.NameValuePairs;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
//import java.lang.String;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisOrdenJudicialImpl extends myEntityImpl{
    public static final int IDJUICIO = 0;
    public static final int IDSOLICITUD = 1;
    public static final int IDTIPO = 2;
    public static final int MONTO = 3;
    public static final int PORCENTAJE = 4;
    public static final int FECHADOC = 5;
    public static final int NOREFERENCIA = 6;
    public static final int NOJUICIO = 7;
    public static final int FECHACREACION = 8;
    public static final int CONVENIO = 9;
    public static final int IDMUNICIPIO = 10;
    public static final int JUZGADO = 11;
    public static final int BENEFICIARIO = 12;
    public static final int CEDULANIT = 13;
    public static final int FECHABAJA = 14;
    public static final int JUEZBAJA = 15;
    public static final int JUZGADOBAJA = 16;
    public static final int DESCONTADO = 17;
    public static final int NOTIFICADOR = 18;
    public static final int FECHAINGRESOUSAC = 19;
    public static final int SISCONDICIONORDENJUDICIAL = 20;
    public static final int SISSOLICITUD = 21;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisOrdenJudicialImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.gestiones.judiciales.SisOrdenJudicial");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdJuicio, using the alias name IdJuicio
     */
    public Number getIdJuicio() {
        return (Number)getAttributeInternal(IDJUICIO);
    }

    /**Sets <code>value</code> as the attribute value for IdJuicio
     */
    public void setIdJuicio(Number value) {
        setAttributeInternal(IDJUICIO, value);
    }

    /**Gets the attribute value for IdSolicitud, using the alias name IdSolicitud
     */
    public Number getIdSolicitud() {
        return (Number)getAttributeInternal(IDSOLICITUD);
    }

    /**Sets <code>value</code> as the attribute value for IdSolicitud
     */
    public void setIdSolicitud(Number value) {
        setAttributeInternal(IDSOLICITUD, value);
    }

    /**Gets the attribute value for IdTipo, using the alias name IdTipo
     */
    public Number getIdTipo() {
        return (Number)getAttributeInternal(IDTIPO);
    }

    /**Sets <code>value</code> as the attribute value for IdTipo
     */
    public void setIdTipo(Number value) {
        setAttributeInternal(IDTIPO, value);
    }

    /**Gets the attribute value for Monto, using the alias name Monto
     */
    public Number getMonto() {
        return (Number)getAttributeInternal(MONTO);
    }

    /**Sets <code>value</code> as the attribute value for Monto
     */
    public void setMonto(Number value) {
        setAttributeInternal(MONTO, value);
    }

    /**Gets the attribute value for Porcentaje, using the alias name Porcentaje
     */
    public Number getPorcentaje() {
        return (Number)getAttributeInternal(PORCENTAJE);
    }

    /**Sets <code>value</code> as the attribute value for Porcentaje
     */
    public void setPorcentaje(Number value) {
        setAttributeInternal(PORCENTAJE, value);
    }

    /**Gets the attribute value for FechaDoc, using the alias name FechaDoc
     */
    public Date getFechaDoc() {
        return (Date)getAttributeInternal(FECHADOC);
    }

    /**Sets <code>value</code> as the attribute value for FechaDoc
     */
    public void setFechaDoc(Date value) {
        setAttributeInternal(FECHADOC, value);
    }

    /**Gets the attribute value for NoReferencia, using the alias name NoReferencia
     */
    public Number getNoReferencia() {
        return (Number)getAttributeInternal(NOREFERENCIA);
    }

    /**Sets <code>value</code> as the attribute value for NoReferencia
     */
    public void setNoReferencia(Number value) {
        setAttributeInternal(NOREFERENCIA, value);
    }

    /**Gets the attribute value for NoJuicio, using the alias name NoJuicio
     */
    public String getNoJuicio() {
        return (String)getAttributeInternal(NOJUICIO);
    }

    /**Sets <code>value</code> as the attribute value for NoJuicio
     */
    public void setNoJuicio(String value) {
        setAttributeInternal(NOJUICIO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDJUICIO:
            return getIdJuicio();
        case IDSOLICITUD:
            return getIdSolicitud();
        case IDTIPO:
            return getIdTipo();
        case MONTO:
            return getMonto();
        case PORCENTAJE:
            return getPorcentaje();
        case FECHADOC:
            return getFechaDoc();
        case NOREFERENCIA:
            return getNoReferencia();
        case NOJUICIO:
            return getNoJuicio();
        case FECHACREACION:
            return getFechaCreacion();
        case CONVENIO:
            return getConvenio();
        case IDMUNICIPIO:
            return getIdMunicipio();
        case JUZGADO:
            return getJuzgado();
        case BENEFICIARIO:
            return getBeneficiario();
        case CEDULANIT:
            return getCedulaNit();
        case FECHABAJA:
            return getFechaBaja();
        case JUEZBAJA:
            return getJuezBaja();
        case JUZGADOBAJA:
            return getJuzgadoBaja();
        case DESCONTADO:
            return getDescontado();
        case NOTIFICADOR:
            return getNotificador();
        case FECHAINGRESOUSAC:
            return getFechaIngresoUsac();
        case SISCONDICIONORDENJUDICIAL:
            return getSisCondicionOrdenjudicial();
        case SISSOLICITUD:
            return getSisSolicitud();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDJUICIO:
            setIdJuicio((Number)value);
            return;
        case IDSOLICITUD:
            setIdSolicitud((Number)value);
            return;
        case IDTIPO:
            setIdTipo((Number)value);
            return;
        case MONTO:
            setMonto((Number)value);
            return;
        case PORCENTAJE:
            setPorcentaje((Number)value);
            return;
        case FECHADOC:
            setFechaDoc((Date)value);
            return;
        case NOREFERENCIA:
            setNoReferencia((Number)value);
            return;
        case NOJUICIO:
            setNoJuicio((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case CONVENIO:
            setConvenio((Number)value);
            return;
        case IDMUNICIPIO:
            setIdMunicipio((Number)value);
            return;
        case JUZGADO:
            setJuzgado((String)value);
            return;
        case BENEFICIARIO:
            setBeneficiario((String)value);
            return;
        case CEDULANIT:
            setCedulaNit((String)value);
            return;
        case FECHABAJA:
            setFechaBaja((Date)value);
            return;
        case JUEZBAJA:
            setJuezBaja((String)value);
            return;
        case JUZGADOBAJA:
            setJuzgadoBaja((String)value);
            return;
        case DESCONTADO:
            setDescontado((Number)value);
            return;
        case NOTIFICADOR:
            setNotificador((String)value);
            return;
        case FECHAINGRESOUSAC:
            setFechaIngresoUsac((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for FechaCreacion, using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the associated entity SisCondicionOrdenjudicialImpl
     */
    public SisCondicionOrdenjudicialImpl getSisCondicionOrdenjudicial() {
        return (SisCondicionOrdenjudicialImpl)getAttributeInternal(SISCONDICIONORDENJUDICIAL);
    }

    /**Sets <code>value</code> as the associated entity SisCondicionOrdenjudicialImpl
     */
    public void setSisCondicionOrdenjudicial(SisCondicionOrdenjudicialImpl value) {
        setAttributeInternal(SISCONDICIONORDENJUDICIAL, value);
    }

    /**Gets the attribute value for Convenio, using the alias name Convenio
     */
    public Number getConvenio() {
        return (Number)getAttributeInternal(CONVENIO);
    }

    /**Sets <code>value</code> as the attribute value for Convenio
     */
    public void setConvenio(Number value) {
        setAttributeInternal(CONVENIO, value);
    }

    /**Gets the attribute value for IdMunicipio, using the alias name IdMunicipio
     */
    public Number getIdMunicipio() {
        return (Number)getAttributeInternal(IDMUNICIPIO);
    }

    /**Sets <code>value</code> as the attribute value for IdMunicipio
     */
    public void setIdMunicipio(Number value) {
        setAttributeInternal(IDMUNICIPIO, value);
    }

    /**Gets the attribute value for Juzgado, using the alias name Juzgado
     */
    public String getJuzgado() {
        return (String)getAttributeInternal(JUZGADO);
    }

    /**Sets <code>value</code> as the attribute value for Juzgado
     */
    public void setJuzgado(String value) {
        setAttributeInternal(JUZGADO, value);
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
            //coloca # correspondiente al id_juicio a traves de una secuencia creada.
        if (operation==this.DML_INSERT){  
                SequenceImpl sequence = new SequenceImpl("SIS_ORDEN_JUDICIAL_SQ",e.getDBTransaction());
                this.setIdJuicio(sequence.getSequenceNumber());
                //this.getSisSolicitud().getRegistroEmpleado();
                //consultando si el empleado tiene un contrato activo                
                String consulta = "select nvl(count(contrato.ID_CONTRATO ),0) from sis_contrato contrato \n" + 
                "    where contrato.REGISTRO_EMPLEADO = "+this.getSisSolicitud().getRegistroEmpleado()+"  and\n" + 
                "    contrato.ESTATUS not in(\n" + 
                "    select id_estado from sis_estado_contrato_vw\n" + 
                "    where nombre like 'BAJA DEFINITIVA' or nombre like 'ANULADO')";
                Object existe = utils_DB.getEjecutarQuerry(this.getDBTransaction(),consulta);
                if (existe.toString().trim().equals("0") ){
                    throw new JboException("EL EMPLEADO NO TIENE NINGUN CONTRATO, PRESIONE CLIC EN EL BOTON CANCELAR");
                
                }
                
        }
        
            //condicion para obtener el porcentaje de la tabla sis_restriccion_oj   
                  
             if ((this.getMonto()== null) & (this.getPorcentaje()==null)){
                  throw new JboException("RECUERDE QUE DEBE INGRESAR UN VALOR FIJO O UN PORCENTAJE");
                       
             }
             else if ((this.getMonto()!=null) &(this.getPorcentaje()!=null)){
                 throw new JboException("RECUERDE QUE DEBE INGRESAR UN VALOR FIJO O UN PORCENTAJE,NO AMBOS");
             
             }
             else {
                     
             /* Se quita la validacion de el porcentaje maximo a descontar para
                 dejarlo en la autorizacion */
              /*          
                 NameValuePairs consulValida= new NameValuePairs();
                 consulValida.setAttribute("1",this.getIdTipo());
                 consulValida.setAttribute("2",this.getSisSolicitud().getRegistroEmpleado());
             
                  if ((this.getMonto()==null)) {
                       consulValida.setAttribute("3",this.getPorcentaje());
                       consulValida.setAttribute("4",2);
                   }
                   else {
                       consulValida.setAttribute("3",this.getMonto());
                       consulValida.setAttribute("4",1);
             }
             */
             
            //obteniendo el porcentaje   
             // Object consulta1 =utils_DB.getValorTabla(this.getDBTransaction(), "sis_restriccion_oj", "porcentaje", consulRestriccion);     
              //String restricPorcentaje = consulta1.toString();
              //obteniendo el nombre de la restriccion 
               //consulta1 =utils_DB.getValorTabla(this.getDBTransaction(), "sis_restriccion_oj", "nombre", consulRestriccion);
               //String nombre = consulta1.toString();
               /*
                   Object validacion = utils_DB.getValorFuncion(this.getDBTransaction(),"sis_pkg_util.VALIDAR_ORDEN_JUDICIAL(?,?,?,?)",consulValida ); 
            
                    if (!validacion.toString().equals("0")){
                    
                        throw new JboException("LA ORDEN JUDICIAL NO PUEDE SER INGRESADA, HA SOBREPASADO EL PORCENTAJE MAXIMO A DESCONTAR," +
                        "PORCENTAJE MAXIMO QUE PUEDE UTILIZAR PARA EL EMPLEADO "+ validacion);  
                        
                          
                     
                    }
                 
                    else {  
                    
                       
                    }
               */
               
                }   
                
            registrarLogOperaciones(operation, e);     
            super.doDML(operation, e);
       
        }


    /**Gets the associated entity enlace_datos.entidades.gestiones.SisSolicitudImpl
     */
    public SisSolicitudImpl getSisSolicitud() {
        return (SisSolicitudImpl)getAttributeInternal(SISSOLICITUD);
    }

    /**Sets <code>value</code> as the associated entity enlace_datos.entidades.gestiones.SisSolicitudImpl
     */
    public void setSisSolicitud(SisSolicitudImpl value) {
        setAttributeInternal(SISSOLICITUD, value);
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
        
    }

    /**Gets the attribute value for Beneficiario, using the alias name Beneficiario
     */
    public String getBeneficiario() {
        return (String)getAttributeInternal(BENEFICIARIO);
    }

    /**Sets <code>value</code> as the attribute value for Beneficiario
     */
    public void setBeneficiario(String value) {
        setAttributeInternal(BENEFICIARIO, value);
    }

    /**Gets the attribute value for CedulaNit, using the alias name CedulaNit
     */
    public String getCedulaNit() {
        return (String)getAttributeInternal(CEDULANIT);
    }

    /**Sets <code>value</code> as the attribute value for CedulaNit
     */
    public void setCedulaNit(String value) {
        setAttributeInternal(CEDULANIT, value);
    }

    /**Gets the attribute value for FechaBaja, using the alias name FechaBaja
     */
    public Date getFechaBaja() {
        return (Date)getAttributeInternal(FECHABAJA);
    }

    /**Sets <code>value</code> as the attribute value for FechaBaja
     */
    public void setFechaBaja(Date value) {
        setAttributeInternal(FECHABAJA, value);
    }

    /**Gets the attribute value for JuezBaja, using the alias name JuezBaja
     */
    public String getJuezBaja() {
        return (String)getAttributeInternal(JUEZBAJA);
    }

    /**Sets <code>value</code> as the attribute value for JuezBaja
     */
    public void setJuezBaja(String value) {
        setAttributeInternal(JUEZBAJA, value);
    }

    /**Gets the attribute value for JuzgadoBaja, using the alias name JuzgadoBaja
     */
    public String getJuzgadoBaja() {
        return (String)getAttributeInternal(JUZGADOBAJA);
    }

    /**Sets <code>value</code> as the attribute value for JuzgadoBaja
     */
    public void setJuzgadoBaja(String value) {
        setAttributeInternal(JUZGADOBAJA, value);
    }

    /**Gets the attribute value for Descontado, using the alias name Descontado
     */
    public Number getDescontado() {
        return (Number)getAttributeInternal(DESCONTADO);
    }

    /**Sets <code>value</code> as the attribute value for Descontado
     */
    public void setDescontado(Number value) {
        setAttributeInternal(DESCONTADO, value);
    }

    /**Gets the attribute value for Notificador, using the alias name Notificador
     */
    public String getNotificador() {
        return (String)getAttributeInternal(NOTIFICADOR);
    }

    /**Sets <code>value</code> as the attribute value for Notificador
     */
    public void setNotificador(String value) {
        setAttributeInternal(NOTIFICADOR, value);
    }

    /**Gets the attribute value for FechaIngresoUsac, using the alias name FechaIngresoUsac
     */
    public Date getFechaIngresoUsac() {
        return (Date)getAttributeInternal(FECHAINGRESOUSAC);
    }

    /**Sets <code>value</code> as the attribute value for FechaIngresoUsac
     */
    public void setFechaIngresoUsac(Date value) {
        setAttributeInternal(FECHAINGRESOUSAC, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idJuicio) {
        return new Key(new Object[]{idJuicio});
    }
}

