package enlace_datos.consultas.nomina.client;

import enlace_datos.consultas.nomina.common.SisNominaVw;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisNominaVwClient extends ViewUsageImpl implements SisNominaVw {
    /**This is the default constructor (do not remove)
     */
    public SisNominaVwClient() {
    }

    public void filtrarxProceso(Number pIdProceso) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"filtrarxProceso",new String [] {"oracle.jbo.domain.Number"},new Object[] {pIdProceso});
        return;
    }
}
