package enlace_datos.consultas.procesos;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisPeridoxTipoNomImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public SisPeridoxTipoNomImpl() {
    }

    /**Gets the bind variable value for pTipoNomina
     */
    public Number getpTipoNomina() {
        return (Number)getNamedWhereClauseParam("pTipoNomina");
    }

    /**Sets <code>value</code> for bind variable pTipoNomina
     */
    public void setpTipoNomina(Number value) {
        setNamedWhereClauseParam("pTipoNomina", value);
    }
}
