package enlace_datos.consultas.gestiones.indemnizaciones;

import enlace_datos.entidades.util.SisAutorizacionDetImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisHistorialTrasladosIndem_vwRowImpl extends ViewRowImpl {
    public static final int IDAUTORIZACIONDET = 0;
    public static final int IDAUTORIZACION = 1;
    public static final int IDESTADO = 2;
    public static final int USUARIO = 3;
    public static final int FECHA = 4;
    public static final int COMENTARIO = 5;
    public static final int NOMBREESTADO = 6;

    /**This is the default constructor (do not remove)
     */
    public SisHistorialTrasladosIndem_vwRowImpl() {
    }

    /**Gets SisAutorizacionDet entity object.
     */
    public SisAutorizacionDetImpl getSisAutorizacionDet() {
        return (SisAutorizacionDetImpl)getEntity(0);
    }

    /**Gets the attribute value for ID_AUTORIZACION_DET using the alias name IdAutorizacionDet
     */
    public Number getIdAutorizacionDet() {
        return (Number) getAttributeInternal(IDAUTORIZACIONDET);
    }

    /**Sets <code>value</code> as attribute value for ID_AUTORIZACION_DET using the alias name IdAutorizacionDet
     */
    public void setIdAutorizacionDet(Number value) {
        setAttributeInternal(IDAUTORIZACIONDET, value);
    }

    /**Gets the attribute value for ID_AUTORIZACION using the alias name IdAutorizacion
     */
    public Number getIdAutorizacion() {
        return (Number) getAttributeInternal(IDAUTORIZACION);
    }

    /**Sets <code>value</code> as attribute value for ID_AUTORIZACION using the alias name IdAutorizacion
     */
    public void setIdAutorizacion(Number value) {
        setAttributeInternal(IDAUTORIZACION, value);
    }

    /**Gets the attribute value for ID_ESTADO using the alias name IdEstado
     */
    public Number getIdEstado() {
        return (Number) getAttributeInternal(IDESTADO);
    }

    /**Sets <code>value</code> as attribute value for ID_ESTADO using the alias name IdEstado
     */
    public void setIdEstado(Number value) {
        setAttributeInternal(IDESTADO, value);
    }

    /**Gets the attribute value for USUARIO using the alias name Usuario
     */
    public String getUsuario() {
        return (String) getAttributeInternal(USUARIO);
    }

    /**Sets <code>value</code> as attribute value for USUARIO using the alias name Usuario
     */
    public void setUsuario(String value) {
        setAttributeInternal(USUARIO, value);
    }

    /**Gets the attribute value for FECHA using the alias name Fecha
     */
    public Date getFecha() {
        return (Date) getAttributeInternal(FECHA);
    }

    /**Sets <code>value</code> as attribute value for FECHA using the alias name Fecha
     */
    public void setFecha(Date value) {
        setAttributeInternal(FECHA, value);
    }

    /**Gets the attribute value for COMENTARIO using the alias name Comentario
     */
    public String getComentario() {
        return (String) getAttributeInternal(COMENTARIO);
    }

    /**Sets <code>value</code> as attribute value for COMENTARIO using the alias name Comentario
     */
    public void setComentario(String value) {
        setAttributeInternal(COMENTARIO, value);
    }

    /**Gets the attribute value for the calculated attribute NombreEstado
     */
    public String getNombreEstado() {
        return (String) getAttributeInternal(NOMBREESTADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NombreEstado
     */
    public void setNombreEstado(String value) {
        setAttributeInternal(NOMBREESTADO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDAUTORIZACIONDET:
            return getIdAutorizacionDet();
        case IDAUTORIZACION:
            return getIdAutorizacion();
        case IDESTADO:
            return getIdEstado();
        case USUARIO:
            return getUsuario();
        case FECHA:
            return getFecha();
        case COMENTARIO:
            return getComentario();
        case NOMBREESTADO:
            return getNombreEstado();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDAUTORIZACIONDET:
            setIdAutorizacionDet((Number)value);
            return;
        case IDAUTORIZACION:
            setIdAutorizacion((Number)value);
            return;
        case IDESTADO:
            setIdEstado((Number)value);
            return;
        case USUARIO:
            setUsuario((String)value);
            return;
        case FECHA:
            setFecha((Date)value);
            return;
        case COMENTARIO:
            setComentario((String)value);
            return;
        case NOMBREESTADO:
            setNombreEstado((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
