package enlace_datos.consultas.gestiones.indemnizaciones;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisProgramasTrabajador_vwRowImpl extends ViewRowImpl {


    public static final int IDPROGRAMA = 0;
    public static final int NOMBRE = 1;

    /**This is the default constructor (do not remove)
     */
    public SisProgramasTrabajador_vwRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute IdPrograma
     */
    public Number getIdPrograma() {
        return (Number) getAttributeInternal(IDPROGRAMA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdPrograma
     */
    public void setIdPrograma(Number value) {
        setAttributeInternal(IDPROGRAMA, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDPROGRAMA:
            return getIdPrograma();
        case NOMBRE:
            return getNombre();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDPROGRAMA:
            setIdPrograma((Number)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }
}
