package enlace_datos.consultas.gestiones.client;

import enlace_datos.consultas.gestiones.common.SicoinPartidaEgresosView;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SicoinPartidaEgresosViewClient extends ViewUsageImpl implements SicoinPartidaEgresosView {
    /**This is the default constructor (do not remove)
     */
    public SicoinPartidaEgresosViewClient() {
    }


    public String getExistePartida(Number pUnidadEjecutora, 
                                   Number pUnidadDesconcentrada, 
                                   Number pPrograma, Number pSubPrograma, 
                                   Number pProyecto, Number pActividad, 
                                   Number pObra, Number pRenglon, 
                                   Number pGeografico, Number pFuente, 
                                   Number pOrganismo, Number pCorrelativo, 
                                   String usuario) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getExistePartida",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","java.lang.String"},new Object[] {pUnidadEjecutora, pUnidadDesconcentrada, pPrograma, pSubPrograma, pProyecto, pActividad, pObra, pRenglon, pGeografico, pFuente, pOrganismo, pCorrelativo, usuario});
        return (String)_ret;
    }

    public String getNombrePartida(Number pRenglon) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getNombrePartida",new String [] {"oracle.jbo.domain.Number"},new Object[] {pRenglon});
        return (String)_ret;
    }

    public String getPartidaFormato(Number pUnidadEjecutora, 
                                    Number pUnidadDesconcentrada, 
                                    Number pPrograma, Number pSubPrograma, 
                                    Number pProyecto, Number pActividad, 
                                    Number pObra, Number pRenglon, 
                                    Number pGeografico, Number pFuente, 
                                    Number pOrganismo, Number pCorrelativo) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getPartidaFormato",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number"},new Object[] {pUnidadEjecutora, pUnidadDesconcentrada, pPrograma, pSubPrograma, pProyecto, pActividad, pObra, pRenglon, pGeografico, pFuente, pOrganismo, pCorrelativo});
        return (String)_ret;
    }
}
