package enlace_datos.entidades.mensajes;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisMensajeEntranteImpl extends EntityImpl {
    public static final int IDMENSAJEENTRANTE = 0;
    public static final int IDMENSAJESAL = 1;
    public static final int USUARIO = 2;
    public static final int ESTADO = 3;
    public static final int FECHALECTURA = 4;
    public static final int SISMENSAJESALIENTE = 5;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisMensajeEntranteImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.mensajes.SisMensajeEntrante");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdMensajeEntrante, using the alias name IdMensajeEntrante
     */
    public Number getIdMensajeEntrante() {
        return (Number)getAttributeInternal(IDMENSAJEENTRANTE);
    }

    /**Sets <code>value</code> as the attribute value for IdMensajeEntrante
     */
    public void setIdMensajeEntrante(Number value) {
        setAttributeInternal(IDMENSAJEENTRANTE, value);
    }

    /**Gets the attribute value for IdMensajeSal, using the alias name IdMensajeSal
     */
    public Number getIdMensajeSal() {
        return (Number)getAttributeInternal(IDMENSAJESAL);
    }

    /**Sets <code>value</code> as the attribute value for IdMensajeSal
     */
    public void setIdMensajeSal(Number value) {
        setAttributeInternal(IDMENSAJESAL, value);
    }

    /**Gets the attribute value for Usuario, using the alias name Usuario
     */
    public String getUsuario() {
        return (String)getAttributeInternal(USUARIO);
    }

    /**Sets <code>value</code> as the attribute value for Usuario
     */
    public void setUsuario(String value) {
        setAttributeInternal(USUARIO, value);
    }

    /**Gets the attribute value for Estado, using the alias name Estado
     */
    public String getEstado() {
        return (String)getAttributeInternal(ESTADO);
    }

    /**Sets <code>value</code> as the attribute value for Estado
     */
    public void setEstado(String value) {
        setAttributeInternal(ESTADO, value);
    }

    /**Gets the attribute value for FechaLectura, using the alias name FechaLectura
     */
    public Date getFechaLectura() {
        return (Date)getAttributeInternal(FECHALECTURA);
    }

    /**Sets <code>value</code> as the attribute value for FechaLectura
     */
    public void setFechaLectura(Date value) {
        setAttributeInternal(FECHALECTURA, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDMENSAJEENTRANTE:
            return getIdMensajeEntrante();
        case IDMENSAJESAL:
            return getIdMensajeSal();
        case USUARIO:
            return getUsuario();
        case ESTADO:
            return getEstado();
        case FECHALECTURA:
            return getFechaLectura();
        case SISMENSAJESALIENTE:
            return getSisMensajeSaliente();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDMENSAJEENTRANTE:
            setIdMensajeEntrante((Number)value);
            return;
        case IDMENSAJESAL:
            setIdMensajeSal((Number)value);
            return;
        case USUARIO:
            setUsuario((String)value);
            return;
        case ESTADO:
            setEstado((String)value);
            return;
        case FECHALECTURA:
            setFechaLectura((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity SisMensajeSalienteImpl
     */
    public SisMensajeSalienteImpl getSisMensajeSaliente() {
        return (SisMensajeSalienteImpl)getAttributeInternal(SISMENSAJESALIENTE);
    }

    /**Sets <code>value</code> as the associated entity SisMensajeSalienteImpl
     */
    public void setSisMensajeSaliente(SisMensajeSalienteImpl value) {
        setAttributeInternal(SISMENSAJESALIENTE, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idMensajeEntrante) {
        return new Key(new Object[]{idMensajeEntrante});
    }
}
