package interfaz_usuario.pageDefs;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class gestiones_ingresar_deduccionPageDefMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "getTotalLiquido_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalDescSA_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalJudiDiff_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalISR_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalPlan_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalNominalDiff_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalNominalSA_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalBono_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalDesc_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalIgssSA_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalDescDiff_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalPlanDiff_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalLiquidoDiff_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalPlan_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalJudi_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalBonoSA_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalPlanSA_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalISRSA_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalIgssSA_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalNominalSA_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalLiquidoDiff_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalIgssDiff_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalLiquido_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalJudiDiff_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalDesc_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalISR_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalJudi_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalISRDiff_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalBono_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalISRDiff_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalIgss_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalISRSA_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalNominalDiff_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalLiquidoSA_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalIgssDiff_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalBonoDiff_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalBonoDiff_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalBonoSA_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalPlanSA_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalJudiSA_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalDescDiff_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalLiquidoSA_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalNominal_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalJudiSA_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalPlanDiff_return_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "getTotalIgss_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalDescSA_return_FMT_FORMAT", "#,##0.00" },
{ "getTotalNominal_return_FMT_FORMAT", "#,##0.00" }};

    /**This is the default constructor (do not remove)
     */
    public gestiones_ingresar_deduccionPageDefMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
