package interfaz_usuario.pageDefs;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class reportes_pagos_repetidos_auditorPageDefMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "dependenciasnombre_codigo_null", "TODAS" },
{ "dependenciasIdDependencia_null", "TODAS" },
{ "periodo1Nombre_null", "<No Selection>" },
{ "SisPeridoxTipoNomVwNomperiodo_null", "NINGUNO" }};

    /**This is the default constructor (do not remove)
     */
    public reportes_pagos_repetidos_auditorPageDefMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
