package enlace_datos.consultas.gestiones.plazas021;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class consul_sispartida021Impl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public consul_sispartida021Impl() {
    }

    /**Gets the bind variable value for varUnidad
     */
    public Number getvarUnidad() {
        return (Number)getNamedWhereClauseParam("varUnidad");
    }

    /**Sets <code>value</code> for bind variable varUnidad
     */
    public void setvarUnidad(Number value) {
        setNamedWhereClauseParam("varUnidad", value);
    }

    /**Gets the bind variable value for varDependencia
     */
    public Number getvarDependencia() {
        return (Number)getNamedWhereClauseParam("varDependencia");
    }

    /**Sets <code>value</code> for bind variable varDependencia
     */
    public void setvarDependencia(Number value) {
        setNamedWhereClauseParam("varDependencia", value);
    }

    /**Gets the bind variable value for varPrograma
     */
    public Number getvarPrograma() {
        return (Number)getNamedWhereClauseParam("varPrograma");
    }

    /**Sets <code>value</code> for bind variable varPrograma
     */
    public void setvarPrograma(Number value) {
        setNamedWhereClauseParam("varPrograma", value);
    }
}
