package enlace_datos.consultas.gestiones;

import enlace_datos.entidades.gestiones.SisIsrForm1101Impl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisIsrForm1101VwRowImpl extends ViewRowImpl {
    public static final int REGISTROEMPLEADO = 0;
    public static final int ANIO = 1;
    public static final int DEDUCCIONUNICA = 2;
    public static final int RENTANETAUSAC = 3;
    public static final int RENTANETAOTROS = 4;
    public static final int TOTALRENTANETA = 5;
    public static final int RENTAIMPONIBLE = 6;
    public static final int IGSSPLAN = 7;
    public static final int PRIMASSEGUROS = 8;
    public static final int GTOSMEDICOS = 9;
    public static final int PENSIONESALIMEN = 10;
    public static final int RENTAEXCENTA = 11;
    public static final int COLEGIOSYOTROS = 12;
    public static final int ISRAPLICAR = 13;
    public static final int FECHAPRESENTACION = 14;
    public static final int FECHACREACION = 15;
    public static final int FECHAMODIFICACION = 16;
    public static final int SHWOPT = 17;
    public static final int SISISRFORM1101OTROSPTRNOSVW = 18;

    /**This is the default constructor (do not remove)
     */
    public SisIsrForm1101VwRowImpl() {
    }

    /**Gets SisIsrForm1101 entity object.
     */
    public SisIsrForm1101Impl getSisIsrForm1101() {
        return (SisIsrForm1101Impl)getEntity(0);
    }

    /**Gets the attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for ANIO using the alias name Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as attribute value for ANIO using the alias name Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for DEDUCCION_UNICA using the alias name DeduccionUnica
     */
    public Number getDeduccionUnica() {
        return (Number) getAttributeInternal(DEDUCCIONUNICA);
    }

    /**Sets <code>value</code> as attribute value for DEDUCCION_UNICA using the alias name DeduccionUnica
     */
    public void setDeduccionUnica(Number value) {
        setAttributeInternal(DEDUCCIONUNICA, value);
    }

    /**Gets the attribute value for RENTA_NETA_USAC using the alias name RentaNetaUsac
     */
    public Number getRentaNetaUsac() {
        return (Number) getAttributeInternal(RENTANETAUSAC);
    }

    /**Sets <code>value</code> as attribute value for RENTA_NETA_USAC using the alias name RentaNetaUsac
     */
    public void setRentaNetaUsac(Number value) {
        setAttributeInternal(RENTANETAUSAC, value);
    }

    /**Gets the attribute value for RENTA_NETA_OTROS using the alias name RentaNetaOtros
     */
    public Number getRentaNetaOtros() {
        return (Number) getAttributeInternal(RENTANETAOTROS);
    }

    /**Sets <code>value</code> as attribute value for RENTA_NETA_OTROS using the alias name RentaNetaOtros
     */
    public void setRentaNetaOtros(Number value) {
        setAttributeInternal(RENTANETAOTROS, value);
    }

    /**Gets the attribute value for TOTAL_RENTA_NETA using the alias name TotalRentaNeta
     */
    public Number getTotalRentaNeta() {
        return (Number) getAttributeInternal(TOTALRENTANETA);
    }

    /**Sets <code>value</code> as attribute value for TOTAL_RENTA_NETA using the alias name TotalRentaNeta
     */
    public void setTotalRentaNeta(Number value) {
        setAttributeInternal(TOTALRENTANETA, value);
    }

    /**Gets the attribute value for RENTA_IMPONIBLE using the alias name RentaImponible
     */
    public Number getRentaImponible() {
        return (Number) getAttributeInternal(RENTAIMPONIBLE);
    }

    /**Sets <code>value</code> as attribute value for RENTA_IMPONIBLE using the alias name RentaImponible
     */
    public void setRentaImponible(Number value) {
        setAttributeInternal(RENTAIMPONIBLE, value);
    }

    /**Gets the attribute value for IGSSPLAN using the alias name Igssplan
     */
    public Number getIgssplan() {
        return (Number) getAttributeInternal(IGSSPLAN);
    }

    /**Sets <code>value</code> as attribute value for IGSSPLAN using the alias name Igssplan
     */
    public void setIgssplan(Number value) {
        setAttributeInternal(IGSSPLAN, value);
    }

    /**Gets the attribute value for PRIMAS_SEGUROS using the alias name PrimasSeguros
     */
    public Number getPrimasSeguros() {
        return (Number) getAttributeInternal(PRIMASSEGUROS);
    }

    /**Sets <code>value</code> as attribute value for PRIMAS_SEGUROS using the alias name PrimasSeguros
     */
    public void setPrimasSeguros(Number value) {
        setAttributeInternal(PRIMASSEGUROS, value);
    }

    /**Gets the attribute value for GTOSMEDICOS using the alias name Gtosmedicos
     */
    public Number getGtosmedicos() {
        return (Number) getAttributeInternal(GTOSMEDICOS);
    }

    /**Sets <code>value</code> as attribute value for GTOSMEDICOS using the alias name Gtosmedicos
     */
    public void setGtosmedicos(Number value) {
        setAttributeInternal(GTOSMEDICOS, value);
    }

    /**Gets the attribute value for PENSIONES_ALIMEN using the alias name PensionesAlimen
     */
    public Number getPensionesAlimen() {
        return (Number) getAttributeInternal(PENSIONESALIMEN);
    }

    /**Sets <code>value</code> as attribute value for PENSIONES_ALIMEN using the alias name PensionesAlimen
     */
    public void setPensionesAlimen(Number value) {
        setAttributeInternal(PENSIONESALIMEN, value);
    }

    /**Gets the attribute value for RENTA_EXCENTA using the alias name RentaExcenta
     */
    public Number getRentaExcenta() {
        return (Number) getAttributeInternal(RENTAEXCENTA);
    }

    /**Sets <code>value</code> as attribute value for RENTA_EXCENTA using the alias name RentaExcenta
     */
    public void setRentaExcenta(Number value) {
        setAttributeInternal(RENTAEXCENTA, value);
    }

    /**Gets the attribute value for COLEGIOSYOTROS using the alias name Colegiosyotros
     */
    public Number getColegiosyotros() {
        return (Number) getAttributeInternal(COLEGIOSYOTROS);
    }

    /**Sets <code>value</code> as attribute value for COLEGIOSYOTROS using the alias name Colegiosyotros
     */
    public void setColegiosyotros(Number value) {
        setAttributeInternal(COLEGIOSYOTROS, value);
    }

    /**Gets the attribute value for ISR_APLICAR using the alias name IsrAplicar
     */
    public Number getIsrAplicar() {
        return (Number) getAttributeInternal(ISRAPLICAR);
    }

    /**Sets <code>value</code> as attribute value for ISR_APLICAR using the alias name IsrAplicar
     */
    public void setIsrAplicar(Number value) {
        setAttributeInternal(ISRAPLICAR, value);
    }

    /**Gets the attribute value for FECHA_PRESENTACION using the alias name FechaPresentacion
     */
    public Date getFechaPresentacion() {
        return (Date) getAttributeInternal(FECHAPRESENTACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_PRESENTACION using the alias name FechaPresentacion
     */
    public void setFechaPresentacion(Date value) {
        setAttributeInternal(FECHAPRESENTACION, value);
    }

    /**Gets the attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for FECHA_MODIFICACION using the alias name FechaModificacion
     */
    public Date getFechaModificacion() {
        return (Date) getAttributeInternal(FECHAMODIFICACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_MODIFICACION using the alias name FechaModificacion
     */
    public void setFechaModificacion(Date value) {
        setAttributeInternal(FECHAMODIFICACION, value);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisIsrForm1101OtrosptrnosVw
     */
    public RowIterator getSisIsrForm1101OtrosptrnosVw() {
        return (RowIterator)getAttributeInternal(SISISRFORM1101OTROSPTRNOSVW);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case ANIO:
            return getAnio();
        case DEDUCCIONUNICA:
            return getDeduccionUnica();
        case RENTANETAUSAC:
            return getRentaNetaUsac();
        case RENTANETAOTROS:
            return getRentaNetaOtros();
        case TOTALRENTANETA:
            return getTotalRentaNeta();
        case RENTAIMPONIBLE:
            return getRentaImponible();
        case IGSSPLAN:
            return getIgssplan();
        case PRIMASSEGUROS:
            return getPrimasSeguros();
        case GTOSMEDICOS:
            return getGtosmedicos();
        case PENSIONESALIMEN:
            return getPensionesAlimen();
        case RENTAEXCENTA:
            return getRentaExcenta();
        case COLEGIOSYOTROS:
            return getColegiosyotros();
        case ISRAPLICAR:
            return getIsrAplicar();
        case FECHAPRESENTACION:
            return getFechaPresentacion();
        case FECHACREACION:
            return getFechaCreacion();
        case FECHAMODIFICACION:
            return getFechaModificacion();
        case SHWOPT:
            return getshwOpt();
        case SISISRFORM1101OTROSPTRNOSVW:
            return getSisIsrForm1101OtrosptrnosVw();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            setRegistroEmpleado((Number)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case DEDUCCIONUNICA:
            setDeduccionUnica((Number)value);
            return;
        case RENTANETAUSAC:
            setRentaNetaUsac((Number)value);
            return;
        case RENTANETAOTROS:
            setRentaNetaOtros((Number)value);
            return;
        case TOTALRENTANETA:
            setTotalRentaNeta((Number)value);
            return;
        case RENTAIMPONIBLE:
            setRentaImponible((Number)value);
            return;
        case IGSSPLAN:
            setIgssplan((Number)value);
            return;
        case PRIMASSEGUROS:
            setPrimasSeguros((Number)value);
            return;
        case GTOSMEDICOS:
            setGtosmedicos((Number)value);
            return;
        case PENSIONESALIMEN:
            setPensionesAlimen((Number)value);
            return;
        case RENTAEXCENTA:
            setRentaExcenta((Number)value);
            return;
        case COLEGIOSYOTROS:
            setColegiosyotros((Number)value);
            return;
        case ISRAPLICAR:
            setIsrAplicar((Number)value);
            return;
        case FECHAPRESENTACION:
            setFechaPresentacion((Date)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case FECHAMODIFICACION:
            setFechaModificacion((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute shwOpt
     */
    public String getshwOpt() {
    
      String vOpcion="";
       
       if (this.getAnio().compareTo(2012)<=0){
       
           vOpcion="1";
           
       }else if (this.getAnio().compareTo(2013)>=0){
        
           vOpcion="2";
       }

        return vOpcion;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute shwOpt
     */
    public void setshwOpt(String value) {
        setAttributeInternal(SHWOPT, value);
    }
}
