package enlace_datos.consultas.gestiones;

import enlace_datos.consultas.gestiones.common.SisLicenciasSinGoceVw;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisLicenciasSinGoceVwImpl extends ViewObjectImpl implements SisLicenciasSinGoceVw {
    /**This is the default constructor (do not remove)
     */
    public SisLicenciasSinGoceVwImpl() {
    }
    
    public void filtrarContrato(Number pIdContrato){
        String pFiltro;
        
        pFiltro="exists(\n" + 
        "select 1 from\n" + 
        "sis_contrato contr2\n" + 
        "where QRSLT.id_partida=contr2.id_partida\n" + 
        "and QRSLT.id_puesto=contr2.id_puesto\n" + 
        "and QRSLT.numero_plaza=contr2.numero_plaza\n" + 
        "and QRSLT.correlativo=contr2.correlativo\n" + 
        "and contr2.id_contrato=" + pIdContrato+ 
        "and QRSLT.registro_empleado=contr2.registro_empleado"+
        ")";
        this.setWhereClause(pFiltro);
        this.executeQuery();
        
    }
    
    
    public void resetFiltros(){
        this.setWhereClause("");
        this.executeQuery();
    }

    /**executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object params[], int noUserParams) {
    super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc, 
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**getEstimatedRowCount - overridden for custom java data source support.
     */
    public long getEstimatedRowCount() {
        long value = super.getEstimatedRowCount();
        return value;
    }
}
