package enlace_datos.consultas.reportes.client;

import enlace_datos.consultas.reportes.common.SisListSis_22Vw;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisListSis_22VwClient extends ViewUsageImpl implements SisListSis_22Vw {
    /**This is the default constructor (do not remove)
     */
    public SisListSis_22VwClient() {
    }


    public void filtarXFechas(String pUsuario, Date vFechaI, Date vFechaF) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"filtarXFechas",new String [] {"java.lang.String","oracle.jbo.domain.Date","oracle.jbo.domain.Date"},new Object[] {pUsuario, vFechaI, vFechaF});
        return;
    }

    public void generarSis_22(String pUsuario, Number pOpcion, Number pIdActa, 
                              Number pAnioActa, Date pFechaSIS) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"generarSis_22",new String [] {"java.lang.String","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Date"},new Object[] {pUsuario, pOpcion, pIdActa, pAnioActa, pFechaSIS});
        return;
    }
}
