package enlace_datos.consultas.reportes.client;

import enlace_datos.consultas.reportes.common.SisPagosProcesados;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisPagosProcesadosClient extends ViewUsageImpl implements SisPagosProcesados {
    /**This is the default constructor (do not remove)
     */
    public SisPagosProcesadosClient() {
    }

    public void acreditamiento_final(Number pIdProceso, String pUsuario) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"acreditamiento_final",new String [] {"oracle.jbo.domain.Number","java.lang.String"},new Object[] {pIdProceso, pUsuario});
        return;
    }
}
