package enlace_datos.consultas.complementos;

import enlace_datos.entidades.complementos.SisComplementoImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisComplementoVwRowImpl extends ViewRowImpl {
    public static final int IDCOMPLEMENTO = 0;
    public static final int IDESTADO = 1;
    public static final int IDTIPO = 2;
    public static final int IDSUBPROGRAMA = 3;
    public static final int PERIODO = 4;
    public static final int ANIO = 5;
    public static final int FECHAPRESENTACION = 6;
    public static final int CREADOPOR = 7;
    public static final int FECHACREACION = 8;
    public static final int MODPOR = 9;
    public static final int FECHAMOD = 10;
    public static final int FIRMATESO = 11;
    public static final int FIRMAJEFE = 12;
    public static final int NOMPERIODO = 13;
    public static final int FORMATO2 = 14;
    public static final int NOMSUBPROG = 15;
    public static final int CODUNIDAD = 16;
    public static final int NOMUNIDAD = 17;
    public static final int NOMESTADO = 18;
    public static final int NOMUSUARIO = 19;
    public static final int IDSOLICITUD = 20;
    public static final int ISFORMAACTIVA = 21;
    public static final int ISAUTOFINANCIABLE = 22;
    public static final int SISCOMPLEMENTODETVW = 23;
    public static final int SISCOMPLEMENTOIGSSVW = 24;

    /**This is the default constructor (do not remove)
     */
    public SisComplementoVwRowImpl() {
    }

    /**Gets SisComplemento entity object.
     */
    public SisComplementoImpl getSisComplemento() {
        return (SisComplementoImpl)getEntity(0);
    }

    /**Gets the attribute value for ID_COMPLEMENTO using the alias name IdComplemento
     */
    public Number getIdComplemento() {
        return (Number) getAttributeInternal(IDCOMPLEMENTO);
    }

    /**Sets <code>value</code> as attribute value for ID_COMPLEMENTO using the alias name IdComplemento
     */
    public void setIdComplemento(Number value) {
        setAttributeInternal(IDCOMPLEMENTO, value);
    }

    /**Gets the attribute value for ID_ESTADO using the alias name IdEstado
     */
    public Number getIdEstado() {
        return (Number) getAttributeInternal(IDESTADO);
    }

    /**Sets <code>value</code> as attribute value for ID_ESTADO using the alias name IdEstado
     */
    public void setIdEstado(Number value) {
        setAttributeInternal(IDESTADO, value);
    }

    /**Gets the attribute value for ID_TIPO using the alias name IdTipo
     */
    public Number getIdTipo() {
        return (Number) getAttributeInternal(IDTIPO);
    }

    /**Sets <code>value</code> as attribute value for ID_TIPO using the alias name IdTipo
     */
    public void setIdTipo(Number value) {
        setAttributeInternal(IDTIPO, value);
    }

    /**Gets the attribute value for ID_SUBPROGRAMA using the alias name IdSubprograma
     */
    public Number getIdSubprograma() {
        return (Number) getAttributeInternal(IDSUBPROGRAMA);
    }

    /**Sets <code>value</code> as attribute value for ID_SUBPROGRAMA using the alias name IdSubprograma
     */
    public void setIdSubprograma(Number value) {
        setAttributeInternal(IDSUBPROGRAMA, value);
    }

    /**Gets the attribute value for PERIODO using the alias name Periodo
     */
    public Number getPeriodo() {
        return (Number) getAttributeInternal(PERIODO);
    }

    /**Sets <code>value</code> as attribute value for PERIODO using the alias name Periodo
     */
    public void setPeriodo(Number value) {
        setAttributeInternal(PERIODO, value);
    }

    /**Gets the attribute value for ANIO using the alias name Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as attribute value for ANIO using the alias name Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for FECHA_PRESENTACION using the alias name FechaPresentacion
     */
    public Date getFechaPresentacion() {
        return (Date) getAttributeInternal(FECHAPRESENTACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_PRESENTACION using the alias name FechaPresentacion
     */
    public void setFechaPresentacion(Date value) {
        setAttributeInternal(FECHAPRESENTACION, value);
    }

    /**Gets the attribute value for CREADO_POR using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String) getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as attribute value for CREADO_POR using the alias name CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for MOD_POR using the alias name ModPor
     */
    public String getModPor() {
        return (String) getAttributeInternal(MODPOR);
    }

    /**Sets <code>value</code> as attribute value for MOD_POR using the alias name ModPor
     */
    public void setModPor(String value) {
        setAttributeInternal(MODPOR, value);
    }

    /**Gets the attribute value for FECHA_MOD using the alias name FechaMod
     */
    public Date getFechaMod() {
        return (Date) getAttributeInternal(FECHAMOD);
    }

    /**Sets <code>value</code> as attribute value for FECHA_MOD using the alias name FechaMod
     */
    public void setFechaMod(Date value) {
        setAttributeInternal(FECHAMOD, value);
    }

    /**Gets the attribute value for FIRMA_TESO using the alias name FirmaTeso
     */
    public String getFirmaTeso() {
        return (String) getAttributeInternal(FIRMATESO);
    }

    /**Sets <code>value</code> as attribute value for FIRMA_TESO using the alias name FirmaTeso
     */
    public void setFirmaTeso(String value) {
        setAttributeInternal(FIRMATESO, value);
    }

    /**Gets the attribute value for FIRMA_JEFE using the alias name FirmaJefe
     */
    public String getFirmaJefe() {
        return (String) getAttributeInternal(FIRMAJEFE);
    }

    /**Sets <code>value</code> as attribute value for FIRMA_JEFE using the alias name FirmaJefe
     */
    public void setFirmaJefe(String value) {
        setAttributeInternal(FIRMAJEFE, value);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisComplementoDetVw
     */
    public RowIterator getSisComplementoDetVw() {
        return (RowIterator)getAttributeInternal(SISCOMPLEMENTODETVW);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDCOMPLEMENTO:
            return getIdComplemento();
        case IDESTADO:
            return getIdEstado();
        case IDTIPO:
            return getIdTipo();
        case IDSUBPROGRAMA:
            return getIdSubprograma();
        case PERIODO:
            return getPeriodo();
        case ANIO:
            return getAnio();
        case FECHAPRESENTACION:
            return getFechaPresentacion();
        case CREADOPOR:
            return getCreadoPor();
        case FECHACREACION:
            return getFechaCreacion();
        case MODPOR:
            return getModPor();
        case FECHAMOD:
            return getFechaMod();
        case FIRMATESO:
            return getFirmaTeso();
        case FIRMAJEFE:
            return getFirmaJefe();
        case NOMPERIODO:
            return getNomperiodo();
        case FORMATO2:
            return getFormato2();
        case NOMSUBPROG:
            return getNomsubprog();
        case CODUNIDAD:
            return getCodunidad();
        case NOMUNIDAD:
            return getNomunidad();
        case NOMESTADO:
            return getNomestado();
        case NOMUSUARIO:
            return getNomusuario();
        case IDSOLICITUD:
            return getIdSolicitud();
        case ISFORMAACTIVA:
            return getIsFormaActiva();
        case ISAUTOFINANCIABLE:
            return getIsautofinanciable();
        case SISCOMPLEMENTODETVW:
            return getSisComplementoDetVw();
        case SISCOMPLEMENTOIGSSVW:
            return getSisComplementoIgssVw();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDCOMPLEMENTO:
            setIdComplemento((Number)value);
            return;
        case IDESTADO:
            setIdEstado((Number)value);
            return;
        case IDTIPO:
            setIdTipo((Number)value);
            return;
        case IDSUBPROGRAMA:
            setIdSubprograma((Number)value);
            return;
        case PERIODO:
            setPeriodo((Number)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case FECHAPRESENTACION:
            setFechaPresentacion((Date)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case MODPOR:
            setModPor((String)value);
            return;
        case FECHAMOD:
            setFechaMod((Date)value);
            return;
        case FIRMATESO:
            setFirmaTeso((String)value);
            return;
        case FIRMAJEFE:
            setFirmaJefe((String)value);
            return;
        case NOMPERIODO:
            setNomperiodo((String)value);
            return;
        case FORMATO2:
            setFormato2((String)value);
            return;
        case NOMSUBPROG:
            setNomsubprog((String)value);
            return;
        case CODUNIDAD:
            setCodunidad((Number)value);
            return;
        case NOMUNIDAD:
            setNomunidad((String)value);
            return;
        case NOMESTADO:
            setNomestado((String)value);
            return;
        case NOMUSUARIO:
            setNomusuario((String)value);
            return;
        case IDSOLICITUD:
            setIdSolicitud((Number)value);
            return;
        case ISAUTOFINANCIABLE:
            setIsautofinanciable((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute IsFormaActiva
     */
    public Boolean getIsFormaActiva() {
       boolean vActivo=false;
    
       if (this.getIdEstado()==null){
           vActivo=true;
           
       }else{
           
          if (this.getIdEstado().compareTo(170)==0 || this.getIdEstado().compareTo(173)==0 ){
              vActivo=true;
              
          }
           
       }
    
        return vActivo;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsFormaActiva
     */
    public void setIsFormaActiva(Boolean value) {
        setAttributeInternal(ISFORMAACTIVA, value);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisComplementoIgssVw
     */
    public RowIterator getSisComplementoIgssVw() {
        return (RowIterator)getAttributeInternal(SISCOMPLEMENTOIGSSVW);
    }

    /**Gets the attribute value for the calculated attribute Nomperiodo
     */
    public String getNomperiodo() {
        return (String) getAttributeInternal(NOMPERIODO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomperiodo
     */
    public void setNomperiodo(String value) {
        setAttributeInternal(NOMPERIODO, value);
    }

    /**Gets the attribute value for the calculated attribute Formato2
     */
    public String getFormato2() {
        return (String) getAttributeInternal(FORMATO2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Formato2
     */
    public void setFormato2(String value) {
        setAttributeInternal(FORMATO2, value);
    }

    /**Gets the attribute value for the calculated attribute Nomsubprog
     */
    public String getNomsubprog() {
        return (String) getAttributeInternal(NOMSUBPROG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomsubprog
     */
    public void setNomsubprog(String value) {
        setAttributeInternal(NOMSUBPROG, value);
    }

    /**Gets the attribute value for the calculated attribute Codunidad
     */
    public Number getCodunidad() {
        return (Number) getAttributeInternal(CODUNIDAD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Codunidad
     */
    public void setCodunidad(Number value) {
        setAttributeInternal(CODUNIDAD, value);
    }

    /**Gets the attribute value for the calculated attribute Nomunidad
     */
    public String getNomunidad() {
        return (String) getAttributeInternal(NOMUNIDAD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomunidad
     */
    public void setNomunidad(String value) {
        setAttributeInternal(NOMUNIDAD, value);
    }

    /**Gets the attribute value for the calculated attribute Nomestado
     */
    public String getNomestado() {
        return (String) getAttributeInternal(NOMESTADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomestado
     */
    public void setNomestado(String value) {
        setAttributeInternal(NOMESTADO, value);
    }

    /**Gets the attribute value for the calculated attribute Nomusuario
     */
    public String getNomusuario() {
        return (String) getAttributeInternal(NOMUSUARIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomusuario
     */
    public void setNomusuario(String value) {
        setAttributeInternal(NOMUSUARIO, value);
    }

    /**Gets the attribute value for ID_SOLICITUD using the alias name IdSolicitud
     */
    public Number getIdSolicitud() {
        return (Number) getAttributeInternal(IDSOLICITUD);
    }

    /**Sets <code>value</code> as attribute value for ID_SOLICITUD using the alias name IdSolicitud
     */
    public void setIdSolicitud(Number value) {
        setAttributeInternal(IDSOLICITUD, value);
    }


    /**Gets the attribute value for ISAUTOFINANCIABLE using the alias name Isautofinanciable
     */
    public String getIsautofinanciable() {
        return (String) getAttributeInternal(ISAUTOFINANCIABLE);
    }

    /**Sets <code>value</code> as attribute value for ISAUTOFINANCIABLE using the alias name Isautofinanciable
     */
    public void setIsautofinanciable(String value) {
        setAttributeInternal(ISAUTOFINANCIABLE, value);
    }
}
