package enlace_datos.consultas.gestiones;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Sis_Departamentos2_vwRowImpl extends ViewRowImpl {
    public static final int IDDEPARTAMENTO = 0;
    public static final int NOMBRE = 1;
    public static final int REGISTRO = 2;

    /**This is the default constructor (do not remove)
     */
    public Sis_Departamentos2_vwRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute IdDepartamento
     */
    public Number getIdDepartamento() {
        return (Number) getAttributeInternal(IDDEPARTAMENTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdDepartamento
     */
    public void setIdDepartamento(Number value) {
        setAttributeInternal(IDDEPARTAMENTO, value);
    }

    /**Gets the attribute value for the calculated attribute Nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Gets the attribute value for the calculated attribute Registro
     */
    public String getRegistro() {
        return (String) getAttributeInternal(REGISTRO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Registro
     */
    public void setRegistro(String value) {
        setAttributeInternal(REGISTRO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDDEPARTAMENTO:
            return getIdDepartamento();
        case NOMBRE:
            return getNombre();
        case REGISTRO:
            return getRegistro();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDDEPARTAMENTO:
            setIdDepartamento((Number)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        case REGISTRO:
            setRegistro((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
