package enlace_datos.consultas.gestiones;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisContrato_byRegAnioImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public SisContrato_byRegAnioImpl() {
    }

    /**Gets the bind variable value for pCorrelativo
     */
    public Number getpCorrelativo() {
        return (Number)getNamedWhereClauseParam("pCorrelativo");
    }

    /**Sets <code>value</code> for bind variable pCorrelativo
     */
    public void setpCorrelativo(Number value) {
        setNamedWhereClauseParam("pCorrelativo", value);
    }

    /**Gets the bind variable value for reg_empleado
     */
    public Number getreg_empleado() {
        return (Number)getNamedWhereClauseParam("reg_empleado");
    }

    /**Sets <code>value</code> for bind variable reg_empleado
     */
    public void setreg_empleado(Number value) {
        setNamedWhereClauseParam("reg_empleado", value);
    }
}
