package enlace_datos.consultas.gestiones;

import enlace_datos.consultas.gestiones.common.SisDeduccionIsr2Vw;

import enlace_datos.util.utils_DB;

import oracle.jbo.NameValuePairs;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisDeduccionIsr2VwImpl extends ViewObjectImpl implements SisDeduccionIsr2Vw {
    /**This is the default constructor (do not remove)
     */
    public SisDeduccionIsr2VwImpl() {
    }

    /**Gets the bind variable value for pRegPer
     */
    public Number getpRegPer() {
        return (Number)getNamedWhereClauseParam("pRegPer");
    }

    /**Sets <code>value</code> for bind variable pRegPer
     */
    public void setpRegPer(Number value) {
        setNamedWhereClauseParam("pRegPer", value);
    }

    /**Gets the bind variable value for pAnio
     */
    public Number getpAnio() {
        return (Number)getNamedWhereClauseParam("pAnio");
    }

    /**Sets <code>value</code> for bind variable pAnio
     */
    public void setpAnio(Number value) {
        setNamedWhereClauseParam("pAnio", value);
    }
    
    public void verificarEmpl(Number pReg,Number pAnio,String pUsuario){
        NameValuePairs vParametros;
        vParametros= new  NameValuePairs();
        
        this.setpAnio(pAnio);
        this.setpRegPer(pReg);        
        this.executeQuery();
        
        if (this.getRowCount()==0)     
        {
        
         vParametros.setAttribute("1",pReg);
         vParametros.setAttribute("2",pAnio);
         vParametros.setAttribute("3",pUsuario);
            
         if (utils_DB.ejecutarProcedimiento(this.getDBTransaction(),"sis_pkg_calculos_isr.VERIFICAR_DEDUCCIONES_FINALES(?,?,?)",vParametros)){
             
            this.getDBTransaction().commit(); 
            this.executeQuery();
         }
         
         System.out.println("No tiene detalle");
        
        }
    }
    
}
