package enlace_datos.consultas.gestiones;

import enlace_datos.entidades.gestiones.SisSolicitudImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisSolicitudVwRowImpl extends ViewRowImpl {
    public static final int IDSOLICITUD = 0;
    public static final int NOMPUESTO1_1_1_1 = 17;
    public static final int PARTIDA1_1_1 = 18;
    public static final int NOMUSR1_1 = 25;
    public static final int IDTIPOSOLICITUD = 1;
    public static final int IDCONTRATO = 2;
    public static final int REGISTROEMPLEADO = 3;
    public static final int DOCUMENTO = 4;
    public static final int OBSERVACION = 5;
    public static final int FECHACREACION = 6;
    public static final int IDESTADO = 7;
    public static final int FECHASOLICITUD = 8;
    public static final int CREADOPOR = 9;
    public static final int NOMBRESOLICITUD = 10;
    public static final int NOMESTADO = 11;
    public static final int ANIO = 12;
    public static final int IDPARTIDA = 13;
    public static final int IDPUESTO = 14;
    public static final int NUMEROPLAZA = 15;
    public static final int ORIGEN = 16;
    public static final int NOMPUESTO = 17;
    public static final int PARTIDA = 18;
    public static final int TIPOSOLICITUD = 19;
    public static final int ESTCONTRL = 20;
    public static final int LOGAUTORIZADO = 21;
    public static final int LOGFINALIZADO = 22;
    public static final int TIPOPUESTO = 23;
    public static final int FECHAGESTION = 24;
    public static final int NOMUSR = 25;
    public static final int PROVISIONADO = 26;
    public static final int SISDETLICENCIAVW = 27;
    public static final int SISARCHIVOADJUNTOSOL = 28;
    public static final int VIEW_ORDEN_JUDICIAL = 29;
    public static final int SISSUSPENCIONIGSS = 30;
    public static final int SIS_DEUDORES_VW = 31;
    public static final int SISPROMRECLAFVIEW = 32;
    public static final int SISCOMPLEMENTOVW = 33;
    public static final int SISBENEFICIARIO = 34;
    private String vPartida;
    private String vNomPuesto;
    

    /**This is the default constructor (do not remove)
     */
    public SisSolicitudVwRowImpl() {
    }

    /**Gets SisSolicitud entity object.
     */
    public SisSolicitudImpl getSisSolicitud() {
        return (SisSolicitudImpl)getEntity(0);
    }

    /**Gets the attribute value for ID_SOLICITUD using the alias name IdSolicitud
     */
    public Number getIdSolicitud() {
        return (Number) getAttributeInternal(IDSOLICITUD);
    }

    /**Sets <code>value</code> as attribute value for ID_SOLICITUD using the alias name IdSolicitud
     */
    public void setIdSolicitud(Number value) {
        setAttributeInternal(IDSOLICITUD, value);
    }

    /**Gets the attribute value for ID_TIPO_SOLICITUD using the alias name IdTipoSolicitud
     */
    public Number getIdTipoSolicitud() {
        return (Number) getAttributeInternal(IDTIPOSOLICITUD);
    }

    /**Sets <code>value</code> as attribute value for ID_TIPO_SOLICITUD using the alias name IdTipoSolicitud
     */
    public void setIdTipoSolicitud(Number value) {
        setAttributeInternal(IDTIPOSOLICITUD, value);
    }

    /**Gets the attribute value for ID_CONTRATO using the alias name IdContrato
     */
    public Number getIdContrato() {
        return (Number) getAttributeInternal(IDCONTRATO);
    }

    /**Sets <code>value</code> as attribute value for ID_CONTRATO using the alias name IdContrato
     */
    public void setIdContrato(Number value) {
        setAttributeInternal(IDCONTRATO, value);
    }

    /**Gets the attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for DOCUMENTO using the alias name Documento
     */
    public String getDocumento() {
        return (String) getAttributeInternal(DOCUMENTO);
    }

    /**Sets <code>value</code> as attribute value for DOCUMENTO using the alias name Documento
     */
    public void setDocumento(String value) {
        setAttributeInternal(DOCUMENTO, value);
    }

    /**Gets the attribute value for OBSERVACION using the alias name Observacion
     */
    public String getObservacion() {
        return (String) getAttributeInternal(OBSERVACION);
    }

    /**Sets <code>value</code> as attribute value for OBSERVACION using the alias name Observacion
     */
    public void setObservacion(String value) {
        setAttributeInternal(OBSERVACION, value);
    }


    /**Gets the attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }


    /**Gets the attribute value for ID_ESTADO using the alias name IdEstado
     */
    public Number getIdEstado() {
    
        //System.out.println(" estado " + getAttributeInternal(IDESTADO));
        return (Number) getAttributeInternal(IDESTADO);
    }

    /**Sets <code>value</code> as attribute value for ID_ESTADO using the alias name IdEstado
     */
    public void setIdEstado(Number value) {
        setAttributeInternal(IDESTADO, value);
    }

    /**Gets the attribute value for the calculated attribute NombreSolicitud
     */
    public String getNombreSolicitud() {
        return (String) getAttributeInternal(NOMBRESOLICITUD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NombreSolicitud
     */
    public void setNombreSolicitud(String value) {
        setAttributeInternal(NOMBRESOLICITUD, value);
    }

    /**Gets the attribute value for the calculated attribute Nomestado
     */
    public String getNomestado() {
        return (String) getAttributeInternal(NOMESTADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomestado
     */
    public void setNomestado(String value) {
        setAttributeInternal(NOMESTADO, value);
    }

    /**Gets the attribute value for the calculated attribute estContrl
     */
     //Estado para habilitar los controles de las solicitudes
    public Boolean getestContrl() {
        boolean vEstado=true;        
        if (this.getNomestado()==null||this.getNomestado().equals("GRABADO")||this.getNomestado().equals("OBJETADO"))
        {
            vEstado=false;
          //  this.setestContrl(vEstado);
          
        }
        return vEstado;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute estContrl
     */
    public void setestContrl(Boolean value) {
        setAttributeInternal(ESTCONTRL, value);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisDetLicenciaVw
     */
    public RowIterator getSisDetLicenciaVw() {
        return (RowIterator)getAttributeInternal(SISDETLICENCIAVW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisArchivoAdjuntoSol
     */
    public RowIterator getSisArchivoAdjuntoSol() {
        return (RowIterator)getAttributeInternal(SISARCHIVOADJUNTOSOL);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link view_orden_judicial
     */
    public RowIterator getview_orden_judicial() {
        return (RowIterator)getAttributeInternal(VIEW_ORDEN_JUDICIAL);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisSuspencionIgss
     */
    public RowIterator getSisSuspencionIgss() {
        return (RowIterator)getAttributeInternal(SISSUSPENCIONIGSS);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDSOLICITUD:
            return getIdSolicitud();
        case IDTIPOSOLICITUD:
            return getIdTipoSolicitud();
        case IDCONTRATO:
            return getIdContrato();
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case DOCUMENTO:
            return getDocumento();
        case OBSERVACION:
            return getObservacion();
        case FECHACREACION:
            return getFechaCreacion();
        case IDESTADO:
            return getIdEstado();
        case FECHASOLICITUD:
            return getFechaSolicitud();
        case CREADOPOR:
            return getCreadoPor();
        case NOMBRESOLICITUD:
            return getNombreSolicitud();
        case NOMESTADO:
            return getNomestado();
        case ANIO:
            return getAnio();
        case IDPARTIDA:
            return getIdPartida();
        case IDPUESTO:
            return getIdPuesto();
        case NUMEROPLAZA:
            return getNumeroPlaza();
        case ORIGEN:
            return getOrigen();
        case NOMPUESTO:
            return getNomPuesto();
        case PARTIDA:
            return getPartida();
        case TIPOSOLICITUD:
            return gettipoSolicitud();
        case ESTCONTRL:
            return getestContrl();
        case LOGAUTORIZADO:
            return getlogAutorizado();
        case LOGFINALIZADO:
            return getlogFinalizado();
        case TIPOPUESTO:
            return getTipoPuesto();
        case FECHAGESTION:
            return getFechaGestion();
        case NOMUSR:
            return getNomUsr();
        case PROVISIONADO:
            return getProvisionado();
        case VIEW_ORDEN_JUDICIAL:
            return getview_orden_judicial();
        case SIS_DEUDORES_VW:
            return getSis_deudores_vw();
        case SISSUSPENCIONIGSS:
            return getSisSuspencionIgss();
        case SISDETLICENCIAVW:
            return getSisDetLicenciaVw();
        case SISARCHIVOADJUNTOSOL:
            return getSisArchivoAdjuntoSol();
        case SISPROMRECLAFVIEW:
            return getSisPromReclafView();
        case SISCOMPLEMENTOVW:
            return getSisComplementoVw();
        case SISBENEFICIARIO:
            return getSisBeneficiario();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDSOLICITUD:
            setIdSolicitud((Number)value);
            return;
        case IDTIPOSOLICITUD:
            setIdTipoSolicitud((Number)value);
            return;
        case IDCONTRATO:
            setIdContrato((Number)value);
            return;
        case REGISTROEMPLEADO:
            setRegistroEmpleado((Number)value);
            return;
        case DOCUMENTO:
            setDocumento((String)value);
            return;
        case OBSERVACION:
            setObservacion((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case IDESTADO:
            setIdEstado((Number)value);
            return;
        case FECHASOLICITUD:
            setFechaSolicitud((Date)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case NOMBRESOLICITUD:
            setNombreSolicitud((String)value);
            return;
        case NOMESTADO:
            setNomestado((String)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case IDPARTIDA:
            setIdPartida((Number)value);
            return;
        case IDPUESTO:
            setIdPuesto((Number)value);
            return;
        case NUMEROPLAZA:
            setNumeroPlaza((Number)value);
            return;
        case ORIGEN:
            setOrigen((String)value);
            return;
        case NOMPUESTO:
            setNomPuesto((String)value);
            return;
        case PARTIDA:
            setPartida((String)value);
            return;
        case TIPOSOLICITUD:
            settipoSolicitud((String)value);
            return;
        case ESTCONTRL:
            setestContrl((Boolean)value);
            return;
        case TIPOPUESTO:
            setTipoPuesto((String)value);
            return;
        case PROVISIONADO:
            setProvisionado((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the attribute value for TIPO_SOLICITUD using the alias name tipoSolicitud
     */
    public String gettipoSolicitud() {
        return (String) getAttributeInternal(TIPOSOLICITUD);
    }

    /**Sets <code>value</code> as attribute value for TIPO_SOLICITUD using the alias name tipoSolicitud
     */
    public void settipoSolicitud(String value) {
        setAttributeInternal(TIPOSOLICITUD, value);
    }

    /**Gets the attribute value for FECHA_SOLICITUD using the alias name FechaSolicitud
     */
    public Date getFechaSolicitud() {
        return (Date) getAttributeInternal(FECHASOLICITUD);
    }

    /**Sets <code>value</code> as attribute value for FECHA_SOLICITUD using the alias name FechaSolicitud
     */
    public void setFechaSolicitud(Date value) {
        setAttributeInternal(FECHASOLICITUD, value);
    }

    /**Gets the attribute value for CREADO_POR using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String) getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as attribute value for CREADO_POR using the alias name CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link Sis_deudores_vw
     */
    public RowIterator getSis_deudores_vw() {
        return (RowIterator)getAttributeInternal(SIS_DEUDORES_VW);
    }

    /**Gets the attribute value for the calculated attribute logAutorizado
     */
    public Boolean getlogAutorizado() {
    
        boolean vEstado=true;
        if (this.getNomestado()!=null && this.getNomestado().equals("AUTORIZADO")){
            vEstado=false;
          //  this.setestContrl(vEstado);
        }
        return vEstado;
        //return (Boolean) getAttributeInternal(LOGAUTORIZADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute logAutorizado
     */
    public void setlogAutorizado(Boolean value) {
        setAttributeInternal(LOGAUTORIZADO, value);
    }

    /**Gets the attribute value for the calculated attribute logFinalizado
     */
    public Boolean getlogFinalizado() {
        //return (Boolean) getAttributeInternal(LOGFINALIZADO);
        boolean vEstado=false;
        if (this.getNomestado()!=null && this.getNomestado().equals("FINALIZADO")){
            vEstado=true;
          //  this.setestContrl(vEstado);
        }
        return vEstado;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute logFinalizado
     */
    public void setlogFinalizado(Boolean value) {
        setAttributeInternal(LOGFINALIZADO, value);
    }

    /**Gets the attribute value for ANIO using the alias name Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as attribute value for ANIO using the alias name Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for ID_PARTIDA using the alias name IdPartida
     */
    public Number getIdPartida() {
        return (Number) getAttributeInternal(IDPARTIDA);
    }

    /**Sets <code>value</code> as attribute value for ID_PARTIDA using the alias name IdPartida
     */
    public void setIdPartida(Number value) {
        setAttributeInternal(IDPARTIDA, value);
    }

    /**Gets the attribute value for ID_PUESTO using the alias name IdPuesto
     */
    public Number getIdPuesto() {
        return (Number) getAttributeInternal(IDPUESTO);
    }

    /**Sets <code>value</code> as attribute value for ID_PUESTO using the alias name IdPuesto
     */
    public void setIdPuesto(Number value) {
        setAttributeInternal(IDPUESTO, value);
    }

    /**Gets the attribute value for NUMERO_PLAZA using the alias name NumeroPlaza
     */
    public Number getNumeroPlaza() {
        return (Number) getAttributeInternal(NUMEROPLAZA);
    }

    /**Sets <code>value</code> as attribute value for NUMERO_PLAZA using the alias name NumeroPlaza
     */
    public void setNumeroPlaza(Number value) {
        setAttributeInternal(NUMEROPLAZA, value);
    }

    /**Gets the attribute value for ORIGEN using the alias name Origen
     */
    public String getOrigen() {
        return (String) getAttributeInternal(ORIGEN);
    }

    /**Sets <code>value</code> as attribute value for ORIGEN using the alias name Origen
     */
    public void setOrigen(String value) {
        setAttributeInternal(ORIGEN, value);
    }


    /**Gets the attribute value for NOMPUESTO using the alias name NomPuesto
     */
    public String getNomPuesto() {
        return (String) getAttributeInternal(NOMPUESTO);
    }

    /**Sets <code>value</code> as attribute value for NOMPUESTO using the alias name NomPuesto
     */
    public void setNomPuesto(String value) {
        setAttributeInternal(NOMPUESTO, value);
    }

    /**Gets the attribute value for PARTIDA using the alias name Partida
     */
    public String getPartida() {
        return (String) getAttributeInternal(PARTIDA);
    }

    /**Sets <code>value</code> as attribute value for PARTIDA using the alias name Partida
     */
    public void setPartida(String value) {
        setAttributeInternal(PARTIDA, value);
    }


    /**Gets the associated <code>RowIterator</code> using master-detail link SisPromReclafView
     */
    public RowIterator getSisPromReclafView() {
        return (RowIterator)getAttributeInternal(SISPROMRECLAFVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisComplementoVw
     */
    public RowIterator getSisComplementoVw() {
        return (RowIterator)getAttributeInternal(SISCOMPLEMENTOVW);
    }

    /**Gets the attribute value for TIPO_PUESTO using the alias name TipoPuesto
     */
    public String getTipoPuesto() {
        return (String) getAttributeInternal(TIPOPUESTO);
    }

    /**Sets <code>value</code> as attribute value for TIPO_PUESTO using the alias name TipoPuesto
     */
    public void setTipoPuesto(String value) {
        setAttributeInternal(TIPOPUESTO, value);
    }


    /**Gets the associated <code>RowIterator</code> using master-detail link SisBeneficiario
     */
    public RowIterator getSisBeneficiario() {
        return (RowIterator)getAttributeInternal(SISBENEFICIARIO);
    }


    /**Gets the attribute value for the calculated attribute FechaGestion
     */
    public String getFechaGestion() {
        return (String) getAttributeInternal(FECHAGESTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FechaGestion
     */
    public void setFechaGestion(String value) {
        setAttributeInternal(FECHAGESTION, value);
    }


    /**Gets the attribute value for the calculated attribute NomUsr
     */
    public String getNomUsr() {
        return (String) getAttributeInternal(NOMUSR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NomUsr
     */
    public void setNomUsr(String value) {
        setAttributeInternal(NOMUSR, value);
    }


    /**Gets the attribute value for PROVISIONADO using the alias name Provisionado
     */
    public Number getProvisionado() {
        return (Number) getAttributeInternal(PROVISIONADO);
    }

    /**Sets <code>value</code> as attribute value for PROVISIONADO using the alias name Provisionado
     */
    public void setProvisionado(Number value) {
        setAttributeInternal(PROVISIONADO, value);
    }


    /**Gets the attribute value for NOMPUESTO using the alias name NomPuesto1_1_1_1
     */
    public String getNomPuesto1_1_1_1() {
        return (String) getAttributeInternal(NOMPUESTO1_1_1_1);
    }

    /**Sets <code>value</code> as attribute value for NOMPUESTO using the alias name NomPuesto1_1_1_1
     */
    public void setNomPuesto1_1_1_1(String value) {
        setAttributeInternal(NOMPUESTO1_1_1_1, value);
    }

    /**Gets the attribute value for PARTIDA using the alias name Partida1_1_1
     */
    public String getPartida1_1_1() {
        return (String) getAttributeInternal(PARTIDA1_1_1);
    }

    /**Sets <code>value</code> as attribute value for PARTIDA using the alias name Partida1_1_1
     */
    public void setPartida1_1_1(String value) {
        setAttributeInternal(PARTIDA1_1_1, value);
    }

    /**Gets the attribute value for the calculated attribute NomUsr1_1
     */
    public String getNomUsr1_1() {
        return (String) getAttributeInternal(NOMUSR1_1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NomUsr1_1
     */
    public void setNomUsr1_1(String value) {
        setAttributeInternal(NOMUSR1_1, value);
    }


}
