package enlace_datos.consultas.gestiones;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisTipoSolicitudImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public SisTipoSolicitudImpl() {
    }
}
