package enlace_datos.consultas.gestiones;

import enlace_datos.consultas.QUERRYSImpl;

import enlace_datos.entidades.gestiones.SisVariacionNominaImpl;

import enlace_datos.util.utils;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class variacion_nominaRowImpl extends ViewRowImpl {
    public static final int IDVARIACIONNOMINA = 0;
    public static final int IDCONTRATO = 1;
    public static final int ESTADOCONTRATO = 2;
    public static final int DESCRIPCION = 3;
    public static final int FECHACREACION = 4;
    public static final int CREADOPOR = 5;
    public static final int REGISTROEMPLEADO = 6;
    public static final int IDESTADO = 7;
    public static final int NOMBREESTADO = 8;
    public static final int ESTCONTRL1 = 9;
    public static final int VNOMBREAJUSTE = 10;
    public static final int DIASLABORADOS = 11;
    public static final int HORAS = 12;
    public static final int SUELDONOMINAL = 13;
    public static final int ESTATUS = 14;
    public static final int INGRESOMANUAL = 15;
    public static final int MES = 16;
    public static final int ANIO = 17;
    public static final int HECHOPOR = 18;
    public static final int APROBADOPOR = 19;
    public static final int CODOTRODESCUENTO = 20;
    public static final int VALOR = 21;
    public static final int ESCALAFON = 22;
    public static final int SIS_VARIACIONDETAJUSTE = 23;
    public static final int SIS_ARCH_ADJUNTO_VARIANOM = 24;

    /**This is the default constructor (do not remove)
     */
    public variacion_nominaRowImpl() {
    }

    /**Gets SisVariacionNomina entity object.
     */
    public SisVariacionNominaImpl getSisVariacionNomina() {
        return (SisVariacionNominaImpl)getEntity(0);
    }

    /**Gets the attribute value for ID_VARIACION_NOMINA using the alias name IdVariacionNomina
     */
    public Number getIdVariacionNomina() {
        return (Number) getAttributeInternal(IDVARIACIONNOMINA);
    }

    /**Sets <code>value</code> as attribute value for ID_VARIACION_NOMINA using the alias name IdVariacionNomina
     */
    public void setIdVariacionNomina(Number value) {
        setAttributeInternal(IDVARIACIONNOMINA, value);
    }

    /**Gets the attribute value for ID_CONTRATO using the alias name IdContrato
     */
    public Number getIdContrato() {
        return (Number) getAttributeInternal(IDCONTRATO);
    }

    /**Sets <code>value</code> as attribute value for ID_CONTRATO using the alias name IdContrato
     */
    public void setIdContrato(Number value) {
        setAttributeInternal(IDCONTRATO, value);
    }

    /**Gets the attribute value for ESTADO_CONTRATO using the alias name EstadoContrato
     */
    public Number getEstadoContrato() {
        return (Number) getAttributeInternal(ESTADOCONTRATO);
    }

    /**Sets <code>value</code> as attribute value for ESTADO_CONTRATO using the alias name EstadoContrato
     */
    public void setEstadoContrato(Number value) {
        setAttributeInternal(ESTADOCONTRATO, value); 
    }

    /**Gets the attribute value for DESCRIPCION using the alias name Descripcion
     */
    public String getDescripcion() {
        return (String) getAttributeInternal(DESCRIPCION);
    }

    /**Sets <code>value</code> as attribute value for DESCRIPCION using the alias name Descripcion
     */
    public void setDescripcion(String value) {
        setAttributeInternal(DESCRIPCION, value);
    }

    /**Gets the attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for CREADO_POR using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String) getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as attribute value for CREADO_POR using the alias name CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDVARIACIONNOMINA:
            return getIdVariacionNomina();
        case IDCONTRATO:
            return getIdContrato();
        case ESTADOCONTRATO:
            return getEstadoContrato();
        case DESCRIPCION:
            return getDescripcion();
        case FECHACREACION:
            return getFechaCreacion();
        case CREADOPOR:
            return getCreadoPor();
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case IDESTADO:
            return getIdEstado();
        case NOMBREESTADO:
            return getNombreestado();
        case ESTCONTRL1:
            return getestContrl1();
        case VNOMBREAJUSTE:
            return getvNombreAjuste();
        case DIASLABORADOS:
            return getDiaslaborados();
        case HORAS:
            return getHoras();
        case SUELDONOMINAL:
            return getSueldoNominal();
        case ESTATUS:
            return getEstatus();
        case INGRESOMANUAL:
            return getIngresoManual();
        case MES:
            return getMes();
        case ANIO:
            return getAnio();
        case HECHOPOR:
            return getHechoPor();
        case APROBADOPOR:
            return getAprobadoPor();
        case CODOTRODESCUENTO:
            return getCodOtroDescuento();
        case VALOR:
            return getValor();
        case ESCALAFON:
            return getEscalafon();
        case SIS_ARCH_ADJUNTO_VARIANOM:
            return getSis_Arch_adjunto_variaNom();
        case SIS_VARIACIONDETAJUSTE:
            return getsis_variacionDetAjuste();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDVARIACIONNOMINA:
            setIdVariacionNomina((Number)value);
            return;
        case IDCONTRATO:
            setIdContrato((Number)value);
            return;
        case ESTADOCONTRATO:
            setEstadoContrato((Number)value);
            return;
        case DESCRIPCION:
            setDescripcion((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case REGISTROEMPLEADO:
            setRegistroEmpleado((Number)value);
            return;
        case IDESTADO:
            setIdEstado((Number)value);
            return;
        case NOMBREESTADO:
            setNombreestado((String)value);
            return;
        case DIASLABORADOS:
            setDiaslaborados((Number)value);
            return;
        case HORAS:
            setHoras((Number)value);
            return;
        case SUELDONOMINAL:
            setSueldoNominal((Number)value);
            return;
        case ESTATUS:
            setEstatus((Number)value);
            return;
        case INGRESOMANUAL:
            setIngresoManual((String)value);
            return;
        case MES:
            setMes((Number)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case HECHOPOR:
            setHechoPor((String)value);
            return;
        case APROBADOPOR:
            setAprobadoPor((String)value);
            return;
        case CODOTRODESCUENTO:
            setCodOtroDescuento((String)value);
            return;
        case VALOR:
            setValor((Number)value);
            return;
        case ESCALAFON:
            setEscalafon((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link sis_variacionDetAjuste
     */
    public RowIterator getsis_variacionDetAjuste() {
        return (RowIterator)getAttributeInternal(SIS_VARIACIONDETAJUSTE);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link Sis_Arch_adjunto_variaNom
     */
    public RowIterator getSis_Arch_adjunto_variaNom() {
        return (RowIterator)getAttributeInternal(SIS_ARCH_ADJUNTO_VARIANOM);
    }

    /**Gets the attribute value for ID_ESTADO using the alias name IdEstado
     */
    public Number getIdEstado() {
        return (Number) getAttributeInternal(IDESTADO);
    }

    /**Sets <code>value</code> as attribute value for ID_ESTADO using the alias name IdEstado
     */
    public void setIdEstado(Number value) {
        setAttributeInternal(IDESTADO, value);
    }

    /**Gets the attribute value for the calculated attribute Nombreestado
     */
    public String getNombreestado() {
        return (String) getAttributeInternal(NOMBREESTADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombreestado
     */
    public void setNombreestado(String value) {
        setAttributeInternal(NOMBREESTADO, value);
    }

    /**Gets the attribute value for the calculated attribute estContrl1
     */
    public Boolean getestContrl1() {
       boolean vEstado=false;
        
        if (this.getNombreestado()!=null){
            if (!this.getNombreestado().equals("GRABADO") && !this.getNombreestado().equals("OBJETADO"))
                vEstado=true;          //  this.getApplicationModule()
            else if(this.getNombreestado().equals("OBJETADO") && (!vUsuarioEnrol("tesorero") && !vUsuarioEnrol("auxiliar_tesoreria")))    
                vEstado=true;        
        }
    
        return vEstado;
    }
    
    
    boolean vUsuarioEnrol(String pRol){
       boolean vResultado;
       try{
        vResultado=((QUERRYSImpl)this.getApplicationModule()).isUsuarioEnRol2(pRol);
       }catch(Exception exep){
           vResultado=false;
       }
      return vResultado;  
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute estContrl1
     */
    public void setestContrl1(Boolean value) {
        setAttributeInternal(ESTCONTRL1, value);
    }

    /**Gets the attribute value for the calculated attribute vNombreAjuste
     */
    public String getvNombreAjuste() {
        Row[] vFilas;
        vFilas=this.getsis_variacionDetAjuste().getAllRowsInRange();
        String vNombre=null;
        
        if (vFilas!=null && vFilas.length>0){
            vNombre=vFilas[0].getAttribute("Nombre").toString();    
        }
                
        return vNombre;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute vNombreAjuste
     */
    public void setvNombreAjuste(String value) {
        setAttributeInternal(VNOMBREAJUSTE, value);
    }


    /**Gets the attribute value for DIASLABORADOS using the alias name Diaslaborados
     */
    public Number getDiaslaborados() {
        return (Number) getAttributeInternal(DIASLABORADOS);
    }

    /**Sets <code>value</code> as attribute value for DIASLABORADOS using the alias name Diaslaborados
     */
    public void setDiaslaborados(Number value) {
        setAttributeInternal(DIASLABORADOS, value);
    }

    /**Gets the attribute value for HORAS using the alias name Horas
     */
    public Number getHoras() {
        return (Number) getAttributeInternal(HORAS);
    }

    /**Sets <code>value</code> as attribute value for HORAS using the alias name Horas
     */
    public void setHoras(Number value) {
        setAttributeInternal(HORAS, value);
    }

    /**Gets the attribute value for SUELDO_NOMINAL using the alias name SueldoNominal
     */
    public Number getSueldoNominal() {
        return (Number) getAttributeInternal(SUELDONOMINAL);
    }

    /**Sets <code>value</code> as attribute value for SUELDO_NOMINAL using the alias name SueldoNominal
     */
    public void setSueldoNominal(Number value) {
        setAttributeInternal(SUELDONOMINAL, value);
    }

    /**Gets the attribute value for ESTATUS using the alias name Estatus
     */
    public Number getEstatus() {
        return (Number) getAttributeInternal(ESTATUS);
    }

    /**Sets <code>value</code> as attribute value for ESTATUS using the alias name Estatus
     */
    public void setEstatus(Number value) {
        setAttributeInternal(ESTATUS, value);
    }

    /**Gets the attribute value for INGRESO_MANUAL using the alias name IngresoManual
     */
    public String getIngresoManual() {
        return (String) getAttributeInternal(INGRESOMANUAL);
    }

    /**Sets <code>value</code> as attribute value for INGRESO_MANUAL using the alias name IngresoManual
     */
    public void setIngresoManual(String value) {
        setAttributeInternal(INGRESOMANUAL, value);
    }

    /**Gets the attribute value for MES using the alias name Mes
     */
    public Number getMes() {
        return (Number) getAttributeInternal(MES);
    }

    /**Sets <code>value</code> as attribute value for MES using the alias name Mes
     */
    public void setMes(Number value) {
        setAttributeInternal(MES, value);
    }

    /**Gets the attribute value for ANIO using the alias name Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as attribute value for ANIO using the alias name Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for HECHO_POR using the alias name HechoPor
     */
    public String getHechoPor() {
        return (String) getAttributeInternal(HECHOPOR);
    }

    /**Sets <code>value</code> as attribute value for HECHO_POR using the alias name HechoPor
     */
    public void setHechoPor(String value) {
        setAttributeInternal(HECHOPOR, value);
    }

    /**Gets the attribute value for APROBADO_POR using the alias name AprobadoPor
     */
    public String getAprobadoPor() {
        return (String) getAttributeInternal(APROBADOPOR);
    }

    /**Sets <code>value</code> as attribute value for APROBADO_POR using the alias name AprobadoPor
     */
    public void setAprobadoPor(String value) {
        setAttributeInternal(APROBADOPOR, value);
    }

    /**Gets the attribute value for COD_OTRO_DESCUENTO using the alias name CodOtroDescuento
     */
    public String getCodOtroDescuento() {
        return (String) getAttributeInternal(CODOTRODESCUENTO);
    }

    /**Sets <code>value</code> as attribute value for COD_OTRO_DESCUENTO using the alias name CodOtroDescuento
     */
    public void setCodOtroDescuento(String value) {
        setAttributeInternal(CODOTRODESCUENTO, value);
    }

    /**Gets the attribute value for VALOR using the alias name Valor
     */
    public Number getValor() {
        return (Number) getAttributeInternal(VALOR);
    }

    /**Sets <code>value</code> as attribute value for VALOR using the alias name Valor
     */
    public void setValor(Number value) {
        setAttributeInternal(VALOR, value);
    }

    /**Gets the attribute value for ESCALAFON using the alias name Escalafon
     */
    public Number getEscalafon() {
        return (Number) getAttributeInternal(ESCALAFON);
    }

    /**Sets <code>value</code> as attribute value for ESCALAFON using the alias name Escalafon
     */
    public void setEscalafon(Number value) {
        setAttributeInternal(ESCALAFON, value);
    }
}
