package enlace_datos.consultas.gestiones.contrato.client;

import enlace_datos.consultas.gestiones.contrato.common.SisAuthContratoVw;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisAuthContratoVwClient extends ViewUsageImpl implements SisAuthContratoVw {
    /**This is the default constructor (do not remove)
     */
    public SisAuthContratoVwClient() {
    }

    public void darBaja() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"darBaja",null,null);
        return;
    }
}
