package enlace_datos.consultas.gestiones.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class SisIsrproy031vwRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "NomTipoNomina_LABEL", "Tipo Nomina" },
{ "DocPendienteAnio_LABEL", "Doc. Pendiente" },
{ "IdTipoNomina_LABEL", "Tipo nómina" },
{ "Anio_LABEL", "Año" },
{ "IdIsr_LABEL", "ID" }};

    /**This is the default constructor (do not remove)
     */
    public SisIsrproy031vwRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
