package enlace_datos.consultas.gestiones.anexo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class consul_puesto_promocion_vwImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public consul_puesto_promocion_vwImpl() {
    }

    /**Gets the bind variable value for varNivel
     */
    public String getvarNivel() {
        return (String)getNamedWhereClauseParam("varNivel");
    }

    /**Sets <code>value</code> for bind variable varNivel
     */
    public void setvarNivel(String value) {
        setNamedWhereClauseParam("varNivel", value);
        
        if (value.equals("ADMINISTRATIVO")){
            this.setWhereClause("");   
        }
        else if (value.equals("DOCENTE")) {
           String linea = "  and UPPER(categoria.NOMBRE) like 'TITULAR'";
           this.setWhereClause(linea);
        }
        
        }
}
