package enlace_datos.consultas.varios;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Sis_historial_det1RowImpl extends ViewRowImpl {
    public static final int REGISTROEMPLEADO = 0;
    public static final int NOMBRECOMPLETO = 1;
    public static final int PARTIDA1 = 2;
    public static final int PARTIDA2 = 3;
    public static final int NUMEROPLAZA = 4;
    public static final int TIPONOMINA = 5;
    public static final int PERIODO = 6;
    public static final int ANIO = 7;
    public static final int NOMINAL = 8;
    public static final int TOTALDESCUENTO = 9;
    public static final int LIQUIDO = 10;
    public static final int TOTALBONO = 11;
    public static final int NUMDOCFISICO = 12;
    public static final int TIPOPAGO = 13;
    public static final int NOMBREBANCO = 14;
    public static final int FECHAREF = 15;
    public static final int FECHAANULACION = 16;
    public static final int NOMBRE = 17;
    public static final int NOMCATEGORIA = 18;
    public static final int NOMNIVEL = 19;
    public static final int NOMTIPO = 20;
    public static final int IDNOMINA = 21;
    public static final int IDDOCUMENTOBANCO = 22;
    public static final int NOMDEP = 23;
    public static final int NOMUNI = 24;
    public static final int IDPUESTO = 25;
    public static final int CORRELATIVO = 26;
    public static final int CODIGONOMINA = 27;
    public static final int TOTALNOM1 = 28;
    public static final int TOTALBONO1 = 29;
    public static final int VTOTALDESC1 = 30;
    public static final int VTOTALLIQUIDO1 = 31;
    public static final int SISDETCALCULOAJUSTEAGRUPVW = 32;

    /**This is the default constructor (do not remove)
     */
    public Sis_historial_det1RowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for the calculated attribute Nombrecompleto
     */
    public String getNombrecompleto() {
        return (String) getAttributeInternal(NOMBRECOMPLETO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombrecompleto
     */
    public void setNombrecompleto(String value) {
        setAttributeInternal(NOMBRECOMPLETO, value);
    }

    /**Gets the attribute value for the calculated attribute Partida1
     */
    public String getPartida1() {
        return (String) getAttributeInternal(PARTIDA1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Partida1
     */
    public void setPartida1(String value) {
        setAttributeInternal(PARTIDA1, value);
    }

    /**Gets the attribute value for the calculated attribute Partida2
     */
    public String getPartida2() {
        return (String) getAttributeInternal(PARTIDA2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Partida2
     */
    public void setPartida2(String value) {
        setAttributeInternal(PARTIDA2, value);
    }

    /**Gets the attribute value for the calculated attribute NumeroPlaza
     */
    public Number getNumeroPlaza() {
        return (Number) getAttributeInternal(NUMEROPLAZA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumeroPlaza
     */
    public void setNumeroPlaza(Number value) {
        setAttributeInternal(NUMEROPLAZA, value);
    }

    /**Gets the attribute value for the calculated attribute Tiponomina
     */
    public String getTiponomina() {
        return (String) getAttributeInternal(TIPONOMINA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tiponomina
     */
    public void setTiponomina(String value) {
        setAttributeInternal(TIPONOMINA, value);
    }

    /**Gets the attribute value for the calculated attribute Periodo
     */
    public String getPeriodo() {
        return (String) getAttributeInternal(PERIODO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Periodo
     */
    public void setPeriodo(String value) {
        setAttributeInternal(PERIODO, value);
    }

    /**Gets the attribute value for the calculated attribute Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for the calculated attribute Nominal
     */
    public Number getNominal() {
        return (Number) getAttributeInternal(NOMINAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nominal
     */
    public void setNominal(Number value) {
        setAttributeInternal(NOMINAL, value);
    }

    /**Gets the attribute value for the calculated attribute TotalDescuento
     */
    public Number getTotalDescuento() {
        return (Number) getAttributeInternal(TOTALDESCUENTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TotalDescuento
     */
    public void setTotalDescuento(Number value) {
        setAttributeInternal(TOTALDESCUENTO, value);
    }

    /**Gets the attribute value for the calculated attribute Liquido
     */
    public Number getLiquido() {
        return (Number) getAttributeInternal(LIQUIDO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Liquido
     */
    public void setLiquido(Number value) {
        setAttributeInternal(LIQUIDO, value);
    }

    /**Gets the attribute value for the calculated attribute TotalBono
     */
    public Number getTotalBono() {
        return (Number) getAttributeInternal(TOTALBONO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TotalBono
     */
    public void setTotalBono(Number value) {
        setAttributeInternal(TOTALBONO, value);
    }

    /**Gets the attribute value for the calculated attribute NumDocFisico
     */
    public Number getNumDocFisico() {
        return (Number) getAttributeInternal(NUMDOCFISICO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumDocFisico
     */
    public void setNumDocFisico(Number value) {
        setAttributeInternal(NUMDOCFISICO, value);
    }

    /**Gets the attribute value for the calculated attribute Tipopago
     */
    public String getTipopago() {
        return (String) getAttributeInternal(TIPOPAGO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tipopago
     */
    public void setTipopago(String value) {
        setAttributeInternal(TIPOPAGO, value);
    }

    /**Gets the attribute value for the calculated attribute Nombrebanco
     */
    public String getNombrebanco() {
        return (String) getAttributeInternal(NOMBREBANCO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombrebanco
     */
    public void setNombrebanco(String value) {
        setAttributeInternal(NOMBREBANCO, value);
    }

    /**Gets the attribute value for the calculated attribute FechaRef
     */
    public Date getFechaRef() {
        return (Date) getAttributeInternal(FECHAREF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FechaRef
     */
    public void setFechaRef(Date value) {
        setAttributeInternal(FECHAREF, value);
    }

    /**Gets the attribute value for the calculated attribute FechaAnulacion
     */
    public Date getFechaAnulacion() {
        return (Date) getAttributeInternal(FECHAANULACION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FechaAnulacion
     */
    public void setFechaAnulacion(Date value) {
        setAttributeInternal(FECHAANULACION, value);
    }

    /**Gets the attribute value for the calculated attribute Nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Gets the attribute value for the calculated attribute Nomcategoria
     */
    public String getNomcategoria() {
       
        return (String) getAttributeInternal(NOMCATEGORIA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomcategoria
     */
    public void setNomcategoria(String value) {
        setAttributeInternal(NOMCATEGORIA, value);
    }

    /**Gets the attribute value for the calculated attribute Nomnivel
     */
    public String getNomnivel() {
        return (String) getAttributeInternal(NOMNIVEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomnivel
     */
    public void setNomnivel(String value) {
        setAttributeInternal(NOMNIVEL, value);
    }

    /**Gets the attribute value for the calculated attribute Nomtipo
     */
    public String getNomtipo() {
        return (String) getAttributeInternal(NOMTIPO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomtipo
     */
    public void setNomtipo(String value) {
        setAttributeInternal(NOMTIPO, value);
    }

    /**Gets the attribute value for the calculated attribute IdNomina
     */
    public Number getIdNomina() {
        return (Number) getAttributeInternal(IDNOMINA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdNomina
     */
    public void setIdNomina(Number value) {
        setAttributeInternal(IDNOMINA, value);
    }

    /**Gets the attribute value for the calculated attribute IdDocumentoBanco
     */
    public Number getIdDocumentoBanco() {
        return (Number) getAttributeInternal(IDDOCUMENTOBANCO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdDocumentoBanco
     */
    public void setIdDocumentoBanco(Number value) {
        setAttributeInternal(IDDOCUMENTOBANCO, value);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case NOMBRECOMPLETO:
            return getNombrecompleto();
        case PARTIDA1:
            return getPartida1();
        case PARTIDA2:
            return getPartida2();
        case NUMEROPLAZA:
            return getNumeroPlaza();
        case TIPONOMINA:
            return getTiponomina();
        case PERIODO:
            return getPeriodo();
        case ANIO:
            return getAnio();
        case NOMINAL:
            return getNominal();
        case TOTALDESCUENTO:
            return getTotalDescuento();
        case LIQUIDO:
            return getLiquido();
        case TOTALBONO:
            return getTotalBono();
        case NUMDOCFISICO:
            return getNumDocFisico();
        case TIPOPAGO:
            return getTipopago();
        case NOMBREBANCO:
            return getNombrebanco();
        case FECHAREF:
            return getFechaRef();
        case FECHAANULACION:
            return getFechaAnulacion();
        case NOMBRE:
            return getNombre();
        case NOMCATEGORIA:
            return getNomcategoria();
        case NOMNIVEL:
            return getNomnivel();
        case NOMTIPO:
            return getNomtipo();
        case IDNOMINA:
            return getIdNomina();
        case IDDOCUMENTOBANCO:
            return getIdDocumentoBanco();
        case NOMDEP:
            return getNomdep();
        case NOMUNI:
            return getNomuni();
        case IDPUESTO:
            return getIdPuesto();
        case CORRELATIVO:
            return getCorrelativo();
        case CODIGONOMINA:
            return getCodigonomina();
        case TOTALNOM1:
            return getTotalNom1();
        case TOTALBONO1:
            return getTotalBono1();
        case VTOTALDESC1:
            return getvTotalDesc1();
        case VTOTALLIQUIDO1:
            return getvTotalLiquido1();
        case SISDETCALCULOAJUSTEAGRUPVW:
            return getSisDetCalculoAjusteAgrupVw();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case NOMDEP:
            setNomdep((String)value);
            return;
        case NOMUNI:
            setNomuni((String)value);
            return;
        case IDPUESTO:
            setIdPuesto((Number)value);
            return;
        case CORRELATIVO:
            setCorrelativo((Number)value);
            return;
        case CODIGONOMINA:
            setCodigonomina((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisDetCalculoAjusteAgrupVw
     */
    public RowIterator getSisDetCalculoAjusteAgrupVw() {
        return (RowIterator)getAttributeInternal(SISDETCALCULOAJUSTEAGRUPVW);
    }

    /**Gets the attribute value for the calculated attribute TotalNom1
     */
    public Number getTotalNom1() {
        Sis_historial_det1Impl vViewObj;
        vViewObj=(Sis_historial_det1Impl)this.getViewObject();
        return vViewObj.getTotalNominal();

    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TotalNom1
     */
    public void setTotalNom1(Number value) {
        setAttributeInternal(TOTALNOM1, value);
    }

    /**Gets the attribute value for the calculated attribute TotalBono1
     */
    public Number getTotalBono1() {
        Sis_historial_det1Impl vViewObj;
        vViewObj=(Sis_historial_det1Impl)this.getViewObject();
        return vViewObj.getTotalBono();
        
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TotalBono1
     */
    public void setTotalBono1(Number value) {
        setAttributeInternal(TOTALBONO1, value);
    }

    /**Gets the attribute value for the calculated attribute vTotalDesc1
     */
    public Number getvTotalDesc1() {
        Sis_historial_det1Impl vViewObj;
        vViewObj=(Sis_historial_det1Impl)this.getViewObject();
        return vViewObj.getTotalDescuento();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute vTotalDesc1
     */
    public void setvTotalDesc1(Number value) {
        setAttributeInternal(VTOTALDESC1, value);
    }

    /**Gets the attribute value for the calculated attribute vTotalLiquido1
     */
    public Number getvTotalLiquido1() {
        Sis_historial_det1Impl vViewObj;
        vViewObj=(Sis_historial_det1Impl)this.getViewObject();
        return vViewObj.getTotalLiquido();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute vTotalLiquido1
     */
    public void setvTotalLiquido1(Number value) {
        setAttributeInternal(VTOTALLIQUIDO1, value);
    }

    /**Gets the attribute value for the calculated attribute Nomdep
     */
    public String getNomdep() {
        return (String) getAttributeInternal(NOMDEP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomdep
     */
    public void setNomdep(String value) {
        setAttributeInternal(NOMDEP, value);
    }

    /**Gets the attribute value for the calculated attribute Nomuni
     */
    public String getNomuni() {
        return (String) getAttributeInternal(NOMUNI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomuni
     */
    public void setNomuni(String value) {
        setAttributeInternal(NOMUNI, value);
    }

    /**Gets the attribute value for the calculated attribute IdPuesto
     */
    public Number getIdPuesto() {
        return (Number) getAttributeInternal(IDPUESTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdPuesto
     */
    public void setIdPuesto(Number value) {
        setAttributeInternal(IDPUESTO, value);
    }


    /**Gets the attribute value for the calculated attribute Correlativo
     */
    public Number getCorrelativo() {
        return (Number) getAttributeInternal(CORRELATIVO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Correlativo
     */
    public void setCorrelativo(Number value) {
        setAttributeInternal(CORRELATIVO, value);
    }


    /**Gets the attribute value for the calculated attribute Codigonomina
     */
    public String getCodigonomina() {
        return (String) getAttributeInternal(CODIGONOMINA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Codigonomina
     */
    public void setCodigonomina(String value) {
        setAttributeInternal(CODIGONOMINA, value);
    }


}
