package enlace_datos.consultas.gestiones.contrato;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class empleado_by_regRowImpl extends ViewRowImpl {
    public static final int REGISTROEMPLEADO = 0;
    public static final int NOMBRE1 = 1;
    public static final int NOMBRE2 = 2;
    public static final int NOMBRE3 = 3;
    public static final int APELLIDO1 = 4;
    public static final int APELLIDO2 = 5;
    public static final int APELLIDOCASADA = 6;
    public static final int NUMCEDULA = 7;
    public static final int EXTENDIDA = 8;
    public static final int EDAD = 9;
    public static final int ESTADOCIVIL = 10;
    public static final int NACIONALIDAD = 11;
    public static final int DESCRIPCION = 12;
    public static final int DIRECCION = 13;
    public static final int COLEGIADO = 14;
    public static final int CUI = 15;
    public static final int NOMBRECOMPLETO = 16;

    /**This is the default constructor (do not remove)
     */
    public empleado_by_regRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for the calculated attribute Nombre1
     */
    public String getNombre1() {
        return (String) getAttributeInternal(NOMBRE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre1
     */
    public void setNombre1(String value) {
        setAttributeInternal(NOMBRE1, value);
    }

    /**Gets the attribute value for the calculated attribute Nombre2
     */
    public String getNombre2() {
        return (String) getAttributeInternal(NOMBRE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre2
     */
    public void setNombre2(String value) {
        setAttributeInternal(NOMBRE2, value);
    }

    /**Gets the attribute value for the calculated attribute Nombre3
     */
    public String getNombre3() {
        return (String) getAttributeInternal(NOMBRE3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre3
     */
    public void setNombre3(String value) {
        setAttributeInternal(NOMBRE3, value);
    }

    /**Gets the attribute value for the calculated attribute Apellido1
     */
    public String getApellido1() {
        return (String) getAttributeInternal(APELLIDO1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Apellido1
     */
    public void setApellido1(String value) {
        setAttributeInternal(APELLIDO1, value);
    }

    /**Gets the attribute value for the calculated attribute Apellido2
     */
    public String getApellido2() {
        return (String) getAttributeInternal(APELLIDO2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Apellido2
     */
    public void setApellido2(String value) {
        setAttributeInternal(APELLIDO2, value);
    }

    /**Gets the attribute value for the calculated attribute Apellidocasada
     */
    public String getApellidocasada() {
        return (String) getAttributeInternal(APELLIDOCASADA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Apellidocasada
     */
    public void setApellidocasada(String value) {
        setAttributeInternal(APELLIDOCASADA, value);
    }

    /**Gets the attribute value for the calculated attribute NumCedula
     */
    public String getNumCedula() {
        return (String) getAttributeInternal(NUMCEDULA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumCedula
     */
    public void setNumCedula(String value) {
        setAttributeInternal(NUMCEDULA, value);
    }

    /**Gets the attribute value for the calculated attribute Extendida
     */
    public String getExtendida() {
        return (String) getAttributeInternal(EXTENDIDA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Extendida
     */
    public void setExtendida(String value) {
        setAttributeInternal(EXTENDIDA, value);
    }

    /**Gets the attribute value for the calculated attribute Edad
     */
    public Number getEdad() {
        return (Number) getAttributeInternal(EDAD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Edad
     */
    public void setEdad(Number value) {
        setAttributeInternal(EDAD, value);
    }

    /**Gets the attribute value for the calculated attribute Estadocivil
     */
    public String getEstadocivil() {
        return (String) getAttributeInternal(ESTADOCIVIL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Estadocivil
     */
    public void setEstadocivil(String value) {
        setAttributeInternal(ESTADOCIVIL, value);
    }

    /**Gets the attribute value for the calculated attribute Nacionalidad
     */
    public String getNacionalidad() {
        return (String) getAttributeInternal(NACIONALIDAD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nacionalidad
     */
    public void setNacionalidad(String value) {
        setAttributeInternal(NACIONALIDAD, value);
    }

    /**Gets the attribute value for the calculated attribute Descripcion
     */
    public String getDescripcion() {
        return (String) getAttributeInternal(DESCRIPCION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Descripcion
     */
    public void setDescripcion(String value) {
        setAttributeInternal(DESCRIPCION, value);
    }

    /**Gets the attribute value for the calculated attribute Direccion
     */
    public String getDireccion() {
        return (String) getAttributeInternal(DIRECCION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Direccion
     */
    public void setDireccion(String value) {
        setAttributeInternal(DIRECCION, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case NOMBRE1:
            return getNombre1();
        case NOMBRE2:
            return getNombre2();
        case NOMBRE3:
            return getNombre3();
        case APELLIDO1:
            return getApellido1();
        case APELLIDO2:
            return getApellido2();
        case APELLIDOCASADA:
            return getApellidocasada();
        case NUMCEDULA:
            return getNumCedula();
        case EXTENDIDA:
            return getExtendida();
        case EDAD:
            return getEdad();
        case ESTADOCIVIL:
            return getEstadocivil();
        case NACIONALIDAD:
            return getNacionalidad();
        case DESCRIPCION:
            return getDescripcion();
        case DIRECCION:
            return getDireccion();
        case COLEGIADO:
            return getColegiado();
        case CUI:
            return getCui();
        case NOMBRECOMPLETO:
            return getNombreCompleto();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            setRegistroEmpleado((Number)value);
            return;
        case NOMBRE1:
            setNombre1((String)value);
            return;
        case NOMBRE2:
            setNombre2((String)value);
            return;
        case NOMBRE3:
            setNombre3((String)value);
            return;
        case APELLIDO1:
            setApellido1((String)value);
            return;
        case APELLIDO2:
            setApellido2((String)value);
            return;
        case APELLIDOCASADA:
            setApellidocasada((String)value);
            return;
        case NUMCEDULA:
            setNumCedula((String)value);
            return;
        case EXTENDIDA:
            setExtendida((String)value);
            return;
        case EDAD:
            setEdad((Number)value);
            return;
        case ESTADOCIVIL:
            setEstadocivil((String)value);
            return;
        case NACIONALIDAD:
            setNacionalidad((String)value);
            return;
        case DESCRIPCION:
            setDescripcion((String)value);
            return;
        case DIRECCION:
            setDireccion((String)value);
            return;
        case COLEGIADO:
            setColegiado((String)value);
            return;
        case CUI:
            setCui((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute NombreCompleto
     */
    public String getNombreCompleto() {
       String str_nombrecompleto;
       str_nombrecompleto=this.getNombre1();
       str_nombrecompleto=str_nombrecompleto + (this.getNombre2()==null?"":" "+this.getNombre2());
       str_nombrecompleto=str_nombrecompleto + (this.getNombre3()!=null?" "+this.getNombre3():"");
       str_nombrecompleto=str_nombrecompleto + (this.getApellido1()==null?"":" "+this.getApellido1())+(this.getApellido2()==null?"":" "+this.getApellido2())+(this.getApellidocasada()==null?"":" "+this.getApellidocasada());    
       return str_nombrecompleto;
       
       
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NombreCompleto
     */
    public void setNombreCompleto(String value) {
        setAttributeInternal(NOMBRECOMPLETO, value);
    }

    /**Gets the attribute value for the calculated attribute Colegiado
     */
    public String getColegiado() {
        return (String) getAttributeInternal(COLEGIADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Colegiado
     */
    public void setColegiado(String value) {
        setAttributeInternal(COLEGIADO, value);
    }

    /**Gets the attribute value for the calculated attribute Cui
     */
    public String getCui() {
        return (String) getAttributeInternal(CUI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cui
     */
    public void setCui(String value) {
        setAttributeInternal(CUI, value);
    }
}
