package enlace_datos.consultas.gestiones.contrato;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisContratosActivosDepImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public SisContratosActivosDepImpl() {
    }

    /**Gets the bind variable value for pAnio
     */
    public Number getpAnio() {
        return (Number)getNamedWhereClauseParam("pAnio");
    }

    /**Sets <code>value</code> for bind variable pAnio
     */
    public void setpAnio(Number value) {
        setNamedWhereClauseParam("pAnio", value);
    }

    /**Gets the bind variable value for pDep
     */
    public Number getpDep() {
        return (Number)getNamedWhereClauseParam("pDep");
    }

    /**Sets <code>value</code> for bind variable pDep
     */
    public void setpDep(Number value) {
        setNamedWhereClauseParam("pDep", value);
    }

    /**Gets the bind variable value for pIdContrato
     */
    public Number getpIdContrato() {
        return (Number)getNamedWhereClauseParam("pIdContrato");
    }

    /**Sets <code>value</code> for bind variable pIdContrato
     */
    public void setpIdContrato(Number value) {
        setNamedWhereClauseParam("pIdContrato", value);
    }
}
