package enlace_datos.consultas.gestiones.procesos;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class tipo_proceso_vwRowImpl extends ViewRowImpl {
    public static final int IDTIPOPROCESO = 0;
    public static final int NOMBRE = 1;
    public static final int CONFPERIODO = 2;
    public static final int PERIODOS_PROC_VW = 3;

    /**This is the default constructor (do not remove)
     */
    public tipo_proceso_vwRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute IdTipoproceso
     */
    public Number getIdTipoproceso() {
        return (Number) getAttributeInternal(IDTIPOPROCESO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdTipoproceso
     */
    public void setIdTipoproceso(Number value) {
        setAttributeInternal(IDTIPOPROCESO, value);
    }

    /**Gets the attribute value for the calculated attribute Nombre
     */
    public String getNombre() {
      
        return (String) getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link periodos_proc_vw
     */
    public RowIterator getperiodos_proc_vw() {
        return (RowIterator)getAttributeInternal(PERIODOS_PROC_VW);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDTIPOPROCESO:
            return getIdTipoproceso();
        case NOMBRE:
            return getNombre();
        case CONFPERIODO:
            return getConfPeriodo();
        case PERIODOS_PROC_VW:
            return getperiodos_proc_vw();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CONFPERIODO:
            setConfPeriodo((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute ConfPeriodo
     */
    public String getConfPeriodo() {
        return (String) getAttributeInternal(CONFPERIODO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConfPeriodo
     */
    public void setConfPeriodo(String value) {
        setAttributeInternal(CONFPERIODO, value);
    }
}
