package enlace_datos.entidades.procesos;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisSueldoCuentaImpl extends EntityImpl {
    public static final int DESCRIPCION = 0;
    public static final int FECHAALTA = 1;
    public static final int FECHABAJA = 2;
    public static final int IDCUENTABANCANCARIA = 3;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisSueldoCuentaImpl() {
    }

    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.procesos.SisSueldoCuenta");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Descripcion, using the alias name Descripcion
     */
    public String getDescripcion() {
        return (String)getAttributeInternal(DESCRIPCION);
    }

    /**Sets <code>value</code> as the attribute value for Descripcion
     */
    public void setDescripcion(String value) {
        setAttributeInternal(DESCRIPCION, value);
    }

    /**Gets the attribute value for FechaAlta, using the alias name FechaAlta
     */
    public Date getFechaAlta() {
        return (Date)getAttributeInternal(FECHAALTA);
    }

    /**Sets <code>value</code> as the attribute value for FechaAlta
     */
    public void setFechaAlta(Date value) {
        setAttributeInternal(FECHAALTA, value);
    }

    /**Gets the attribute value for FechaBaja, using the alias name FechaBaja
     */
    public Date getFechaBaja() {
        return (Date)getAttributeInternal(FECHABAJA);
    }

    /**Sets <code>value</code> as the attribute value for FechaBaja
     */
    public void setFechaBaja(Date value) {
        setAttributeInternal(FECHABAJA, value);
    }

    /**Gets the attribute value for IdCuentaBancancaria, using the alias name IdCuentaBancancaria
     */
    public Number getIdCuentaBancancaria() {
        return (Number)getAttributeInternal(IDCUENTABANCANCARIA);
    }

    /**Sets <code>value</code> as the attribute value for IdCuentaBancancaria
     */
    public void setIdCuentaBancancaria(Number value) {
        setAttributeInternal(IDCUENTABANCANCARIA, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DESCRIPCION:
            return getDescripcion();
        case FECHAALTA:
            return getFechaAlta();
        case FECHABAJA:
            return getFechaBaja();
        case IDCUENTABANCANCARIA:
            return getIdCuentaBancancaria();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DESCRIPCION:
            setDescripcion((String)value);
            return;
        case FECHAALTA:
            setFechaAlta((Date)value);
            return;
        case FECHABAJA:
            setFechaBaja((Date)value);
            return;
        case IDCUENTABANCANCARIA:
            setIdCuentaBancancaria((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Date fechaAlta, 
                                       Number idCuentaBancancaria) {
        return new Key(new Object[]{fechaAlta, idCuentaBancancaria});
    }
}
