package enlace_datos.entidades.procesos;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisTipoProcesoImpl extends EntityImpl {
    public static final int IDTIPOPROCESO = 0;
    public static final int NOMBRE = 1;
    public static final int DESCRIPCION = 2;
    public static final int SISTIPOPROCPERIODO = 3;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisTipoProcesoImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.procesos.SisTipoProceso");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdTipoproceso, using the alias name IdTipoproceso
     */
    public Number getIdTipoproceso() {
        return (Number)getAttributeInternal(IDTIPOPROCESO);
    }

    /**Sets <code>value</code> as the attribute value for IdTipoproceso
     */
    public void setIdTipoproceso(Number value) {
        setAttributeInternal(IDTIPOPROCESO, value);
    }

    /**Gets the attribute value for Nombre, using the alias name Nombre
     */
    public String getNombre() {
        return (String)getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Gets the attribute value for Descripcion, using the alias name Descripcion
     */
    public String getDescripcion() {
        return (String)getAttributeInternal(DESCRIPCION);
    }

    /**Sets <code>value</code> as the attribute value for Descripcion
     */
    public void setDescripcion(String value) {
        setAttributeInternal(DESCRIPCION, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDTIPOPROCESO:
            return getIdTipoproceso();
        case NOMBRE:
            return getNombre();
        case DESCRIPCION:
            return getDescripcion();
        case SISTIPOPROCPERIODO:
            return getSisTipoprocPeriodo();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDTIPOPROCESO:
            setIdTipoproceso((Number)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        case DESCRIPCION:
            setDescripcion((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getSisTipoprocPeriodo() {
        return (RowIterator)getAttributeInternal(SISTIPOPROCPERIODO);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idTipoproceso) {
        return new Key(new Object[]{idTipoproceso});
    }
}
