package enlace_datos.consultas.gestiones.indemnizaciones.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface SisIndemnizacion_vw extends ViewObject {


    String ObtenerNumeroContratosFinalizadosTrabajador(Number pRegistroEmpleado, 
                                                       Date pFechaFallecimiento);

    String ObtenerContratosTrabajadorFallecido(Number pRegistroEmpleado, 
                                               Date pFechaFallecimiento);

    void RecuperarSolicitudesIndemnizacion();

    void RecuperarExpediente(Number pIdIndemnizacion);
}
