package enlace_datos.entidades.procesos;

import enlace_datos.consultas.procesos.detalle_asig_chequeRowImpl;

import enlace_datos.entidades.gestiones.procesos.SisProcesoImpl;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisAsignacionNumChequeImpl extends EntityImpl {
    public static final int IDASIGNACIONNUMCHEQUE = 0;
    public static final int IDTIPOPROCESO = 3;
    public static final int IDBANCO = 1;
    public static final int FECHACREACION = 2;
    public static final int IDPROCESO = 3;
    public static final int NOMBRE = 4;
    public static final int SISDETASIGCHEQUE = 5;
    public static final int SISPROCESO = 6;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisAsignacionNumChequeImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.procesos.SisAsignacionNumCheque");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdAsignacionNumCheque, using the alias name IdAsignacionNumCheque
     */
    public DBSequence getIdAsignacionNumCheque() {
        return (DBSequence)getAttributeInternal(IDASIGNACIONNUMCHEQUE);
    }

    /**Sets <code>value</code> as the attribute value for IdAsignacionNumCheque
     */
    public void setIdAsignacionNumCheque(DBSequence value) {
        setAttributeInternal(IDASIGNACIONNUMCHEQUE, value);
    }

    /**Gets the attribute value for IdBanco, using the alias name IdBanco
     */
    public Number getIdBanco() {
        return (Number)getAttributeInternal(IDBANCO);
    }

    /**Sets <code>value</code> as the attribute value for IdBanco
     */
    public void setIdBanco(Number value) {
        setAttributeInternal(IDBANCO, value);
    }


    /**Gets the attribute value for IdTipoproceso, using the alias name IdTipoproceso
     */
    public Number getIdTipoproceso() {
        return (Number)getAttributeInternal(IDTIPOPROCESO);
    }

    /**Sets <code>value</code> as the attribute value for IdTipoproceso
     */
    public void setIdTipoproceso(Number value) {
        setAttributeInternal(IDTIPOPROCESO, value);
    }


    /**Gets the attribute value for FechaCreacion, using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDASIGNACIONNUMCHEQUE:
            return getIdAsignacionNumCheque();
        case IDBANCO:
            return getIdBanco();
        case FECHACREACION:
            return getFechaCreacion();
        case IDPROCESO:
            return getIdProceso();
        case NOMBRE:
            return getNombre();
        case SISDETASIGCHEQUE:
            return getSisDetAsigCheque();
        case SISPROCESO:
            return getSisProceso();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDASIGNACIONNUMCHEQUE:
            setIdAsignacionNumCheque((DBSequence)value);
            return;
        case IDBANCO:
            setIdBanco((Number)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case IDPROCESO:
            setIdProceso((Number)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getSisDetAsigCheque() {
        return (RowIterator)getAttributeInternal(SISDETASIGCHEQUE);
    }


    /**Gets the attribute value for IdProceso, using the alias name IdProceso
     */
    public Number getIdProceso() {
        return (Number)getAttributeInternal(IDPROCESO);
    }

    /**Sets <code>value</code> as the attribute value for IdProceso
     */
    public void setIdProceso(Number value) {
        setAttributeInternal(IDPROCESO, value);
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
       DBSequence seq;
       RowIterator filas;
       SisDetAsigChequeImpl filaDetalle;
        if (operation==DML_INSERT){
            SequenceImpl sequence = new SequenceImpl("sis_num_cheque_Sq",e.getDBTransaction());
            seq=new DBSequence(sequence.getSequenceNumber());
            
            filas=this.getSisDetAsigCheque();
            
            while (filas.hasNext()){
              filaDetalle=(SisDetAsigChequeImpl)filas.next();  
              filaDetalle.setIdAsignacionNumCheque(sequence.getSequenceNumber());  
            }
            
            this.setIdAsignacionNumCheque(seq);
        }
        super.doDML(operation, e);
    }

    /**Gets the associated entity enlace_datos.entidades.gestiones.procesos.SisProcesoImpl
     */
    public SisProcesoImpl getSisProceso() {
        return (SisProcesoImpl)getAttributeInternal(SISPROCESO);
    }

    /**Sets <code>value</code> as the associated entity enlace_datos.entidades.gestiones.procesos.SisProcesoImpl
     */
    public void setSisProceso(SisProcesoImpl value) {
        setAttributeInternal(SISPROCESO, value);
    }

    /**Gets the attribute value for Nombre, using the alias name Nombre
     */
    public String getNombre() {
        return (String)getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(DBSequence idAsignacionNumCheque) {
        return new Key(new Object[]{idAsignacionNumCheque});
    }
}
