package enlace_datos.consultas.gestiones.plazas021;

import enlace_datos.entidades.gestiones.plazas021.sis_plazaImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class sis_plazaRowImpl extends ViewRowImpl {
    public static final int IDPARTIDA = 0;
    public static final int IDPUESTO = 1;
    public static final int NUMEROPLAZA = 2;
    public static final int CORRELATIVO = 3;
    public static final int CANTIDADHORAS = 4;
    public static final int SALARIOBASE = 5;
    public static final int FECHAINICIO = 6;
    public static final int FECHAFIN = 7;
    public static final int DISPONIBLE = 8;
    public static final int COMPLEMENTOSAL = 9;
    public static final int ESCALAFON = 10;
    public static final int FECHACREACION = 11;
    public static final int PERIODOPLAZA = 12;
    public static final int DICTAMEN = 13;
    public static final int NOMPLAZA = 14;
    public static final int CREADOPOR = 15;
    public static final int NOMBRE = 16;
    public static final int FORMATO2 = 17;
    public static final int ESCALAMIN = 18;
    public static final int PAGOUNICO = 19;
    public static final int IDPUESTOESCALA = 20;
    public static final int PLAZACVACACION = 21;
    public static final int PAGAMESVACA = 22;
    public static final int PLAZASICOIN = 23;
    public static final int IDPARTIDASICOIN = 24;
    public static final int IDRENGLON = 25;
    public static final int AMPLIACION = 26;

    /**This is the default constructor (do not remove)
     */
    public sis_plazaRowImpl() {
    }

    /**Gets sis_plaza entity object.
     */
    public sis_plazaImpl getsis_plaza() {
        return (sis_plazaImpl)getEntity(0);
    }

    /**Gets the attribute value for ID_PARTIDA using the alias name IdPartida
     */
    public Number getIdPartida() {
        return (Number) getAttributeInternal(IDPARTIDA);
    }

    /**Sets <code>value</code> as attribute value for ID_PARTIDA using the alias name IdPartida
     */
    public void setIdPartida(Number value) {
        setAttributeInternal(IDPARTIDA, value);
    }

    /**Gets the attribute value for ID_PUESTO using the alias name IdPuesto
     */
    public Number getIdPuesto() {
        return (Number) getAttributeInternal(IDPUESTO);
    }

    /**Sets <code>value</code> as attribute value for ID_PUESTO using the alias name IdPuesto
     */
    public void setIdPuesto(Number value) {
        setAttributeInternal(IDPUESTO, value);
    }

    /**Gets the attribute value for NUMERO_PLAZA using the alias name NumeroPlaza
     */
    public Number getNumeroPlaza() {
        return (Number) getAttributeInternal(NUMEROPLAZA);
    }

    /**Sets <code>value</code> as attribute value for NUMERO_PLAZA using the alias name NumeroPlaza
     */
    public void setNumeroPlaza(Number value) {
        setAttributeInternal(NUMEROPLAZA, value);
    }

    /**Gets the attribute value for CORRELATIVO using the alias name Correlativo
     */
    public Number getCorrelativo() {
        return (Number) getAttributeInternal(CORRELATIVO);
    }

    /**Sets <code>value</code> as attribute value for CORRELATIVO using the alias name Correlativo
     */
    public void setCorrelativo(Number value) {
        setAttributeInternal(CORRELATIVO, value);
    }

    /**Gets the attribute value for CANTIDAD_HORAS using the alias name CantidadHoras
     */
    public Number getCantidadHoras() {
        return (Number) getAttributeInternal(CANTIDADHORAS);
    }

    /**Sets <code>value</code> as attribute value for CANTIDAD_HORAS using the alias name CantidadHoras
     */
    public void setCantidadHoras(Number value) {
        setAttributeInternal(CANTIDADHORAS, value);
    }

    /**Gets the attribute value for SALARIO_BASE using the alias name SalarioBase
     */
    public Number getSalarioBase() {
        return (Number) getAttributeInternal(SALARIOBASE);
    }

    /**Sets <code>value</code> as attribute value for SALARIO_BASE using the alias name SalarioBase
     */
    public void setSalarioBase(Number value) {
        setAttributeInternal(SALARIOBASE, value);
    }

    /**Gets the attribute value for FECHA_INICIO using the alias name FechaInicio
     */
    public Date getFechaInicio() {
        return (Date) getAttributeInternal(FECHAINICIO);
    }

    /**Sets <code>value</code> as attribute value for FECHA_INICIO using the alias name FechaInicio
     */
    public void setFechaInicio(Date value) {
        setAttributeInternal(FECHAINICIO, value);
    }

    /**Gets the attribute value for FECHA_FIN using the alias name FechaFin
     */
    public Date getFechaFin() {
        return (Date) getAttributeInternal(FECHAFIN);
    }

    /**Sets <code>value</code> as attribute value for FECHA_FIN using the alias name FechaFin
     */
    public void setFechaFin(Date value) {
        setAttributeInternal(FECHAFIN, value);
    }

    /**Gets the attribute value for DISPONIBLE using the alias name Disponible
     */
    public String getDisponible() {
        return (String) getAttributeInternal(DISPONIBLE);
    }

    /**Sets <code>value</code> as attribute value for DISPONIBLE using the alias name Disponible
     */
    public void setDisponible(String value) {
        setAttributeInternal(DISPONIBLE, value);
    }

    /**Gets the attribute value for COMPLEMENTO_SAL using the alias name ComplementoSal
     */
    public Number getComplementoSal() {
        return (Number) getAttributeInternal(COMPLEMENTOSAL);
    }

    /**Sets <code>value</code> as attribute value for COMPLEMENTO_SAL using the alias name ComplementoSal
     */
    public void setComplementoSal(Number value) {
        setAttributeInternal(COMPLEMENTOSAL, value);
    }

    /**Gets the attribute value for ESCALAFON using the alias name Escalafon
     */
    public Number getEscalafon() {
        return (Number) getAttributeInternal(ESCALAFON);
    }

    /**Sets <code>value</code> as attribute value for ESCALAFON using the alias name Escalafon
     */
    public void setEscalafon(Number value) {
        setAttributeInternal(ESCALAFON, value);
    }

    /**Gets the attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for PERIODO_PLAZA using the alias name PeriodoPlaza
     */
    public String getPeriodoPlaza() {
        return (String) getAttributeInternal(PERIODOPLAZA);
    }

    /**Sets <code>value</code> as attribute value for PERIODO_PLAZA using the alias name PeriodoPlaza
     */
    public void setPeriodoPlaza(String value) {
        setAttributeInternal(PERIODOPLAZA, value);
    }

    /**Gets the attribute value for DICTAMEN using the alias name Dictamen
     */
    public String getDictamen() {
        return (String) getAttributeInternal(DICTAMEN);
    }

    /**Sets <code>value</code> as attribute value for DICTAMEN using the alias name Dictamen
     */
    public void setDictamen(String value) {
        setAttributeInternal(DICTAMEN, value);
    }

    /**Gets the attribute value for NOMPLAZA using the alias name Nomplaza
     */
    public String getNomplaza() {
        return (String) getAttributeInternal(NOMPLAZA);
    }

    /**Sets <code>value</code> as attribute value for NOMPLAZA using the alias name Nomplaza
     */
    public void setNomplaza(String value) {
        setAttributeInternal(NOMPLAZA, value);
    }

    /**Gets the attribute value for CREADO_POR using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String) getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as attribute value for CREADO_POR using the alias name CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the attribute value for the calculated attribute Nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Gets the attribute value for the calculated attribute formato2
     */
    public String getformato2() {
        return (String) getAttributeInternal(FORMATO2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute formato2
     */
    public void setformato2(String value) {
        setAttributeInternal(FORMATO2, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDPARTIDA:
            return getIdPartida();
        case IDPUESTO:
            return getIdPuesto();
        case NUMEROPLAZA:
            return getNumeroPlaza();
        case CORRELATIVO:
            return getCorrelativo();
        case CANTIDADHORAS:
            return getCantidadHoras();
        case SALARIOBASE:
            return getSalarioBase();
        case FECHAINICIO:
            return getFechaInicio();
        case FECHAFIN:
            return getFechaFin();
        case DISPONIBLE:
            return getDisponible();
        case COMPLEMENTOSAL:
            return getComplementoSal();
        case ESCALAFON:
            return getEscalafon();
        case FECHACREACION:
            return getFechaCreacion();
        case PERIODOPLAZA:
            return getPeriodoPlaza();
        case DICTAMEN:
            return getDictamen();
        case NOMPLAZA:
            return getNomplaza();
        case CREADOPOR:
            return getCreadoPor();
        case NOMBRE:
            return getNombre();
        case FORMATO2:
            return getFormato2();
        case ESCALAMIN:
            return getEscalamin();
        case PAGOUNICO:
            return getPagoUnico();
        case IDPUESTOESCALA:
            return getIdPuestoEscala();
        case PLAZACVACACION:
            return getPlazaCvacacion();
        case PAGAMESVACA:
            return getPagaMesVaca();
        case PLAZASICOIN:
            return getPlazaSicoin();
        case IDPARTIDASICOIN:
            return getIdPartidaSicoin();
        case IDRENGLON:
            return getIdRenglon();
        case AMPLIACION:
            return getampliacion();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDPARTIDA:
            setIdPartida((Number)value);
            return;
        case IDPUESTO:
            setIdPuesto((Number)value);
            return;
        case NUMEROPLAZA:
            setNumeroPlaza((Number)value);
            return;
        case CORRELATIVO:
            setCorrelativo((Number)value);
            return;
        case CANTIDADHORAS:
            setCantidadHoras((Number)value);
            return;
        case SALARIOBASE:
            setSalarioBase((Number)value);
            return;
        case FECHAINICIO:
            setFechaInicio((Date)value);
            return;
        case FECHAFIN:
            setFechaFin((Date)value);
            return;
        case DISPONIBLE:
            setDisponible((String)value);
            return;
        case COMPLEMENTOSAL:
            setComplementoSal((Number)value);
            return;
        case ESCALAFON:
            setEscalafon((Number)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case PERIODOPLAZA:
            setPeriodoPlaza((String)value);
            return;
        case DICTAMEN:
            setDictamen((String)value);
            return;
        case NOMPLAZA:
            setNomplaza((String)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        case FORMATO2:
            setFormato2((String)value);
            return;
        case ESCALAMIN:
            setEscalamin((Number)value);
            return;
        case PAGOUNICO:
            setPagoUnico((String)value);
            return;
        case IDPUESTOESCALA:
            setIdPuestoEscala((Number)value);
            return;
        case PLAZACVACACION:
            setPlazaCvacacion((Number)value);
            return;
        case PAGAMESVACA:
            setPagaMesVaca((Number)value);
            return;
        case PLAZASICOIN:
            setPlazaSicoin((Number)value);
            return;
        case IDPARTIDASICOIN:
            setIdPartidaSicoin((Number)value);
            return;
        case IDRENGLON:
            setIdRenglon((Number)value);
            return;
        case AMPLIACION:
            setampliacion((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Formato2
     */
    public String getFormato2() {
        return (String) getAttributeInternal(FORMATO2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Formato2
     */
    public void setFormato2(String value) {
        setAttributeInternal(FORMATO2, value);
    }


    /**Gets the attribute value for the calculated attribute Escalamin
     */
    public Number getEscalamin() {
        return (Number) getAttributeInternal(ESCALAMIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Escalamin
     */
    public void setEscalamin(Number value) {
        setAttributeInternal(ESCALAMIN, value);
    }


    /**Gets the attribute value for the calculated attribute ampliacion
     */
    public Number getampliacion() {
        return (Number) getAttributeInternal(AMPLIACION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ampliacion
     */
    public void setampliacion(Number value) {
        setAttributeInternal(AMPLIACION, value);
    }

    /**Gets the attribute value for PAGO_UNICO using the alias name PagoUnico
     */
    public String getPagoUnico() {
        return (String) getAttributeInternal(PAGOUNICO);
    }

    /**Sets <code>value</code> as attribute value for PAGO_UNICO using the alias name PagoUnico
     */
    public void setPagoUnico(String value) {
        setAttributeInternal(PAGOUNICO, value);
    }

    /**Gets the attribute value for ID_PUESTO_ESCALA using the alias name IdPuestoEscala
     */
    public Number getIdPuestoEscala() {
        return (Number) getAttributeInternal(IDPUESTOESCALA);
    }

    /**Sets <code>value</code> as attribute value for ID_PUESTO_ESCALA using the alias name IdPuestoEscala
     */
    public void setIdPuestoEscala(Number value) {
        setAttributeInternal(IDPUESTOESCALA, value);
    }

    /**Gets the attribute value for PLAZA_CVACACION using the alias name PlazaCvacacion
     */
    public Number getPlazaCvacacion() {
        return (Number) getAttributeInternal(PLAZACVACACION);
    }

    /**Sets <code>value</code> as attribute value for PLAZA_CVACACION using the alias name PlazaCvacacion
     */
    public void setPlazaCvacacion(Number value) {
        setAttributeInternal(PLAZACVACACION, value);
    }

    /**Gets the attribute value for PAGA_MES_VACA using the alias name PagaMesVaca
     */
    public Number getPagaMesVaca() {
        return (Number) getAttributeInternal(PAGAMESVACA);
    }

    /**Sets <code>value</code> as attribute value for PAGA_MES_VACA using the alias name PagaMesVaca
     */
    public void setPagaMesVaca(Number value) {
        setAttributeInternal(PAGAMESVACA, value);
    }

    /**Gets the attribute value for the calculated attribute PlazaSicoin
     */
    public Number getPlazaSicoin() {
        return (Number) getAttributeInternal(PLAZASICOIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PlazaSicoin
     */
    public void setPlazaSicoin(Number value) {
        setAttributeInternal(PLAZASICOIN, value);
    }

    /**Gets the attribute value for the calculated attribute IdPartidaSicoin
     */
    public Number getIdPartidaSicoin() {
        return (Number) getAttributeInternal(IDPARTIDASICOIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdPartidaSicoin
     */
    public void setIdPartidaSicoin(Number value) {
        setAttributeInternal(IDPARTIDASICOIN, value);
    }

    /**Gets the attribute value for the calculated attribute IdRenglon
     */
    public Number getIdRenglon() {
        return (Number) getAttributeInternal(IDRENGLON);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdRenglon
     */
    public void setIdRenglon(Number value) {
        setAttributeInternal(IDRENGLON, value);
    }
}
