package enlace_datos.consultas.reportes.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface Sis_pagosAnuladosVw extends ViewObject {
    void consulta_anulados(String pUsuario, Number pNumPago, Date vFechaI, 
                           Date vFechaF);
}
