package enlace_datos.consultas.gestiones.horas_extras;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class consul_partidaSICOIN_vwImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public consul_partidaSICOIN_vwImpl() {
    }

    /**Gets the bind variable value for pIdDependencia
     */
    public Number getpIdDependencia() {
        return (Number)getNamedWhereClauseParam("pIdDependencia");
    }

    /**Sets <code>value</code> for bind variable pIdDependencia
     */
    public void setpIdDependencia(Number value) {
        setNamedWhereClauseParam("pIdDependencia", value);
    }


    /**Gets the bind variable value for pAnio
     */
    public Number getpAnio() {
        return (Number)getNamedWhereClauseParam("pAnio");
    }

    /**Sets <code>value</code> for bind variable pAnio
     */
    public void setpAnio(Number value) {
        setNamedWhereClauseParam("pAnio", value);
    }

    /**Gets the bind variable value for pIdPartida
     */
    public Number getpIdPartida() {
        return (Number)getNamedWhereClauseParam("pIdPartida");
    }

    /**Sets <code>value</code> for bind variable pIdPartida
     */
    public void setpIdPartida(Number value) {
        setNamedWhereClauseParam("pIdPartida", value);
    }
}
