package enlace_datos.entidades.admin;

import enlace_datos.util.myEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisCategoriaPuestoImpl extends myEntityImpl {
    public static final int IDCATEGORIA = 0;
    public static final int IDNIVELPUESTO = 1;
    public static final int NOMBRE = 2;
    public static final int SISNIVELPUESTO = 3;
    public static final int SISPUESTO = 4;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisCategoriaPuestoImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.admin.SisCategoriaPuesto");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdCategoria, using the alias name IdCategoria
     */
    public Number getIdCategoria() {
        return (Number)getAttributeInternal(IDCATEGORIA);
    }

    /**Sets <code>value</code> as the attribute value for IdCategoria
     */
    public void setIdCategoria(Number value) {
        setAttributeInternal(IDCATEGORIA, value);
    }

    /**Gets the attribute value for IdNivelPuesto, using the alias name IdNivelPuesto
     */
    public Number getIdNivelPuesto() {
        return (Number)getAttributeInternal(IDNIVELPUESTO);
    }

    /**Sets <code>value</code> as the attribute value for IdNivelPuesto
     */
    public void setIdNivelPuesto(Number value) {
        setAttributeInternal(IDNIVELPUESTO, value);
    }

    /**Gets the attribute value for Nombre, using the alias name Nombre
     */
    public String getNombre() {
        return (String)getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDCATEGORIA:
            return getIdCategoria();
        case IDNIVELPUESTO:
            return getIdNivelPuesto();
        case NOMBRE:
            return getNombre();
        case SISPUESTO:
            return getSisPuesto();
        case SISNIVELPUESTO:
            return getSisNivelPuesto();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDCATEGORIA:
            setIdCategoria((Number)value);
            return;
        case IDNIVELPUESTO:
            setIdNivelPuesto((Number)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity SisNivelPuestoImpl
     */
    public SisNivelPuestoImpl getSisNivelPuesto() {
        return (SisNivelPuestoImpl)getAttributeInternal(SISNIVELPUESTO);
    }

    /**Sets <code>value</code> as the associated entity SisNivelPuestoImpl
     */
    public void setSisNivelPuesto(SisNivelPuestoImpl value) {
        setAttributeInternal(SISNIVELPUESTO, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getSisPuesto() {
        return (RowIterator)getAttributeInternal(SISPUESTO);
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
    
        registrarLogOperaciones(operation, e); 
        super.doDML(operation, e);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idCategoria) {
        return new Key(new Object[]{idCategoria});
    }
}
