package enlace_datos.consultas.procesos.common;

import java.util.Date;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface consul_aumentoSalarial_vw extends ViewObject {
    void aumentoPlan45(Number idAumento, Number idPartida, Number idanexo, 
                       Date fechaIni);
}
