package enlace_datos.consultas.procesos.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface SisProcesoPagoDetView extends ViewObject {
    void crearFila(Number pProcesoNomina, Number pIdTipoNomina, 
                   Number pIdPeriodo, Number pPorcentaje, String pNomPeriodo, 
                   String pTipoNomina, Number pAnio);
}
