CREATE TABLE SIS_CHEQUE_DESCARTADO
(
ID_CHEQUE_DESCARTADO NUMBER(10) NOT NULL,
ID_ACTA_FACSIMIL NUMBER(10),
ID_MOTIVO_CHEQUE_DESCARTADO NUMBER(3),
NUM_CHEQUE_INICIAL NUMBER(14, 0) NOT NULL,
NUM_CHEQUE_FINAL NUMBER(14, 0),
CREADO_POR VARCHAR2(20),
FECHA_CREACION DATE DEFAULT sysdate NOT NULL
)
;

CREATE TABLE SIS_MOTIVO_CHEQUE_DESCARTADO
(
ID_MOTIVO_CHEQUE_DESCARTADO NUMBER(3) NOT NULL,
NOMBRE_MOTIVO VARCHAR2(100)
)
;

ALTER TABLE SIS_CHEQUE_DESCARTADO
ADD CONSTRAINT SIS_CHEQUE_DESCARTADO_PK PRIMARY KEY
(
ID_CHEQUE_DESCARTADO
)
 ENABLE
;

ALTER TABLE SIS_MOTIVO_CHEQUE_DESCARTADO
ADD CONSTRAINT SIS_MOTIVO_CHEQUE_DESCART_PK PRIMARY KEY
(
ID_MOTIVO_CHEQUE_DESCARTADO
)
 ENABLE
;

ALTER TABLE SIS_CHEQUE_DESCARTADO
ADD CONSTRAINT SIS_CHEQUEDESCAR_ACTA_FK FOREIGN KEY
(
ID_ACTA_FACSIMIL
)
REFERENCES SIS_ACTA_FACSIMIL
(
ID_ACTA_FACSIMIL
) ENABLE
;

ALTER TABLE SIS_CHEQUE_DESCARTADO
ADD CONSTRAINT SIS_CHEQUEDESCAR_MOTIVO_FK FOREIGN KEY
(

)
REFERENCES SIS_MOTIVO_CHEQUE_DESCARTADO
(
ID_MOTIVO_CHEQUE_DESCARTADO
) ENABLE
;

