package enlace_datos.consultas.gestiones.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class SaldoAnualvwRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "Ejecutado_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "Debe_FMT_FORMAT", "" },
{ "Comprometido_FMT_FORMAT", "" },
{ "SaldoInicial_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "Ejecutado_FMT_FORMAT", "" },
{ "SaldoInicial_FMT_FORMAT", "" },
{ "Comprometido_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "Haber_FMT_FORMAT", "" },
{ "Haber_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "Debe_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" }};

    /**This is the default constructor (do not remove)
     */
    public SaldoAnualvwRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
