package enlace_datos.consultas.gestiones.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface Sis_Departamentos2_vw extends ViewObject {
    void DatosCenso();

    void resetQuerry();
}
