package enlace_datos.entidades.nomina;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisConciliacionAcreditImpl extends EntityImpl {
    public static final int IDCONCILIACIONACREDIT = 0;
    public static final int IDCARGAARCHIVODATOS = 1;
    public static final int IDDOCUMENTOBANCO = 2;
    public static final int NUMBOLETA = 3;
    public static final int MONTO = 4;
    public static final int FECHAAPLICACION = 5;
    public static final int OBSERV = 6;
    public static final int ESTADO = 7;
    public static final int FECHACREACION = 8;
    public static final int CREADOPOR = 9;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisConciliacionAcreditImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.nomina.SisConciliacionAcredit");
        }
        return mDefinitionObject;
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
    
        if (operation== DML_INSERT )
        {
            SequenceImpl sequence = new SequenceImpl("sis_conciliacion_acredit_sq",e.getDBTransaction());
            this.setIdConciliacionAcredit(sequence.getSequenceNumber());
        
        }
        
        super.doDML(operation, e);
    }

    /**Gets the attribute value for IdConciliacionAcredit, using the alias name IdConciliacionAcredit
     */
    public Number getIdConciliacionAcredit() {
        return (Number)getAttributeInternal(IDCONCILIACIONACREDIT);
    }

    /**Sets <code>value</code> as the attribute value for IdConciliacionAcredit
     */
    public void setIdConciliacionAcredit(Number value) {
        setAttributeInternal(IDCONCILIACIONACREDIT, value);
    }

    /**Gets the attribute value for IdCargaArchivoDatos, using the alias name IdCargaArchivoDatos
     */
    public Number getIdCargaArchivoDatos() {
        return (Number)getAttributeInternal(IDCARGAARCHIVODATOS);
    }

    /**Sets <code>value</code> as the attribute value for IdCargaArchivoDatos
     */
    public void setIdCargaArchivoDatos(Number value) {
        setAttributeInternal(IDCARGAARCHIVODATOS, value);
    }

    /**Gets the attribute value for IdDocumentoBanco, using the alias name IdDocumentoBanco
     */
    public Number getIdDocumentoBanco() {
        return (Number)getAttributeInternal(IDDOCUMENTOBANCO);
    }

    /**Sets <code>value</code> as the attribute value for IdDocumentoBanco
     */
    public void setIdDocumentoBanco(Number value) {
        setAttributeInternal(IDDOCUMENTOBANCO, value);
    }

    /**Gets the attribute value for NumBoleta, using the alias name NumBoleta
     */
    public Number getNumBoleta() {
        return (Number)getAttributeInternal(NUMBOLETA);
    }

    /**Sets <code>value</code> as the attribute value for NumBoleta
     */
    public void setNumBoleta(Number value) {
        setAttributeInternal(NUMBOLETA, value);
    }

    /**Gets the attribute value for Monto, using the alias name Monto
     */
    public Number getMonto() {
        return (Number)getAttributeInternal(MONTO);
    }

    /**Sets <code>value</code> as the attribute value for Monto
     */
    public void setMonto(Number value) {
        setAttributeInternal(MONTO, value);
    }

    /**Gets the attribute value for FechaAplicacion, using the alias name FechaAplicacion
     */
    public Date getFechaAplicacion() {
        return (Date)getAttributeInternal(FECHAAPLICACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaAplicacion
     */
    public void setFechaAplicacion(Date value) {
        setAttributeInternal(FECHAAPLICACION, value);
    }

    /**Gets the attribute value for Observ, using the alias name Observ
     */
    public String getObserv() {
        return (String)getAttributeInternal(OBSERV);
    }

    /**Sets <code>value</code> as the attribute value for Observ
     */
    public void setObserv(String value) {
        setAttributeInternal(OBSERV, value);
    }

    /**Gets the attribute value for Estado, using the alias name Estado
     */
    public Number getEstado() {
        return (Number)getAttributeInternal(ESTADO);
    }

    /**Sets <code>value</code> as the attribute value for Estado
     */
    public void setEstado(Number value) {
        setAttributeInternal(ESTADO, value);
    }

    /**Gets the attribute value for FechaCreacion, using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for CreadoPor, using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String)getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as the attribute value for CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDCONCILIACIONACREDIT:
            return getIdConciliacionAcredit();
        case IDCARGAARCHIVODATOS:
            return getIdCargaArchivoDatos();
        case IDDOCUMENTOBANCO:
            return getIdDocumentoBanco();
        case NUMBOLETA:
            return getNumBoleta();
        case MONTO:
            return getMonto();
        case FECHAAPLICACION:
            return getFechaAplicacion();
        case OBSERV:
            return getObserv();
        case ESTADO:
            return getEstado();
        case FECHACREACION:
            return getFechaCreacion();
        case CREADOPOR:
            return getCreadoPor();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDCONCILIACIONACREDIT:
            setIdConciliacionAcredit((Number)value);
            return;
        case IDCARGAARCHIVODATOS:
            setIdCargaArchivoDatos((Number)value);
            return;
        case IDDOCUMENTOBANCO:
            setIdDocumentoBanco((Number)value);
            return;
        case NUMBOLETA:
            setNumBoleta((Number)value);
            return;
        case MONTO:
            setMonto((Number)value);
            return;
        case FECHAAPLICACION:
            setFechaAplicacion((Date)value);
            return;
        case OBSERV:
            setObserv((String)value);
            return;
        case ESTADO:
            setEstado((Number)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idConciliacionAcredit) {
        return new Key(new Object[]{idConciliacionAcredit});
    }
}
