package enlace_datos.consultas.gestiones.procesos.client;

import enlace_datos.consultas.gestiones.procesos.common.SisProcesoSfltro;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisProcesoSfltroClient extends ViewUsageImpl implements SisProcesoSfltro {
    /**This is the default constructor (do not remove)
     */
    public SisProcesoSfltroClient() {
    }


    public void PorEstados(String pEstados) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"PorEstados",new String [] {"java.lang.String"},new Object[] {pEstados});
        return;
    }

    public void SoloAutorizados() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"SoloAutorizados",null,null);
        return;
    }

    public void Todos() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"Todos",null,null);
        return;
    }
}
