// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package webservices.ProxyBanrural.runtime;

import oracle.j2ee.ws.common.encoding.*;
import oracle.j2ee.ws.common.encoding.literal.*;
import oracle.j2ee.ws.common.encoding.literal.DetailFragmentDeserializer;
import oracle.j2ee.ws.common.encoding.simpletype.*;
import oracle.j2ee.ws.common.soap.SOAPEncodingConstants;
import oracle.j2ee.ws.common.soap.SOAPEnvelopeConstants;
import oracle.j2ee.ws.common.soap.SOAPVersion;
import oracle.j2ee.ws.common.streaming.*;
import oracle.j2ee.ws.common.wsdl.document.schema.SchemaConstants;
import oracle.j2ee.ws.common.util.xml.UUID;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.AttachmentPart;

public class ValidaCuentaBnrlResponseElement_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable {
    private static final QName ns1_result_QNAME = new QName("http://webservice/", "result");
    private static final QName ns1_result_TYPE_QNAME = new QName("http://webservice/", "result");
    private CombinedSerializer ns1_result_TYPE_QNAMEjavax$2e$xml$2e$soap$2e$SOAPElement_Serializer;
    
    public ValidaCuentaBnrlResponseElement_LiteralSerializer(QName type) {
        this(type,  false);
    }
    
    public ValidaCuentaBnrlResponseElement_LiteralSerializer(QName type, boolean encodeType) {
        super(type, true, encodeType);
        setSOAPVersion(SOAPVersion.SOAP_11);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_result_TYPE_QNAMEjavax$2e$xml$2e$soap$2e$SOAPElement_Serializer = (CombinedSerializer)registry.getSerializer("", javax.xml.soap.SOAPElement.class, ns1_result_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        webservices.ProxyBanrural.ValidaCuentaBnrlResponseElement instance = new webservices.ProxyBanrural.ValidaCuentaBnrlResponseElement();
        java.lang.Object member=null;
        QName elementName;
        List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        java.util.HashSet requiredElements = new java.util.HashSet();
        requiredElements.add("result");
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (matchQName(elementName, ns1_result_QNAME))) {
            context.setXmlFragmentWrapperName(  ns1_result_QNAME );
            ns1_result_TYPE_QNAMEjavax$2e$xml$2e$soap$2e$SOAPElement_Serializer.setNullable( true );
            member = ns1_result_TYPE_QNAMEjavax$2e$xml$2e$soap$2e$SOAPElement_Serializer.deserialize(ns1_result_QNAME, reader, context);
            requiredElements.remove("result");
            instance.setResult((javax.xml.soap.SOAPElement)member);
            context.setXmlFragmentWrapperName( null );
            reader.nextElementContent();
        }
        if (!requiredElements.isEmpty()) {
            throw new DeserializationException( "literal.expectedElementName" , requiredElements.iterator().next().toString(), DeserializationException.FAULT_CODE_CLIENT );
        }
        
        if( reader.getState() != XMLReader.END)
        {
            reader.skipElement();
        }
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        webservices.ProxyBanrural.ValidaCuentaBnrlResponseElement instance = (webservices.ProxyBanrural.ValidaCuentaBnrlResponseElement)obj;
        
    }
    public void doSerializeAnyAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        webservices.ProxyBanrural.ValidaCuentaBnrlResponseElement instance = (webservices.ProxyBanrural.ValidaCuentaBnrlResponseElement)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        webservices.ProxyBanrural.ValidaCuentaBnrlResponseElement instance = (webservices.ProxyBanrural.ValidaCuentaBnrlResponseElement)obj;
        
        context.setXmlFragmentWrapperName( ns1_result_QNAME );
        ns1_result_TYPE_QNAMEjavax$2e$xml$2e$soap$2e$SOAPElement_Serializer.setNullable( true );
        ns1_result_TYPE_QNAMEjavax$2e$xml$2e$soap$2e$SOAPElement_Serializer.serialize(instance.getResult(), ns1_result_QNAME, null, writer, context);
        context.setXmlFragmentWrapperName( null );
    }
}
