package enlace_datos.entidades.gestiones;

import enlace_datos.util.utils;
import enlace_datos.util.utils_DB;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisDetplazaCubreLicImpl extends EntityImpl {
    public static final int IDDETPLAZACUBRELIC = 0;
    public static final int IDDETLICENCIA = 1;
    public static final int IDCONTRATO = 2;
    public static final int IDPARTIDA = 3;
    public static final int IDPUESTO = 4;
    public static final int NUMEROPLAZA = 5;
    public static final int CORRELATIVO = 6;
    public static final int REGISTROEMPLEADO = 7;
    public static final int FECHACREACION = 8;
    public static final int CREADOPOR = 9;
    public static final int MODPOR = 10;
    public static final int FECHAMOD = 11;
    public static final int SISDETLICENCIA = 12;
    public static final int SISEMPLEADO = 13;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisDetplazaCubreLicImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.gestiones.SisDetplazaCubreLic");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdDetplazaCubreLic, using the alias name IdDetplazaCubreLic
     */
    public Number getIdDetplazaCubreLic() {
        return (Number)getAttributeInternal(IDDETPLAZACUBRELIC);
    }

    /**Sets <code>value</code> as the attribute value for IdDetplazaCubreLic
     */
    public void setIdDetplazaCubreLic(Number value) {
        setAttributeInternal(IDDETPLAZACUBRELIC, value);
    }

    /**Gets the attribute value for IdDetLicencia, using the alias name IdDetLicencia
     */
    public Number getIdDetLicencia() {
        return (Number)getAttributeInternal(IDDETLICENCIA);
    }

    /**Sets <code>value</code> as the attribute value for IdDetLicencia
     */
    public void setIdDetLicencia(Number value) {
        setAttributeInternal(IDDETLICENCIA, value);
    }

    /**Gets the attribute value for IdContrato, using the alias name IdContrato
     */
    public Number getIdContrato() {
        return (Number)getAttributeInternal(IDCONTRATO);
    }

    /**Sets <code>value</code> as the attribute value for IdContrato
     */
    public void setIdContrato(Number value) {
        setAttributeInternal(IDCONTRATO, value);
    }

    /**Gets the attribute value for IdPartida, using the alias name IdPartida
     */
    public Number getIdPartida() {
        return (Number)getAttributeInternal(IDPARTIDA);
    }

    /**Sets <code>value</code> as the attribute value for IdPartida
     */
    public void setIdPartida(Number value) {
        setAttributeInternal(IDPARTIDA, value);
    }

    /**Gets the attribute value for IdPuesto, using the alias name IdPuesto
     */
    public Number getIdPuesto() {
        return (Number)getAttributeInternal(IDPUESTO);
    }

    /**Sets <code>value</code> as the attribute value for IdPuesto
     */
    public void setIdPuesto(Number value) {
        setAttributeInternal(IDPUESTO, value);
    }

    /**Gets the attribute value for NumeroPlaza, using the alias name NumeroPlaza
     */
    public Number getNumeroPlaza() {
        return (Number)getAttributeInternal(NUMEROPLAZA);
    }

    /**Sets <code>value</code> as the attribute value for NumeroPlaza
     */
    public void setNumeroPlaza(Number value) {
        setAttributeInternal(NUMEROPLAZA, value);
    }

    /**Gets the attribute value for Correlativo, using the alias name Correlativo
     */
    public Number getCorrelativo() {
        return (Number)getAttributeInternal(CORRELATIVO);
    }

    /**Sets <code>value</code> as the attribute value for Correlativo
     */
    public void setCorrelativo(Number value) {
        setAttributeInternal(CORRELATIVO, value);
    }

    /**Gets the attribute value for RegistroEmpleado, using the alias name RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number)getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as the attribute value for RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for FechaCreacion, using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for CreadoPor, using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String)getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as the attribute value for CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the attribute value for ModPor, using the alias name ModPor
     */
    public String getModPor() {
        return (String)getAttributeInternal(MODPOR);
    }

    /**Sets <code>value</code> as the attribute value for ModPor
     */
    public void setModPor(String value) {
        setAttributeInternal(MODPOR, value);
    }

    /**Gets the attribute value for FechaMod, using the alias name FechaMod
     */
    public Date getFechaMod() {
        return (Date)getAttributeInternal(FECHAMOD);
    }

    /**Sets <code>value</code> as the attribute value for FechaMod
     */
    public void setFechaMod(Date value) {
        setAttributeInternal(FECHAMOD, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDDETPLAZACUBRELIC:
            return getIdDetplazaCubreLic();
        case IDDETLICENCIA:
            return getIdDetLicencia();
        case IDCONTRATO:
            return getIdContrato();
        case IDPARTIDA:
            return getIdPartida();
        case IDPUESTO:
            return getIdPuesto();
        case NUMEROPLAZA:
            return getNumeroPlaza();
        case CORRELATIVO:
            return getCorrelativo();
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case FECHACREACION:
            return getFechaCreacion();
        case CREADOPOR:
            return getCreadoPor();
        case MODPOR:
            return getModPor();
        case FECHAMOD:
            return getFechaMod();
        case SISDETLICENCIA:
            return getSisDetLicencia();
        case SISEMPLEADO:
            return getSisEmpleado();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDDETPLAZACUBRELIC:
            setIdDetplazaCubreLic((Number)value);
            return;
        case IDDETLICENCIA:
            setIdDetLicencia((Number)value);
            return;
        case IDCONTRATO:
            setIdContrato((Number)value);
            return;
        case IDPARTIDA:
            setIdPartida((Number)value);
            return;
        case IDPUESTO:
            setIdPuesto((Number)value);
            return;
        case NUMEROPLAZA:
            setNumeroPlaza((Number)value);
            return;
        case CORRELATIVO:
            setCorrelativo((Number)value);
            return;
        case REGISTROEMPLEADO:
            setRegistroEmpleado((Number)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case MODPOR:
            setModPor((String)value);
            return;
        case FECHAMOD:
            setFechaMod((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity SisDetLicenciaImpl
     */
    public SisDetLicenciaImpl getSisDetLicencia() {
        return (SisDetLicenciaImpl)getAttributeInternal(SISDETLICENCIA);
    }

    /**Sets <code>value</code> as the associated entity SisDetLicenciaImpl
     */
    public void setSisDetLicencia(SisDetLicenciaImpl value) {
        setAttributeInternal(SISDETLICENCIA, value);
    }

    /**Gets the associated entity SisEmpleadoImpl
     */
    public SisEmpleadoImpl getSisEmpleado() {
        return (SisEmpleadoImpl)getAttributeInternal(SISEMPLEADO);
    }

    /**Sets <code>value</code> as the associated entity SisEmpleadoImpl
     */
    public void setSisEmpleado(SisEmpleadoImpl value) {
        setAttributeInternal(SISEMPLEADO, value);
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {    
    
       if (operation==DML_INSERT){
           
           if (this.getCreadoPor()==null){
               
               this.setCreadoPor(utils.getAuthUser(this.getDBTransaction()));
           }
       }
    
        super.doDML(operation, e);
    }

    /**Add attribute defaulting logic in this method.
     */
    protected void create(AttributeList attributeList) {           
        Object vValorSec;
        super.create(attributeList);
        if (this.getIdDetplazaCubreLic()==null){
          try{
          
            vValorSec=utils_DB.getValorSequencia(this.getDBTransaction(),"sis_detplaza_cubre_lic_sq");
            this.setIdDetplazaCubreLic(utils.getNumberOracle(vValorSec));
            
          }catch(Exception exep)
          {
              
          }
                        
        }
        
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idDetplazaCubreLic) {
        return new Key(new Object[]{idDetplazaCubreLic});
    }
}
