package enlace_datos.entidades.gestiones;

import enlace_datos.util.utils;

import enlace_datos.util.utils_DB;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisPromReclafImpl extends EntityImpl {
    public static final int IDPROMORECLAF = 0;
    public static final int IDSOLICITUD = 1;
    public static final int NUMDOCPROMO = 2;
    public static final int IDPUESTODE = 3;
    public static final int IDPUESTOA = 4;
    public static final int APARTIRDE = 5;
    public static final int HASTA = 6;
    public static final int OBSERVACIONES = 7;
    public static final int CREADOPOR = 8;
    public static final int FECHACREACION = 9;
    public static final int MODPOR = 10;
    public static final int FECHAMOD = 11;
    public static final int SISSOLICITUD = 12;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisPromReclafImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.gestiones.SisPromReclaf");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdPromoReclaf, using the alias name IdPromoReclaf
     */
    public Number getIdPromoReclaf() {
        return (Number)getAttributeInternal(IDPROMORECLAF);
    }

    /**Sets <code>value</code> as the attribute value for IdPromoReclaf
     */
    public void setIdPromoReclaf(Number value) {
        setAttributeInternal(IDPROMORECLAF, value);
    }

    /**Gets the attribute value for IdSolicitud, using the alias name IdSolicitud
     */
    public Number getIdSolicitud() {
        return (Number)getAttributeInternal(IDSOLICITUD);
    }

    /**Sets <code>value</code> as the attribute value for IdSolicitud
     */
    public void setIdSolicitud(Number value) {
        setAttributeInternal(IDSOLICITUD, value);
    }

    /**Gets the attribute value for NumDocPromo, using the alias name NumDocPromo
     */
    public String getNumDocPromo() {
        return (String)getAttributeInternal(NUMDOCPROMO);
    }

    /**Sets <code>value</code> as the attribute value for NumDocPromo
     */
    public void setNumDocPromo(String value) {
        setAttributeInternal(NUMDOCPROMO, value);
    }

    /**Gets the attribute value for IdPuestoDe, using the alias name IdPuestoDe
     */
    public Number getIdPuestoDe() {
        return (Number)getAttributeInternal(IDPUESTODE);
    }

    /**Sets <code>value</code> as the attribute value for IdPuestoDe
     */
    public void setIdPuestoDe(Number value) {
        setAttributeInternal(IDPUESTODE, value);
    }

    /**Gets the attribute value for IdPuestoA, using the alias name IdPuestoA
     */
    public Number getIdPuestoA() {
        return (Number)getAttributeInternal(IDPUESTOA);
    }

    /**Sets <code>value</code> as the attribute value for IdPuestoA
     */
    public void setIdPuestoA(Number value) {
        setAttributeInternal(IDPUESTOA, value);
    }

    /**Gets the attribute value for APartirDe, using the alias name APartirDe
     */
    public Date getAPartirDe() {
        return (Date)getAttributeInternal(APARTIRDE);
    }

    /**Sets <code>value</code> as the attribute value for APartirDe
     */
    public void setAPartirDe(Date value) {
        setAttributeInternal(APARTIRDE, value);
    }

    /**Gets the attribute value for Hasta, using the alias name Hasta
     */
    public Date getHasta() {
        return (Date)getAttributeInternal(HASTA);
    }

    /**Sets <code>value</code> as the attribute value for Hasta
     */
    public void setHasta(Date value) {
        setAttributeInternal(HASTA, value);
    }

    /**Gets the attribute value for Observaciones, using the alias name Observaciones
     */
    public String getObservaciones() {
        return (String)getAttributeInternal(OBSERVACIONES);
    }

    /**Sets <code>value</code> as the attribute value for Observaciones
     */
    public void setObservaciones(String value) {
        setAttributeInternal(OBSERVACIONES, value);
    }

    /**Gets the attribute value for CreadoPor, using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String)getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as the attribute value for CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the attribute value for FechaCreacion, using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for ModPor, using the alias name ModPor
     */
    public String getModPor() {
        return (String)getAttributeInternal(MODPOR);
    }

    /**Sets <code>value</code> as the attribute value for ModPor
     */
    public void setModPor(String value) {
        setAttributeInternal(MODPOR, value);
    }

    /**Gets the attribute value for FechaMod, using the alias name FechaMod
     */
    public Date getFechaMod() {
        return (Date)getAttributeInternal(FECHAMOD);
    }

    /**Sets <code>value</code> as the attribute value for FechaMod
     */
    public void setFechaMod(Date value) {
        setAttributeInternal(FECHAMOD, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDPROMORECLAF:
            return getIdPromoReclaf();
        case IDSOLICITUD:
            return getIdSolicitud();
        case NUMDOCPROMO:
            return getNumDocPromo();
        case IDPUESTODE:
            return getIdPuestoDe();
        case IDPUESTOA:
            return getIdPuestoA();
        case APARTIRDE:
            return getAPartirDe();
        case HASTA:
            return getHasta();
        case OBSERVACIONES:
            return getObservaciones();
        case CREADOPOR:
            return getCreadoPor();
        case FECHACREACION:
            return getFechaCreacion();
        case MODPOR:
            return getModPor();
        case FECHAMOD:
            return getFechaMod();
        case SISSOLICITUD:
            return getSisSolicitud();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDPROMORECLAF:
            setIdPromoReclaf((Number)value);
            return;
        case IDSOLICITUD:
            setIdSolicitud((Number)value);
            return;
        case NUMDOCPROMO:
            setNumDocPromo((String)value);
            return;
        case IDPUESTODE:
            setIdPuestoDe((Number)value);
            return;
        case IDPUESTOA:
            setIdPuestoA((Number)value);
            return;
        case APARTIRDE:
            setAPartirDe((Date)value);
            return;
        case HASTA:
            setHasta((Date)value);
            return;
        case OBSERVACIONES:
            setObservaciones((String)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case MODPOR:
            setModPor((String)value);
            return;
        case FECHAMOD:
            setFechaMod((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity SisSolicitudImpl
     */
    public SisSolicitudImpl getSisSolicitud() {
        return (SisSolicitudImpl)getAttributeInternal(SISSOLICITUD);
    }

    /**Sets <code>value</code> as the associated entity SisSolicitudImpl
     */
    public void setSisSolicitud(SisSolicitudImpl value) {
        setAttributeInternal(SISSOLICITUD, value);
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==this.DML_INSERT) {
            Number vIdPromoReclaf;
            vIdPromoReclaf = utils.getNumberOracle(utils_DB.getEjecutarQuerry(this.getDBTransaction(),"select sis_prom_reclaf_sq.nextval from dual"));
            this.setIdPromoReclaf(vIdPromoReclaf);
        }
        
        super.doDML(operation, e);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idPromoReclaf) {
        return new Key(new Object[]{idPromoReclaf});
    }
}
