package enlace_datos.entidades.gestiones;

import enlace_datos.util.utils;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisReintegroImpl extends EntityImpl {
    public static final int IDREINTEGRO = 0;
    public static final int IDDOCUMENTOBANCO = 1;
    public static final int TOTALPAGAR = 2;
    public static final int OBSERVACIONES = 3;
    public static final int CREADOPOR = 4;
    public static final int FECHACREACION = 5;
    public static final int MODPOR = 6;
    public static final int FECHAMOD = 7;
    public static final int IDESTADO = 8;
    public static final int SISDETALLEREINTEGRO = 9;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisReintegroImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.gestiones.SisReintegro");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdReintegro, using the alias name IdReintegro
     */
    public Number getIdReintegro() {
        return (Number)getAttributeInternal(IDREINTEGRO);
    }

    /**Sets <code>value</code> as the attribute value for IdReintegro
     */
    public void setIdReintegro(Number value) {
        setAttributeInternal(IDREINTEGRO, value);
    }

    /**Gets the attribute value for IdDocumentoBanco, using the alias name IdDocumentoBanco
     */
    public Number getIdDocumentoBanco() {
        return (Number)getAttributeInternal(IDDOCUMENTOBANCO);
    }

    /**Sets <code>value</code> as the attribute value for IdDocumentoBanco
     */
    public void setIdDocumentoBanco(Number value) {
        setAttributeInternal(IDDOCUMENTOBANCO, value);
    }

    /**Gets the attribute value for TotalPagar, using the alias name TotalPagar
     */
    public Number getTotalPagar() {
        return (Number)getAttributeInternal(TOTALPAGAR);
    }

    /**Sets <code>value</code> as the attribute value for TotalPagar
     */
    public void setTotalPagar(Number value) {
        setAttributeInternal(TOTALPAGAR, value);
    }

    /**Gets the attribute value for Observaciones, using the alias name Observaciones
     */
    public String getObservaciones() {
        return (String)getAttributeInternal(OBSERVACIONES);
    }

    /**Sets <code>value</code> as the attribute value for Observaciones
     */
    public void setObservaciones(String value) {
        setAttributeInternal(OBSERVACIONES, value);
    }

    /**Gets the attribute value for CreadoPor, using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String)getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as the attribute value for CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the attribute value for FechaCreacion, using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for ModPor, using the alias name ModPor
     */
    public String getModPor() {
        return (String)getAttributeInternal(MODPOR);
    }

    /**Sets <code>value</code> as the attribute value for ModPor
     */
    public void setModPor(String value) {
        setAttributeInternal(MODPOR, value);
    }

    /**Gets the attribute value for FechaMod, using the alias name FechaMod
     */
    public Date getFechaMod() {
        return (Date)getAttributeInternal(FECHAMOD);
    }

    /**Sets <code>value</code> as the attribute value for FechaMod
     */
    public void setFechaMod(Date value) {
        setAttributeInternal(FECHAMOD, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDREINTEGRO:
            return getIdReintegro();
        case IDDOCUMENTOBANCO:
            return getIdDocumentoBanco();
        case TOTALPAGAR:
            return getTotalPagar();
        case OBSERVACIONES:
            return getObservaciones();
        case CREADOPOR:
            return getCreadoPor();
        case FECHACREACION:
            return getFechaCreacion();
        case MODPOR:
            return getModPor();
        case FECHAMOD:
            return getFechaMod();
        case IDESTADO:
            return getIdEstado();
        case SISDETALLEREINTEGRO:
            return getSisDetalleReintegro();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDREINTEGRO:
            setIdReintegro((Number)value);
            return;
        case IDDOCUMENTOBANCO:
            setIdDocumentoBanco((Number)value);
            return;
        case TOTALPAGAR:
            setTotalPagar((Number)value);
            return;
        case OBSERVACIONES:
            setObservaciones((String)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case MODPOR:
            setModPor((String)value);
            return;
        case FECHAMOD:
            setFechaMod((Date)value);
            return;
        case IDESTADO:
            setIdEstado((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getSisDetalleReintegro() {
        return (RowIterator)getAttributeInternal(SISDETALLEREINTEGRO);
    }

    /**Gets the attribute value for IdEstado, using the alias name IdEstado
     */
    public Number getIdEstado() {
        return (Number)getAttributeInternal(IDESTADO);
    }

    /**Sets <code>value</code> as the attribute value for IdEstado
     */
    public void setIdEstado(Number value) {
        setAttributeInternal(IDESTADO, value);
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        
        if (operation==this.DML_UPDATE){
            this.setModPor(utils.getAuthUser(this.getDBTransaction()));
            this.setFechaMod(utils.getFechaActual());
        }
        super.doDML(operation, e);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idReintegro) {
        return new Key(new Object[]{idReintegro});
    }
}
