package enlace_datos.consultas.empleado.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class Sis_list_detPagoDesc_vwRowImplMsgBundle extends JboResourceBundle {

    static final Object[][] sMessageStrings = 
    {
{ "ValorAplicado_FMT_FORMAT", "#,###.00" },
{ "TotalAplicado_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "ValorAplicado_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "TotalAplicado_FMT_FORMAT", "#,###.00" }};

    /**This is the default constructor (do not remove)
     */
    public Sis_list_detPagoDesc_vwRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
