CREATE TABLE SIS_DEPARTAMENTO
(
ID_DEPARTAMENTO NUMBER(6, 0) NOT NULL,
NOMBRE VARCHAR2(200) NOT NULL,
REGISTRO VARCHAR2(4) NOT NULL
)
;

CREATE TABLE SIS_MUNICIPIO
(
ID_MUNICIPIO NUMBER(6, 0) NOT NULL,
ID_DEPARTAMENTO NUMBER(6, 0) NOT NULL,
NOMBRE VARCHAR2(150) NOT NULL
)
;

CREATE TABLE SIS_DEPENDENCIA
(
ID_DEPENDENCIA NUMBER(7, 0) NOT NULL,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(250)
)
;

CREATE TABLE SIS_UNIDAD_EJECUTORA
(
ID_UNIDAD NUMBER(7, 0) NOT NULL,
ID_DEPENDENCIA NUMBER(7, 0),
NOMBRE VARCHAR2(150)
)
;

CREATE TABLE SIS_BANCO
(
ID_BANCO NUMBER(3, 0) NOT NULL,
NOMBRE VARCHAR2(150)
)
;

CREATE TABLE SIS_CUENTA
(
ID_CUENTA NUMBER(10, 0) NOT NULL,
ID_BANCO NUMBER(6, 0) NOT NULL,
NUMERO VARCHAR2(50),
REGISTRO_EMPLEADO NUMBER(10, 0),
FECHA_BAJA DATE
)
;

CREATE TABLE SIS_AJUSTE
(
ID_AJUSTE NUMBER(6, 0) NOT NULL,
ID_TIPOAJUSTE NUMBER(3, 0),
VARIANTE NUMBER,
PRIORIDAD VARCHAR2(25),
NOMBRE VARCHAR2(100),
COD_NOMINA NUMBER,
DESCRIPCION VARCHAR2(200),
OPCIONAL VARCHAR2(2),
REMOVIBLE VARCHAR2(2)
)
;

CREATE TABLE SIS_TIPO_AJUSTE
(
ID_TIPOAJUSTE NUMBER(3, 0) NOT NULL,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(200),
OPERACION VARCHAR2(3)
)
;

CREATE TABLE SIS_REGLA
(
ID_REGLA NUMBER(6, 0) NOT NULL,
ID_AJUSTE NUMBER(6, 0),
VALOR_INICIAL NUMBER(12, 2),
VALOR_FINAL NUMBER(12, 2),
VALOR NUMBER(10, 2),
PORCENTAJE NUMBER(10, 0),
EXPRESION VARCHAR2(25),
FRECUENCIA VARCHAR2(15),
FECHA_INICIO DATE,
FECHA_FIN DATE,
LITERAL VARCHAR2(15)
)
;

CREATE TABLE SIS_PUESTO
(
ID_PUESTO NUMBER(7, 0) NOT NULL,
NOMBRE VARCHAR2(200),
CLASIFICACION NUMBER,
ESCALAMIN NUMBER(12, 2),
ESCALAMAX NUMBER(12, 2)
)
;

CREATE TABLE SIS_PARTIDA
(
ID_PARTIDA NUMBER NOT NULL,
ID_UNIDAD NUMBER,
DESCRIPCION VARCHAR2(200)
)
;

CREATE TABLE SIS_PLAZA
(
ID_PARTIDA NUMBER NOT NULL,
ID_PUESTO NUMBER NOT NULL,
CORRELATIVO VARCHAR2(4000) NOT NULL,
NUMERO_PLAZA NUMBER(10, 0) NOT NULL,
CANTIDAD_HORAS NUMBER(2, 0),
FECHA_INICIO DATE,
FECHA_FIN DATE
)
;

CREATE TABLE SIS_TIPO_DOCUMENTO
(
ID_TIPO_DOCUMENTO NUMBER(3, 0) NOT NULL,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(200)
)
;

CREATE TABLE SIS_DOCUMENTO_BANCO
(
ID_DOCUMENTO_BANCO NUMBER(12, 0) NOT NULL,
ID_BANCO NUMBER(3, 0),
ID_CUENTA NUMBER,
ID_TIPO_DOCUMENTO NUMBER(3, 0),
ID_MONEDA NUMBER,
ID_ESTADO NUMBER(3, 0),
DOC_REEMPLAZA NUMBER(12, 0),
NUM_DOC_FISICO VARCHAR2(150),
VALOR NUMBER(12, 2),
DESCRIPCION VARCHAR2(200),
FECHA_EMISION DATE,
FECHA_ANULACION DATE
)
;

CREATE TABLE SIS_EMPLEADO
(
REGISTRO_EMPLEADO NUMBER(10, 0) NOT NULL,
ID_NIVEL NUMBER(6, 0),
ID_ESTADO NUMBER(3, 0) NOT NULL,
APELLIDO1 VARCHAR2(50) NOT NULL,
APELLIDO2 VARCHAR2(50),
APELLIDOCASADA VARCHAR2(50),
NOMBRE1 VARCHAR2(50) NOT NULL,
NOMBRE2 VARCHAR2(50),
NOMBRE3 VARCHAR2(50),
ESTADOCIVIL VARCHAR2(2) NOT NULL,
GENERO VARCHAR2(2) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
ORDEN_CEDULA VARCHAR2(3) NOT NULL,
REGISTRO_CEDULA NUMBER(10) NOT NULL,
MUNICIPIO_CEDULA NUMBER(6, 0) NOT NULL,
NIT VARCHAR2(20),
IGSS VARCHAR2(20),
TEL_CASA VARCHAR2(10),
CELULAR VARCHAR2(10),
FAX VARCHAR2(10),
EMAIL VARCHAR2(150),
TITULO VARCHAR2(100),
COLEGIADO VARCHAR2(50)
)
;

CREATE TABLE SIS_NIVEL_ACADEMICO
(
ID_NIVEL NUMBER(6, 0) NOT NULL,
DESCRIPCION VARCHAR2(200)
)
;

CREATE TABLE SIS_PROCESO
(
ID_PROCESO NUMBER(10, 0) NOT NULL,
PROCESO_PADRE NUMBER,
TIPOPROCESO NUMBER(3, 0),
FECHA_INICIO DATE,
FECHA_FIN DATE,
ANIO NUMBER(4, 0),
PERIODO NUMBER(2, 0)
)
;

CREATE TABLE SIS_TIPO_PROCESO
(
ID_TIPOPROCESO NUMBER(3, 0) NOT NULL,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(250)
)
;

CREATE TABLE SIS_CONTRATO
(
ID_CONTRATO NUMBER(10, 0) NOT NULL,
ID_TIPO_CONTRATO NUMBER(2, 0),
ID_FORMA_OBT_PUESTO NUMBER(10, 0),
ID_PARTIDA NUMBER,
ID_PUESTO NUMBER,
CORRELATIVO VARCHAR2(4000),
REGISTRO_EMPLEADO NUMBER(10, 0) NOT NULL,
SUELDOBASE NUMBER(12, 2),
ATRIBUCION VARCHAR2(1000),
HORASCONTRATADAS NUMBER(2, 0),
LUGAR_POSESION NUMBER(10, 0),
FECHA_POSESION DATE,
INSTALACION_POSESION VARCHAR2(250),
FECHA_CREACION DATE,
ESTATUS VARCHAR2(15) NOT NULL
)
;

CREATE TABLE SIS_DET_CALCULO_AJUSTE
(
ID_AJUSTE NUMBER(10, 0) NOT NULL,
ID_PROCESO NUMBER(10, 0) NOT NULL,
ID_CONTRATO NUMBER(10, 0) NOT NULL,
ID_CORRELATIVO NUMBER,
VALOR_APLICADO NUMBER(12, 2),
REMANENTE NUMBER,
APLICADO VARCHAR2(2)
)
;

CREATE TABLE SIS_AJUSTE_CONTRATO
(
ID_CONTRATO NUMBER(10, 0) NOT NULL,
ID_AJUSTE NUMBER(10, 0) NOT NULL,
ID_CORRELATIVO NUMBER NOT NULL,
ID_PROCESO NUMBER,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE,
VALOR NUMBER(16, 2)
)
;

CREATE TABLE SIS_AJUSTE_EMPLEADO
(
REGISTRO_EMPLEADO NUMBER(10, 0) NOT NULL,
ID_AJUSTE NUMBER(10, 0) NOT NULL,
ID_CORRELATIVO NUMBER NOT NULL,
ID_PROCESO NUMBER,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE,
VALOR NUMBER(16, 2)
)
;

CREATE TABLE SIS_TIPO_SOLICITUD
(
ID_TIPO_SOLICITUD NUMBER(10, 0) NOT NULL,
DESCRIPCION VARCHAR2(200)
)
;

CREATE TABLE SIS_SOLICITUD
(
ID_SOLICITUD NUMBER(10, 0) NOT NULL,
ID_TIPO_SOLICITUD NUMBER(10, 0),
ID_CONTRATO NUMBER,
REGISTRO_EMPLEADO NUMBER,
DOCUMENTO VARCHAR2(50),
OBSERVACION VARCHAR2(200),
LUGAR NUMBER,
FECHA_CREACION DATE
)
;

CREATE TABLE SIS_CONVENIO
(
ID_CONVENIO NUMBER(10, 0) NOT NULL,
ID_SOLICITUD NUMBER(10, 0) NOT NULL,
FECHAINICIO DATE,
FECHAFIN DATE,
MONTO NUMBER(16, 2),
DOCUMENTO VARCHAR2(25)
)
;

CREATE TABLE SIS_BENEFICIARIO
(
ID_BENEFICIARIO NUMBER(10, 0) NOT NULL,
ID_SOLICITUD NUMBER(10, 0) NOT NULL,
NOMBRE VARCHAR2(200),
PARENTESCO VARCHAR2(50),
MONTO NUMBER(16, 2)
)
;

CREATE TABLE SIS_HISTORICO_EST_SOLICITUD
(
ID_ESTADO NUMBER(10, 0) NOT NULL,
ID_SOLICITUD NUMBER(10, 0) NOT NULL,
ID_USUARIO NUMBER(10, 0) NOT NULL,
FECHA DATE,
OBSERVACION VARCHAR2(200)
)
;

CREATE TABLE SIS_MENSAJE
(
ID_MENSAJE NUMBER(10, 0) NOT NULL,
ID_SOLICITUD NUMBER(10, 0) NOT NULL,
ID_USUARIO NUMBER(10, 0),
OBSERVACION VARCHAR2(200),
VISTO VARCHAR2(100),
FECHA DATE,
HORA VARCHAR2(10)
)
;

CREATE TABLE SIS_USUARIO
(
ID_USUARIO NUMBER(6, 0) NOT NULL,
ID_ESTADO NUMBER(3, 0),
CLAVE VARCHAR2(50),
TIPO VARCHAR2(20),
REGISTRO VARCHAR2(20),
DEPENDENCIA VARCHAR2(20)
)
;

CREATE TABLE SIS_PERFIL
(
ID_PERFIL NUMBER(6, 0) NOT NULL,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(200)
)
;

CREATE TABLE SIS_OPCION_MENU
(
ID_OPCION_MENU NUMBER(6, 0) NOT NULL,
ID_PADRE NUMBER(6, 0),
ORDEN NUMBER(3),
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(350),
OUTCOME VARCHAR2(100),
PAGINA VARCHAR2(300)
)
;

CREATE TABLE SIS_PERMISO
(
ID_OPCION_MENU NUMBER(6, 0) NOT NULL,
ID_PERFIL NUMBER(6, 0) NOT NULL,
GUARDAR NUMBER(1, 0),
ACTUALIZAR NUMBER(1, 0),
BORRAR NUMBER(1, 0),
IMPRIMIR NUMBER(1, 0)
)
;

CREATE TABLE SIS_TIPO_CONTRATO
(
ID_TIPO_CONTRATO NUMBER(3, 0) NOT NULL,
NOMBRE VARCHAR2(25)
)
;

CREATE TABLE SIS_FORMA_OBT_PUESTO
(
ID_FORMA_OBT_PUESTO NUMBER(3, 0) NOT NULL,
NOMBRE VARCHAR2(50)
)
;

CREATE TABLE SIS_AJUSTEXPROCESO
(
ID_TIPOPROCESO NUMBER(10, 0) NOT NULL,
ID_AJUSTE NUMBER(10, 0) NOT NULL,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE
)
;

CREATE TABLE SIS_FORMA_PAGO
(
ID_TIPO_DOCUMENTO NUMBER(10, 0) NOT NULL,
ID_CONTRATO NUMBER(10, 0) NOT NULL,
ID_MONEDA NUMBER,
ID_CUENTA NUMBER(10, 0),
ID_BANCO NUMBER,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE
)
;

CREATE TABLE SIS_HISTORICO_EST_CONTRATO
(
ID_CONTRATO NUMBER(10, 0) NOT NULL,
ID_ESTADO NUMBER NOT NULL,
FECHA DATE NOT NULL
)
;

CREATE TABLE SIS_DET_TIEMPO_EXTRA
(
ID_DET_HORA_EXTRA NUMBER NOT NULL,
FECHA DATE,
DESC_ACTIVIDAD VARCHAR2(250),
HORA_INICIO NUMBER,
HORA_FIN NUMBER,
ID_TIEMPO_EXTRAORDINARIO NUMBER
)
;

CREATE TABLE SIS_DET_LICENCIA
(
ID_DET_LICENCIA NUMBER NOT NULL,
ID_SOLICITUD NUMBER NOT NULL,
FECHA_INICIO DATE,
FECHA_FIN DATE,
MOTIVO VARCHAR2(350),
PRORROGA VARCHAR2(2),
FECHA_ANT_INICIO DATE,
FECHA_ANT_FIN DATE,
MOTIVO_ANT VARCHAR2(350)
)
;

CREATE TABLE SIS_HISTORICO_SUELDO
(
ID_CONTRATO NUMBER(10, 0) NOT NULL,
ID_VARIACION_SUELDO NUMBER NOT NULL,
SUELDO_BASE_ANT NUMBER,
SUELDO_BASE NUMBER,
FECHA VARCHAR2(4000)
)
;

CREATE TABLE SIS_NOMINA
(
ID_NOMINA NUMBER NOT NULL,
ID_TIPO_NOMINA NUMBER,
ID_PROCESO NUMBER,
ID_PARTIDA NUMBER,
ID_CONTRATO NUMBER,
ANIO NUMBER,
PERIODO NUMBER,
SUELDO_BASE NUMBER,
NOMINAL NUMBER,
TOTAL_BONO NUMBER,
TOTAL_DESCUENTO VARCHAR2(4000),
TOTAL_PLUS_SALARIAL VARCHAR2(4000)
)
;

CREATE TABLE SIS_MONEDA
(
ID_MONEDA NUMBER NOT NULL,
NOMBRE VARCHAR2(100),
SIMBOLO VARCHAR2(2),
FACTOR_CONV NUMBER
)
;

CREATE TABLE SIS_DIRECCION
(
ID_DIRECCION NUMBER NOT NULL,
ID_MUNICIPIO NUMBER(10, 0) NOT NULL,
REGISTRO_EMPLEADO NUMBER(10, 0) NOT NULL,
AVECALLE VARCHAR2(50),
NUM_CASA VARCHAR2(10),
APTO VARCHAR2(50),
ZONA VARCHAR2(2),
COLONIA VARCHAR2(250)
)
;

CREATE TABLE SIS_COMPLEMENTO_IGSS
(
ID_COMPLEMENTO_IGSS NUMBER NOT NULL,
ID_SUSPENCION_IGSS VARCHAR2(4000),
ID_PROCESO NUMBER(10, 0),
DIA_NO_PAGA_IGSS NUMBER,
COMPLEMENTO_SUELDO NUMBER,
DIF_CALCULO_IGSS NUMBER,
NOMINAL NUMBER,
ANIO NUMBER,
PERIODO NUMBER,
DIA_INICIO NUMBER(3, 0),
DIA_FIN NUMBER(3, 0)
)
;

CREATE TABLE SIS_SUSPENCION_IGSS
(
ID_SUSPENCION_IGSS VARCHAR2(4000) NOT NULL,
REGISTRO_EMPLEADO NUMBER,
FECHA_INICIO_SUSP_IGSS DATE,
FECHA_ALTA_SUSP_IGSS VARCHAR2(4000),
MOTIVO_SUSP_IGSS NUMBER,
SOLICITUD NUMBER(10, 0)
)
;

CREATE TABLE SIS_VARIACION_SUELDO
(
ID_VARIACION_SUELDO NUMBER NOT NULL,
DESCRIPCION VARCHAR2(250),
VALOR NUMBER,
PORCENTAJE NUMBER,
FECHA_CREACION DATE,
FECHA_INICIO DATE,
FECHA_FIN VARCHAR2(4000)
)
;

CREATE TABLE SIS_PAGO
(
ID_PROCESO NUMBER(10, 0) NOT NULL,
ID_DOCUMENTO_BANCO NUMBER(10, 0) NOT NULL,
ID_PAGO NUMBER NOT NULL,
ID_NOMINA NUMBER,
ID_COMPLEMENTO_IGSS NUMBER
)
;

CREATE TABLE SIS_DET_CHEQUE_ANULADO
(
ID_DET_CHEQUE_ANULADO NUMBER NOT NULL,
ID_CHEQUE_ANULADO NUMBER,
NO_CHEQUE NUMBER,
PARTIDA NUMBER,
PLAZA NUMBER,
COD_CLASIFICACION VARCHAR2(10),
REG_EMPLEADO NUMBER,
NO_ACTA NUMBER,
REPOSICION NUMBER
)
;

CREATE TABLE SIS_CHEQUE_ANULADO
(
ID_CHEQUE_ANULADO NUMBER NOT NULL,
ID_MOTIVO_ANULACION NUMBER,
ID_TIPO_NOMINA NUMBER,
DEPENDENCIA NUMBER,
PERIODO NUMBER,
ANIO NUMBER,
DE VARCHAR2(250),
PARA VARCHAR2(250),
FECHA_CREACION DATE
)
;

CREATE TABLE SIS_MOTIVO_ANULACION
(
ID_MOTIVO_ANULACION NUMBER NOT NULL,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(250)
)
;

CREATE TABLE SIS_TIPO_NOMINA
(
ID_TIPO_NOMINA NUMBER NOT NULL,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(250)
)
;

CREATE TABLE SIS_CARGA_ARCHIVO_DATOS
(
ID_CARGA_ARCHIVO_DATOS NUMBER(7, 0) NOT NULL,
ID_ORIGEN_CARGA_ARCHIVO NUMBER(3, 0),
NOM_ARCHIVO VARCHAR2(250),
PERIODO NUMBER(2, 0),
ANIO NUMBER(4, 0),
FECHA_INICIO DATE,
FECHA_FIN DATE
)
;

CREATE TABLE SIS_ARCHIVO_APERTURA
(
ID_ARCHIVO_APERTURA NUMBER(10, 0) NOT NULL,
ID_CARGA_ARCHIVO_DATOS NUMBER(7, 0),
PLAZA NUMBER,
PUESTO VARCHAR2(10),
HORAS_PLAZA NUMBER(2, 0),
REGISTRO_EMPLEADO NUMBER,
SALARIO_BASE NUMBER(8, 2),
COMPL_SALARIAL NUMBER(8, 2),
ESCALAFON NUMBER(8, 2),
PARTIDA VARCHAR2(20),
FECHA_INICIO DATE,
FECHA_FIN DATE
)
;

CREATE TABLE SIS_ARCHIVO_ADJUNTO
(
ID_ARCHIVO_ADJUNTO NUMBER NOT NULL,
ID_TIPO_ARCHIVO NUMBER,
ID_CONTRATO NUMBER(10, 0),
NOM_ARCHIVO VARCHAR2(4000),
PATH VARCHAR2(350),
FECHA DATE,
DESCRIPCION VARCHAR2(350),
ID_SOLICITUD NUMBER(10, 0)
)
;

CREATE TABLE SIS_TIPO_ARCHIVO
(
ID_TIPO_ARCHIVO NUMBER NOT NULL,
NOMBRE VARCHAR2(50)
)
;

CREATE TABLE SIS_VARIACION_NOMINA
(
ID_VARIACION_NOMINA NUMBER NOT NULL,
ID_CONTRATO NUMBER,
DIAS_LABORADOS NUMBER(3, 0),
HORAS NUMBER(2, 0),
SUELDO_NOMINAL NUMBER,
STATUS NUMBER
)
;

CREATE TABLE SIS_VARIACION_DET_AJUSTE
(
ID_VARIACION_NOMINA NUMBER NOT NULL,
ID_AJUSTE NUMBER NOT NULL,
ID_ESTADO NUMBER,
VALOR NUMBER,
DESCRIPCION VARCHAR2(350)
)
;

CREATE TABLE SIS_ARCHIVO_PRESTAMO
(
ID_ARCHIVO_PRESTAMO NUMBER(10, 0) NOT NULL,
ID_CARGA_ARCHIVO_DATOS NUMBER(7, 0),
REGISTRO_EMPLEADO NUMBER,
NO_PRESTAMO VARCHAR2(20),
MONTO NUMBER(8, 2),
COD_PRESTAMO NUMBER
)
;

CREATE TABLE SIS_ORIGEN_CARGA_ARCHIVO
(
ID_ORIGEN_CARGA_ARCHIVO NUMBER(3, 0) NOT NULL,
NOMBRE VARCHAR2(150),
DESCRIPCION VARCHAR2(500)
)
;

CREATE TABLE SIS_ASIGNACION_NUM_CHEQUE
(
ID_ASIGNACION_NUM_CHEQUE NUMBER NOT NULL,
ID_BANCO NUMBER,
FECHA_CREACION DATE
)
;

CREATE TABLE SIS_DET_ASIG_CHEQUE
(
ID_DET_ASIG_CHEQUE VARCHAR2(4000) NOT NULL,
ID_ASIGNACION_NUM_CHEQUE NUMBER,
NUM_CHEQUE_INICIAL NUMBER,
NUM_CHEQUE_FIN NUMBER
)
;

CREATE TABLE SIS_ESTADO
(
ID_ESTADO NUMBER(3, 0) NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
DESCRIPCION VARCHAR2(500),
TABLA VARCHAR2(100) NOT NULL
)
;

CREATE TABLE SIS_ACTA_FACSIMIL
(
ID_ACTA_FACSIMIL NUMBER NOT NULL,
FECHA_INICIO_ACTA DATE,
FECHA_FIN_ACTA DATE,
NOMINA VARCHAR2(50)
)
;

CREATE TABLE SIS_DET_CHEQUES
(
ID_DET_CHEQUES NUMBER,
ID_ACTA_FACSIMIL NUMBER,
BANCO NUMBER,
CUENTA VARCHAR2(50),
NUM_CHEQUE_INICIAL NUMBER,
NUM_CHEQUE_FINAL VARCHAR2(4000),
TIPO VARCHAR2(2)
)
;

CREATE TABLE SIS_COMISION_FACSIMIL
(
ID_ACTA_FACSIMIL NUMBER NOT NULL,
REGISTRO_EMPLEADO NUMBER NOT NULL
)
;

CREATE TABLE SIS_TIEMPO_EXTRAORDINARIO
(
ID_TIEMPO_EXTRAORDINARIO NUMBER NOT NULL,
ID_SOLICITUD NUMBER(10, 0),
PARTIDA_GASTO VARCHAR2(15),
PERIODO NUMBER,
ANIO NUMBER,
SALARIO_MENSUAL NUMBER,
TOTAL_HORAS_EXTRA NUMBER,
VALOR_HORA_EXTRA NUMBER,
VALOR_NOMINAL NUMBER,
VALOR_LIQUDO NUMBER
)
;

CREATE TABLE SIS_DESCUENTO_TIEMPO_EXTRA
(
ID_TIEMPO_EXTRAORDINARIO NUMBER NOT NULL,
ID_AJUSTE NUMBER NOT NULL,
VALOR NUMBER
)
;

CREATE TABLE SIS_COMPLEMENTO
(
ID_COMPLEMENTO VARCHAR2(4000),
ID_SOLICITUD NUMBER(10, 0),
TIPO VARCHAR2(2),
PERIODO NUMBER,
ANIO NUMBER,
FECHA_ING_PLAZA DATE,
NUM_HORAS NUMBER,
VALOR_NOMINAL NUMBER
)
;

CREATE TABLE SIS_HISTORICO_CARGA_ARCHIVO
(
ID_PROCESO NUMBER(10, 0) NOT NULL,
ID_CARGA_ARCHIVO_DATOS NUMBER(7, 0) NOT NULL
)
;

CREATE TABLE SIS_USUARIO_PERFIL
(
ID_USUARIO NUMBER(6, 0) NOT NULL,
ID_PERFIL NUMBER(6, 0) NOT NULL,
NUMERO NUMBER(3, 0) NOT NULL,
ID_ESTADO NUMBER(3, 0),
FECHA_CREACION DATE
)
;

ALTER TABLE SIS_DEPARTAMENTO
ADD CONSTRAINT SIS_DEPARTAMENTO_PK PRIMARY KEY
(
ID_DEPARTAMENTO
)
 ENABLE
;

ALTER TABLE SIS_MUNICIPIO
ADD CONSTRAINT SIS_MUNICIPIO_PK PRIMARY KEY
(
ID_MUNICIPIO
)
 ENABLE
;

ALTER TABLE SIS_DEPENDENCIA
ADD CONSTRAINT SIS_DEPENDENCIA_PK PRIMARY KEY
(
ID_DEPENDENCIA
)
 ENABLE
;

ALTER TABLE SIS_UNIDAD_EJECUTORA
ADD CONSTRAINT SIS_UNIDAD_EJECUTORA_PK PRIMARY KEY
(
ID_UNIDAD
)
 ENABLE
;

ALTER TABLE SIS_BANCO
ADD CONSTRAINT SIS_BANCO_PK PRIMARY KEY
(
ID_BANCO
)
 ENABLE
;

ALTER TABLE SIS_CUENTA
ADD CONSTRAINT SIS_CUENTA_PK PRIMARY KEY
(
ID_CUENTA
)
 ENABLE
;

ALTER TABLE SIS_AJUSTE
ADD CONSTRAINT SIS_AJUSTE_PK PRIMARY KEY
(
ID_AJUSTE
)
 ENABLE
;

ALTER TABLE SIS_TIPO_AJUSTE
ADD CONSTRAINT SIS_TIPO_AJUSTE_PK PRIMARY KEY
(
ID_TIPOAJUSTE
)
 ENABLE
;

ALTER TABLE SIS_REGLA
ADD CONSTRAINT SIS_REGLA_PK PRIMARY KEY
(
ID_REGLA
)
 ENABLE
;

ALTER TABLE SIS_PUESTO
ADD CONSTRAINT SIS_PUESTO_PK PRIMARY KEY
(
ID_PUESTO
)
 ENABLE
;

ALTER TABLE SIS_PARTIDA
ADD CONSTRAINT SIS_PARTIDA_PK PRIMARY KEY
(
ID_PARTIDA
)
 ENABLE
;

ALTER TABLE SIS_PLAZA
ADD CONSTRAINT SIS_PLAZA_PK PRIMARY KEY
(
ID_PARTIDA,
ID_PUESTO,
CORRELATIVO
)
 ENABLE
;

ALTER TABLE SIS_TIPO_DOCUMENTO
ADD CONSTRAINT SIS_TIPO_DOCUMENTO_PK PRIMARY KEY
(
ID_TIPO_DOCUMENTO
)
 ENABLE
;

ALTER TABLE SIS_DOCUMENTO_BANCO
ADD CONSTRAINT SIS_DOCUMENTO_BANCO_PK PRIMARY KEY
(
ID_DOCUMENTO_BANCO
)
 ENABLE
;

ALTER TABLE SIS_EMPLEADO
ADD CONSTRAINT SIS_EMPLEADO_PK PRIMARY KEY
(
REGISTRO_EMPLEADO
)
 ENABLE
;

ALTER TABLE SIS_NIVEL_ACADEMICO
ADD CONSTRAINT NIVEL_ACADEMICO_PK PRIMARY KEY
(
ID_NIVEL
)
 ENABLE
;

ALTER TABLE SIS_PROCESO
ADD CONSTRAINT SIS_PROCESO_PK PRIMARY KEY
(
ID_PROCESO
)
 ENABLE
;

ALTER TABLE SIS_TIPO_PROCESO
ADD CONSTRAINT SIS_TIPO_PROCESO_PK PRIMARY KEY
(
ID_TIPOPROCESO
)
 ENABLE
;

ALTER TABLE SIS_CONTRATO
ADD CONSTRAINT SIS_CONTRATO_PK PRIMARY KEY
(
ID_CONTRATO
)
 ENABLE
;

ALTER TABLE SIS_DET_CALCULO_AJUSTE
ADD CONSTRAINT SIS_DETALLE_AJUSTE_PK PRIMARY KEY
(
ID_PROCESO,
ID_AJUSTE,
ID_CONTRATO
)
 ENABLE
;

ALTER TABLE SIS_AJUSTE_CONTRATO
ADD CONSTRAINT SIS_AJUSTE_CONTRATO_PK PRIMARY KEY
(
ID_CONTRATO,
ID_AJUSTE,
ID_CORRELATIVO
)
 ENABLE
;

ALTER TABLE SIS_AJUSTE_EMPLEADO
ADD CONSTRAINT AJUSTE_EMPLEADO_PK PRIMARY KEY
(
REGISTRO_EMPLEADO,
ID_AJUSTE,
ID_CORRELATIVO
)
 ENABLE
;

ALTER TABLE SIS_TIPO_SOLICITUD
ADD CONSTRAINT SIS_TIPO_SOLICITUD_PK PRIMARY KEY
(
ID_TIPO_SOLICITUD
)
 ENABLE
;

ALTER TABLE SIS_SOLICITUD
ADD CONSTRAINT SIS_SOLICITUD_PK PRIMARY KEY
(
ID_SOLICITUD
)
 ENABLE
;

ALTER TABLE SIS_CONVENIO
ADD CONSTRAINT CONVENIO_PK PRIMARY KEY
(
ID_CONVENIO
)
 ENABLE
;

ALTER TABLE SIS_BENEFICIARIO
ADD CONSTRAINT SIS_BENEFICIARIO_PK PRIMARY KEY
(
ID_BENEFICIARIO
)
 ENABLE
;

ALTER TABLE SIS_HISTORICO_EST_SOLICITUD
ADD CONSTRAINT SIS_HIST_EST_SOL_PK PRIMARY KEY
(
ID_ESTADO,
ID_SOLICITUD
)
 ENABLE
;

ALTER TABLE SIS_MENSAJE
ADD CONSTRAINT SIS_MENSAJE_PK PRIMARY KEY
(
ID_MENSAJE
)
 ENABLE
;

ALTER TABLE SIS_USUARIO
ADD CONSTRAINT SIS_USUARIO_PK PRIMARY KEY
(
ID_USUARIO
)
 ENABLE
;

ALTER TABLE SIS_PERFIL
ADD CONSTRAINT SIS_PERFIL_PK PRIMARY KEY
(
ID_PERFIL
)
 ENABLE
;

ALTER TABLE SIS_OPCION_MENU
ADD CONSTRAINT SIS_OPCION_MENU_PK PRIMARY KEY
(
ID_OPCION_MENU
)
 ENABLE
;

ALTER TABLE SIS_PERMISO
ADD CONSTRAINT SIS_PERMISO_PK PRIMARY KEY
(
ID_PERFIL,
ID_OPCION_MENU
)
 ENABLE
;

ALTER TABLE SIS_TIPO_CONTRATO
ADD CONSTRAINT SIS_TIPO_CONTRATO_PK PRIMARY KEY
(
ID_TIPO_CONTRATO
)
 ENABLE
;

ALTER TABLE SIS_FORMA_OBT_PUESTO
ADD CONSTRAINT SIS_FORMA_PK PRIMARY KEY
(
ID_FORMA_OBT_PUESTO
)
 ENABLE
;

ALTER TABLE SIS_AJUSTEXPROCESO
ADD CONSTRAINT SIS_AJUSTEXPROCESO_PK PRIMARY KEY
(
ID_TIPOPROCESO,
ID_AJUSTE,
FECHA_INICIO
)
 ENABLE
;

ALTER TABLE SIS_FORMA_PAGO
ADD CONSTRAINT SIS_FORMA_PAGO_PK PRIMARY KEY
(
FECHA_INICIO
)
 ENABLE
;

ALTER TABLE SIS_HISTORICO_EST_CONTRATO
ADD CONSTRAINT SIS_HISTORICO_EST_CONTRATO_PK PRIMARY KEY
(
ID_CONTRATO,
ID_ESTADO,
FECHA
)
 ENABLE
;

ALTER TABLE SIS_DET_TIEMPO_EXTRA
ADD CONSTRAINT DET_AUT_TIEMPO_EXTRA_PK PRIMARY KEY
(
ID_DET_HORA_EXTRA
)
 ENABLE
;

ALTER TABLE SIS_DET_LICENCIA
ADD CONSTRAINT DET_LICENCIA_PK PRIMARY KEY
(
ID_DET_LICENCIA
)
 ENABLE
;

ALTER TABLE SIS_HISTORICO_SUELDO
ADD CONSTRAINT SIS_HISTORICO_SUELDO_PK PRIMARY KEY
(
ID_VARIACION_SUELDO,
ID_CONTRATO
)
 ENABLE
;

ALTER TABLE SIS_NOMINA
ADD CONSTRAINT SIS_NOMINA_PK PRIMARY KEY
(
ID_NOMINA
)
 ENABLE
;

ALTER TABLE SIS_MONEDA
ADD CONSTRAINT SIS_MONEDA_PK PRIMARY KEY
(
ID_MONEDA
)
 ENABLE
;

ALTER TABLE SIS_DIRECCION
ADD CONSTRAINT SIS_DIRECCION_PK PRIMARY KEY
(
ID_DIRECCION
)
 ENABLE
;

ALTER TABLE SIS_COMPLEMENTO_IGSS
ADD CONSTRAINT SIS_COMPLEMENTO_IGSS_PK PRIMARY KEY
(
ID_COMPLEMENTO_IGSS
)
 ENABLE
;

ALTER TABLE SIS_SUSPENCION_IGSS
ADD CONSTRAINT SIS_SUSPENCION_IGSS_PK PRIMARY KEY
(
ID_SUSPENCION_IGSS
)
 ENABLE
;

ALTER TABLE SIS_VARIACION_SUELDO
ADD CONSTRAINT SIS_VARIACION_SUELDO_PK PRIMARY KEY
(
ID_VARIACION_SUELDO
)
 ENABLE
;

ALTER TABLE SIS_PAGO
ADD CONSTRAINT SIS_PAGO_PK PRIMARY KEY
(
ID_PROCESO,
ID_DOCUMENTO_BANCO,
ID_PAGO
)
 ENABLE
;

ALTER TABLE SIS_DET_CHEQUE_ANULADO
ADD CONSTRAINT SIS_DET_CHEQUE_ANULADO_PK PRIMARY KEY
(
ID_DET_CHEQUE_ANULADO
)
 ENABLE
;

ALTER TABLE SIS_CHEQUE_ANULADO
ADD CONSTRAINT SIS_CHEQUE_ANULADO_PK PRIMARY KEY
(
ID_CHEQUE_ANULADO
)
 ENABLE
;

ALTER TABLE SIS_MOTIVO_ANULACION
ADD CONSTRAINT SIS_MOTIVO_ANULACION_PK PRIMARY KEY
(
ID_MOTIVO_ANULACION
)
 ENABLE
;

ALTER TABLE SIS_TIPO_NOMINA
ADD CONSTRAINT SIS_TIPO_NOMINA_PK PRIMARY KEY
(
ID_TIPO_NOMINA
)
 ENABLE
;

ALTER TABLE SIS_CARGA_ARCHIVO_DATOS
ADD CONSTRAINT SIS_CARGA_ARCHIVO_DATOS_PK PRIMARY KEY
(
ID_CARGA_ARCHIVO_DATOS
)
 ENABLE
;

ALTER TABLE SIS_ARCHIVO_APERTURA
ADD CONSTRAINT SIS_ARCHIVO_APERTURA_PK PRIMARY KEY
(
ID_ARCHIVO_APERTURA
)
 ENABLE
;

ALTER TABLE SIS_ARCHIVO_ADJUNTO
ADD CONSTRAINT SIS_ARCHIVO_ADJUNTO_PK PRIMARY KEY
(
ID_ARCHIVO_ADJUNTO
)
 ENABLE
;

ALTER TABLE SIS_TIPO_ARCHIVO
ADD CONSTRAINT SIS_TIPO_ARCHIVO_PK PRIMARY KEY
(
ID_TIPO_ARCHIVO
)
 ENABLE
;

ALTER TABLE SIS_VARIACION_NOMINA
ADD CONSTRAINT SIS_VARIACION_NOMINA_PK PRIMARY KEY
(
ID_VARIACION_NOMINA
)
 ENABLE
;

ALTER TABLE SIS_VARIACION_DET_AJUSTE
ADD CONSTRAINT SIS_VAIRACION_DET_AJUSTE_PK PRIMARY KEY
(
ID_VARIACION_NOMINA,
ID_AJUSTE
)
 ENABLE
;

ALTER TABLE SIS_ARCHIVO_PRESTAMO
ADD CONSTRAINT SIS_CARGA_PRESTAMO_PK PRIMARY KEY
(
ID_ARCHIVO_PRESTAMO
)
 ENABLE
;

ALTER TABLE SIS_ORIGEN_CARGA_ARCHIVO
ADD CONSTRAINT SIS_ORIGEN_CARGA_PK PRIMARY KEY
(
ID_ORIGEN_CARGA_ARCHIVO
)
 ENABLE
;

ALTER TABLE SIS_ASIGNACION_NUM_CHEQUE
ADD CONSTRAINT SIS_ASIGNACION_NUM_CHEQUE_PK PRIMARY KEY
(
ID_ASIGNACION_NUM_CHEQUE
)
 ENABLE
;

ALTER TABLE SIS_DET_ASIG_CHEQUE
ADD CONSTRAINT SIS_DET_ASIG_CHEQUE_PK PRIMARY KEY
(
ID_DET_ASIG_CHEQUE
)
 ENABLE
;

ALTER TABLE SIS_ESTADO
ADD CONSTRAINT SIS_ESTADO_PK PRIMARY KEY
(
ID_ESTADO
)
 ENABLE
;

ALTER TABLE SIS_ACTA_FACSIMIL
ADD CONSTRAINT SIS_ACTA_FACSIMIL_PK PRIMARY KEY
(
ID_ACTA_FACSIMIL
)
 ENABLE
;

ALTER TABLE SIS_COMISION_FACSIMIL
ADD CONSTRAINT SIS_COMISION_FACSIMIL_PK PRIMARY KEY
(
ID_ACTA_FACSIMIL,
REGISTRO_EMPLEADO
)
 ENABLE
;

ALTER TABLE SIS_TIEMPO_EXTRAORDINARIO
ADD CONSTRAINT SIS_TIEMPO_EXTRAORDINARIO_PK PRIMARY KEY
(
ID_TIEMPO_EXTRAORDINARIO
)
 ENABLE
;

ALTER TABLE SIS_DESCUENTO_TIEMPO_EXTRA
ADD CONSTRAINT SIS_DESCUENTO_TIEMPO_EXTR_PK PRIMARY KEY
(
ID_TIEMPO_EXTRAORDINARIO,
ID_AJUSTE
)
 ENABLE
;

ALTER TABLE SIS_HISTORICO_CARGA_ARCHIVO
ADD CONSTRAINT SIS_HIST_CARGA_PK PRIMARY KEY
(
ID_PROCESO,
ID_CARGA_ARCHIVO_DATOS
)
 ENABLE
;

ALTER TABLE SIS_USUARIO_PERFIL
ADD CONSTRAINT SIS_USUARIO_PERFIL_PK PRIMARY KEY
(
ID_USUARIO,
ID_PERFIL,
NUMERO
)
 ENABLE
;

ALTER TABLE SIS_MUNICIPIO
ADD CONSTRAINT SIS_MUNICIPIO_DEPARTAMENTO_FK FOREIGN KEY
(
ID_DEPARTAMENTO
)
REFERENCES SIS_DEPARTAMENTO
(
ID_DEPARTAMENTO
) ENABLE
;

ALTER TABLE SIS_UNIDAD_EJECUTORA
ADD CONSTRAINT SIS_UNIDAD_EJECUTORA_DEP_FK FOREIGN KEY
(
ID_UNIDAD
)
REFERENCES SIS_DEPENDENCIA
(
ID_DEPENDENCIA
) ENABLE
;

ALTER TABLE SIS_CUENTA
ADD CONSTRAINT SIS_CUENTA_EMPLEADO_FK FOREIGN KEY
(
REGISTRO_EMPLEADO
)
REFERENCES SIS_EMPLEADO
(
REGISTRO_EMPLEADO
) ENABLE
;

ALTER TABLE SIS_CUENTA
ADD CONSTRAINT SIS_CUENTA_BANCO_FK FOREIGN KEY
(
ID_BANCO
)
REFERENCES SIS_BANCO
(
ID_BANCO
) ENABLE
;

ALTER TABLE SIS_AJUSTE
ADD CONSTRAINT SIS_AJUSTE_TIPO_AJUSTE_FK FOREIGN KEY
(
ID_TIPOAJUSTE
)
REFERENCES SIS_TIPO_AJUSTE
(
ID_TIPOAJUSTE
) ENABLE
;

ALTER TABLE SIS_AJUSTE
ADD CONSTRAINT SIS_AJUSTE_VARIANTE_FK FOREIGN KEY
(
VARIANTE
)
REFERENCES SIS_AJUSTE
(
ID_AJUSTE
) ENABLE
;

ALTER TABLE SIS_REGLA
ADD CONSTRAINT SIS_REGLA_SIS_AJUSTE_FK FOREIGN KEY
(
ID_AJUSTE
)
REFERENCES SIS_AJUSTE
(
ID_AJUSTE
) ENABLE
;

ALTER TABLE SIS_PARTIDA
ADD CONSTRAINT SIS_PARTIDA_UNIDAD_EJEC_FK FOREIGN KEY
(
ID_UNIDAD
)
REFERENCES SIS_UNIDAD_EJECUTORA
(
ID_UNIDAD
) ENABLE
;

ALTER TABLE SIS_PLAZA
ADD CONSTRAINT SIS_PLAZA_PUESTO_FK FOREIGN KEY
(
ID_PUESTO
)
REFERENCES SIS_PUESTO
(
ID_PUESTO
) ENABLE
;

ALTER TABLE SIS_PLAZA
ADD CONSTRAINT SIS_PLAZA_PARTIDA_FK FOREIGN KEY
(
ID_PARTIDA
)
REFERENCES SIS_PARTIDA
(
ID_PARTIDA
) ENABLE
;

ALTER TABLE SIS_DOCUMENTO_BANCO
ADD CONSTRAINT SIS_DOCUMENTO_CUENTA_FK FOREIGN KEY
(
ID_CUENTA
)
REFERENCES SIS_CUENTA
(
ID_CUENTA
) ENABLE
;

ALTER TABLE SIS_DOCUMENTO_BANCO
ADD CONSTRAINT SIS_DOCUMENTO_BANCO_FK FOREIGN KEY
(
ID_BANCO
)
REFERENCES SIS_BANCO
(
ID_BANCO
) ENABLE
;

ALTER TABLE SIS_DOCUMENTO_BANCO
ADD CONSTRAINT SIS_DOCUMENTO_ESTADO_FK FOREIGN KEY
(
ID_ESTADO
)
REFERENCES SIS_ESTADO
(
ID_ESTADO
) ENABLE
;

ALTER TABLE SIS_DOCUMENTO_BANCO
ADD CONSTRAINT SIS_DOCUMENTO_MONEDA_FK FOREIGN KEY
(
ID_MONEDA
)
REFERENCES SIS_MONEDA
(
ID_MONEDA
) ENABLE
;

ALTER TABLE SIS_DOCUMENTO_BANCO
ADD CONSTRAINT SIS_DOCUMENTO_DOC_BANCO_FK FOREIGN KEY
(
DOC_REEMPLAZA
)
REFERENCES SIS_DOCUMENTO_BANCO
(
ID_DOCUMENTO_BANCO
) ENABLE
;

ALTER TABLE SIS_DOCUMENTO_BANCO
ADD CONSTRAINT SIS_DOCUMENTO_TIPO_DOC_FK FOREIGN KEY
(
ID_TIPO_DOCUMENTO
)
REFERENCES SIS_TIPO_DOCUMENTO
(
ID_TIPO_DOCUMENTO
) ENABLE
;

ALTER TABLE SIS_EMPLEADO
ADD CONSTRAINT SIS_EMPLEADO_ESTADO_FK FOREIGN KEY
(
ID_ESTADO
)
REFERENCES SIS_ESTADO
(
ID_ESTADO
) ENABLE
;

ALTER TABLE SIS_EMPLEADO
ADD CONSTRAINT SIS_EMPLEADO_NIVACADEMICO_FK FOREIGN KEY
(
ID_NIVEL
)
REFERENCES SIS_NIVEL_ACADEMICO
(
ID_NIVEL
) ENABLE
;

ALTER TABLE SIS_PROCESO
ADD CONSTRAINT SIS_PROCESO_TIPO_PROCESO_FK FOREIGN KEY
(
TIPOPROCESO
)
REFERENCES SIS_TIPO_PROCESO
(
ID_TIPOPROCESO
) ENABLE
;

ALTER TABLE SIS_PROCESO
ADD CONSTRAINT SIS_PROCESO_PROCESO_FK FOREIGN KEY
(
PROCESO_PADRE
)
REFERENCES SIS_PROCESO
(
ID_PROCESO
) ENABLE
;

ALTER TABLE SIS_CONTRATO
ADD CONSTRAINT SIS_CONTRATO_EMPLEADO_FK FOREIGN KEY
(
REGISTRO_EMPLEADO
)
REFERENCES SIS_EMPLEADO
(
REGISTRO_EMPLEADO
) ENABLE
;

ALTER TABLE SIS_CONTRATO
ADD CONSTRAINT SIS_CONTRATO_TIPOCONTRATO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_TIPO_CONTRATO
(
ID_TIPO_CONTRATO
) ENABLE
;

ALTER TABLE SIS_CONTRATO
ADD CONSTRAINT SIS_CONTRATO_SIS_PLAZA_FK FOREIGN KEY
(
ID_PARTIDA,
ID_PUESTO,
CORRELATIVO
)
REFERENCES SIS_PLAZA
(
ID_PARTIDA,
ID_PUESTO,
CORRELATIVO
) ENABLE
;

ALTER TABLE SIS_CONTRATO
ADD CONSTRAINT SIS_CONTRATO_SIS_MUNICIPIO_FK FOREIGN KEY
(
LUGAR_POSESION
)
REFERENCES SIS_MUNICIPIO
(
ID_MUNICIPIO
) ENABLE
;

ALTER TABLE SIS_CONTRATO
ADD CONSTRAINT SIS_CONTRAT_FORM_OBT_PUESTO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_FORMA_OBT_PUESTO
(
ID_FORMA_OBT_PUESTO
) ENABLE
;

ALTER TABLE SIS_DET_CALCULO_AJUSTE
ADD CONSTRAINT SIS_DET_CALC_AJUSTE_FK FOREIGN KEY
(
ID_AJUSTE
)
REFERENCES SIS_AJUSTE
(
ID_AJUSTE
) ENABLE
;

ALTER TABLE SIS_DET_CALCULO_AJUSTE
ADD CONSTRAINT SIS_DET_CALC_CONTRATO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_CONTRATO
(
ID_CONTRATO
) ENABLE
;

ALTER TABLE SIS_DET_CALCULO_AJUSTE
ADD CONSTRAINT SIS_DET_CALC_PROCESO_FK FOREIGN KEY
(
ID_PROCESO
)
REFERENCES SIS_PROCESO
(
ID_PROCESO
) ENABLE
;

ALTER TABLE SIS_AJUSTE_CONTRATO
ADD CONSTRAINT SIS_AJUSTE_CONTRATO_AJUSTE_FK FOREIGN KEY
(
ID_AJUSTE
)
REFERENCES SIS_AJUSTE
(
ID_AJUSTE
) ENABLE
;

ALTER TABLE SIS_AJUSTE_CONTRATO
ADD CONSTRAINT SIS_AJUSTE_CONTRATO_CONTRA_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_CONTRATO
(
ID_CONTRATO
) ENABLE
;

ALTER TABLE SIS_AJUSTE_CONTRATO
ADD CONSTRAINT SIS_AJUSTE_CONTRATO_PROCESO_FK FOREIGN KEY
(
ID_PROCESO
)
REFERENCES SIS_PROCESO
(
ID_PROCESO
) ENABLE
;

ALTER TABLE SIS_AJUSTE_EMPLEADO
ADD CONSTRAINT AJUSTE_EMPLEADO_EMPLEADO_FK FOREIGN KEY
(
REGISTRO_EMPLEADO
)
REFERENCES SIS_EMPLEADO
(
REGISTRO_EMPLEADO
) ENABLE
;

ALTER TABLE SIS_AJUSTE_EMPLEADO
ADD CONSTRAINT SIS_AJUSTE_EMPLEADO_AJUSTE_FK FOREIGN KEY
(
ID_AJUSTE
)
REFERENCES SIS_AJUSTE
(
ID_AJUSTE
) ENABLE
;

ALTER TABLE SIS_AJUSTE_EMPLEADO
ADD CONSTRAINT SIS_AJUSTE_EMPLEADO_PROCESO_FK FOREIGN KEY
(
ID_PROCESO
)
REFERENCES SIS_PROCESO
(
ID_PROCESO
) ENABLE
;

ALTER TABLE SIS_SOLICITUD
ADD CONSTRAINT SOLICITUD_TIPO_SOLICITUD_FK FOREIGN KEY
(
ID_TIPO_SOLICITUD
)
REFERENCES SIS_TIPO_SOLICITUD
(
ID_TIPO_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_CONVENIO
ADD CONSTRAINT SIS_CONVENIO_SIS_SOLICITUD_FK FOREIGN KEY
(
ID_SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_BENEFICIARIO
ADD CONSTRAINT SIS_BENEFICIARIO_FK FOREIGN KEY
(
ID_SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_HISTORICO_EST_SOLICITUD
ADD CONSTRAINT SIS_HIST_EST_SOL_USUARIO_FK FOREIGN KEY
(
ID_USUARIO
)
REFERENCES SIS_USUARIO
(
ID_USUARIO
) ENABLE
;

ALTER TABLE SIS_HISTORICO_EST_SOLICITUD
ADD CONSTRAINT SIS_HIST_EST_SOL_ESTADO_FK FOREIGN KEY
(
ID_ESTADO
)
REFERENCES SIS_ESTADO
(
ID_ESTADO
) ENABLE
;

ALTER TABLE SIS_HISTORICO_EST_SOLICITUD
ADD CONSTRAINT SIS_HIST_EST_SOL_SOL_FK FOREIGN KEY
(
ID_SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_MENSAJE
ADD CONSTRAINT SIS_MENSAJE_USUARIO_FK FOREIGN KEY
(
ID_USUARIO
)
REFERENCES SIS_USUARIO
(
ID_USUARIO
) ENABLE
;

ALTER TABLE SIS_MENSAJE
ADD CONSTRAINT SIS_MENSAJE_SOLICITUD_FK FOREIGN KEY
(
ID_SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_USUARIO
ADD CONSTRAINT SIS_USUARIO_ESTADO_FK FOREIGN KEY
(
ID_USUARIO
)
REFERENCES SIS_ESTADO
(
ID_ESTADO
) ENABLE
;

ALTER TABLE SIS_PERMISO
ADD CONSTRAINT SIS_PERMISO_PERFIL_FK FOREIGN KEY
(
ID_PERFIL
)
REFERENCES SIS_PERFIL
(
ID_PERFIL
) ENABLE
;

ALTER TABLE SIS_PERMISO
ADD CONSTRAINT SIS_PERMISO_SIS_OPCION_MENU_FK FOREIGN KEY
(
ID_OPCION_MENU
)
REFERENCES SIS_OPCION_MENU
(
ID_OPCION_MENU
) ENABLE
;

ALTER TABLE SIS_AJUSTEXPROCESO
ADD CONSTRAINT SIS_AJUSTXPROC_AJUSTE_FK FOREIGN KEY
(
ID_AJUSTE
)
REFERENCES SIS_AJUSTE
(
ID_AJUSTE
) ENABLE
;

ALTER TABLE SIS_AJUSTEXPROCESO
ADD CONSTRAINT SIS_AJUSTXPROC_TIPOPROCESO_FK FOREIGN KEY
(
ID_TIPOPROCESO
)
REFERENCES SIS_TIPO_PROCESO
(
ID_TIPOPROCESO
) ENABLE
;

ALTER TABLE SIS_FORMA_PAGO
ADD CONSTRAINT SIS_FORMAPAGO_TIPODOCUMENTO_FK FOREIGN KEY
(
ID_TIPO_DOCUMENTO
)
REFERENCES SIS_TIPO_DOCUMENTO
(
ID_TIPO_DOCUMENTO
) ENABLE
;

ALTER TABLE SIS_FORMA_PAGO
ADD CONSTRAINT SIS_FORMAPAGO_BANCO_FK FOREIGN KEY
(
ID_BANCO
)
REFERENCES SIS_BANCO
(
ID_BANCO
) ENABLE
;

ALTER TABLE SIS_FORMA_PAGO
ADD CONSTRAINT SIS_FORMAPAGO_MONEDA_FK FOREIGN KEY
(
ID_MONEDA
)
REFERENCES SIS_MONEDA
(
ID_MONEDA
) ENABLE
;

ALTER TABLE SIS_FORMA_PAGO
ADD CONSTRAINT SIS_FORMAPAGO_CUENTA_FK FOREIGN KEY
(
ID_CUENTA
)
REFERENCES SIS_CUENTA
(
ID_CUENTA
) ENABLE
;

ALTER TABLE SIS_FORMA_PAGO
ADD CONSTRAINT SIS_FORMAPAGO_CONTRATO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_CONTRATO
(
ID_CONTRATO
) ENABLE
;

ALTER TABLE SIS_HISTORICO_EST_CONTRATO
ADD CONSTRAINT SIS_HISTORICOEST_CONTRATO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_CONTRATO
(
ID_CONTRATO
) ENABLE
;

ALTER TABLE SIS_HISTORICO_EST_CONTRATO
ADD CONSTRAINT SIS_HISTORICOEST_ESTADO_FK FOREIGN KEY
(
ID_ESTADO
)
REFERENCES SIS_ESTADO
(
ID_ESTADO
) ENABLE
;

ALTER TABLE SIS_DET_TIEMPO_EXTRA
ADD CONSTRAINT SIS_DET_TIEMPOX_TIEMPOX_FK FOREIGN KEY
(
ID_TIEMPO_EXTRAORDINARIO
)
REFERENCES SIS_TIEMPO_EXTRAORDINARIO
(
ID_TIEMPO_EXTRAORDINARIO
) ENABLE
;

ALTER TABLE SIS_DET_LICENCIA
ADD CONSTRAINT DETLICENCIA_SOLICITUD_FK FOREIGN KEY
(
ID_SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_HISTORICO_SUELDO
ADD CONSTRAINT SIS_HIST_SUELDO_VARIACION_FK FOREIGN KEY
(
ID_VARIACION_SUELDO
)
REFERENCES SIS_VARIACION_SUELDO
(
ID_VARIACION_SUELDO
) ENABLE
;

ALTER TABLE SIS_HISTORICO_SUELDO
ADD CONSTRAINT SIS_HIST_SUELDO_CONTRATO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_CONTRATO
(
ID_CONTRATO
) ENABLE
;

ALTER TABLE SIS_NOMINA
ADD CONSTRAINT SIS_NOMINA_TIPO_NOMINA_FK FOREIGN KEY
(
ID_TIPO_NOMINA
)
REFERENCES SIS_TIPO_NOMINA
(
ID_TIPO_NOMINA
) ENABLE
;

ALTER TABLE SIS_NOMINA
ADD CONSTRAINT SIS_NOMINA_CONTRATO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_CONTRATO
(
ID_CONTRATO
) ENABLE
;

ALTER TABLE SIS_NOMINA
ADD CONSTRAINT SIS_NOMINA_PARTIDA_FK FOREIGN KEY
(
ID_PARTIDA
)
REFERENCES SIS_PARTIDA
(
ID_PARTIDA
) ENABLE
;

ALTER TABLE SIS_NOMINA
ADD CONSTRAINT SIS_NOMINA_PROCESO_FK FOREIGN KEY
(
ID_PROCESO
)
REFERENCES SIS_PROCESO
(
ID_PROCESO
) ENABLE
;

ALTER TABLE SIS_DIRECCION
ADD CONSTRAINT SIS_DIRECCION_SIS_MUNICIPIO_FK FOREIGN KEY
(
ID_MUNICIPIO
)
REFERENCES SIS_MUNICIPIO
(
ID_MUNICIPIO
) ENABLE
;

ALTER TABLE SIS_DIRECCION
ADD CONSTRAINT SIS_DIRECCION_EMPLEADO_FK FOREIGN KEY
(
REGISTRO_EMPLEADO
)
REFERENCES SIS_EMPLEADO
(
REGISTRO_EMPLEADO
) ENABLE
;

ALTER TABLE SIS_COMPLEMENTO_IGSS
ADD CONSTRAINT SIS_COMPLEMNT_IGSS_SUS_IGSS_FK FOREIGN KEY
(
ID_SUSPENCION_IGSS
)
REFERENCES SIS_SUSPENCION_IGSS
(
ID_SUSPENCION_IGSS
) ENABLE
;

ALTER TABLE SIS_COMPLEMENTO_IGSS
ADD CONSTRAINT SIS_COMPLEMNT_IGSS_PROCESO_FK FOREIGN KEY
(
ID_PROCESO
)
REFERENCES SIS_PROCESO
(
ID_PROCESO
) ENABLE
;

ALTER TABLE SIS_SUSPENCION_IGSS
ADD CONSTRAINT SIS_SUSPENCION_IGSS_FK FOREIGN KEY
(
SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_PAGO
ADD CONSTRAINT SIS_PAGO_NOMINA_FK FOREIGN KEY
(
ID_NOMINA
)
REFERENCES SIS_NOMINA
(
ID_NOMINA
) ENABLE
;

ALTER TABLE SIS_PAGO
ADD CONSTRAINT SIS_PAGO_DOC_BANCO_FK FOREIGN KEY
(
ID_DOCUMENTO_BANCO
)
REFERENCES SIS_DOCUMENTO_BANCO
(
ID_DOCUMENTO_BANCO
) ENABLE
;

ALTER TABLE SIS_PAGO
ADD CONSTRAINT SIS_PAGO_PROCESO_FK FOREIGN KEY
(
ID_PROCESO
)
REFERENCES SIS_PROCESO
(
ID_PROCESO
) ENABLE
;

ALTER TABLE SIS_PAGO
ADD CONSTRAINT SIS_PAGO_COMPL_IGSSFK FOREIGN KEY
(
ID_COMPLEMENTO_IGSS
)
REFERENCES SIS_COMPLEMENTO_IGSS
(
ID_COMPLEMENTO_IGSS
) ENABLE
;

ALTER TABLE SIS_DET_CHEQUE_ANULADO
ADD CONSTRAINT SIS_DET_CHEQUE_ANULADO_FK FOREIGN KEY
(
ID_CHEQUE_ANULADO
)
REFERENCES SIS_CHEQUE_ANULADO
(
ID_CHEQUE_ANULADO
) ENABLE
;

ALTER TABLE SIS_CHEQUE_ANULADO
ADD CONSTRAINT SIS_CHEQUE_ANUL_MOTIVO_FK FOREIGN KEY
(
ID_MOTIVO_ANULACION
)
REFERENCES SIS_MOTIVO_ANULACION
(
ID_MOTIVO_ANULACION
) ENABLE
;

ALTER TABLE SIS_CHEQUE_ANULADO
ADD CONSTRAINT SIS_CHEQUE_ANU_TIPONOM_FK FOREIGN KEY
(
ID_TIPO_NOMINA
)
REFERENCES SIS_TIPO_NOMINA
(
ID_TIPO_NOMINA
) ENABLE
;

ALTER TABLE SIS_CARGA_ARCHIVO_DATOS
ADD CONSTRAINT SIS_CARGA_ARCHIVO_DATOS_FK FOREIGN KEY
(
ID_ORIGEN_CARGA_ARCHIVO
)
REFERENCES SIS_ORIGEN_CARGA_ARCHIVO
(
ID_ORIGEN_CARGA_ARCHIVO
) ENABLE
;

ALTER TABLE SIS_ARCHIVO_APERTURA
ADD CONSTRAINT SIS_ARCH_APERT_ARCH_DATOS_FK FOREIGN KEY
(
ID_CARGA_ARCHIVO_DATOS
)
REFERENCES SIS_CARGA_ARCHIVO_DATOS
(
ID_CARGA_ARCHIVO_DATOS
) ENABLE
;

ALTER TABLE SIS_ARCHIVO_ADJUNTO
ADD CONSTRAINT SIS_ARCH_ADJ_CONTRATO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_CONTRATO
(
ID_CONTRATO
) ENABLE
;

ALTER TABLE SIS_ARCHIVO_ADJUNTO
ADD CONSTRAINT SIS_ARCH_ADJ_SOLICITUD_FK FOREIGN KEY
(
ID_SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_ARCHIVO_ADJUNTO
ADD CONSTRAINT SIS_ARCH_ADJ_TIP_ARCH_FK FOREIGN KEY
(
ID_TIPO_ARCHIVO
)
REFERENCES SIS_TIPO_ARCHIVO
(
ID_TIPO_ARCHIVO
) ENABLE
;

ALTER TABLE SIS_VARIACION_NOMINA
ADD CONSTRAINT SIS_VAR_NOMINA_CONTRATO_FK FOREIGN KEY
(
ID_CONTRATO
)
REFERENCES SIS_CONTRATO
(
ID_CONTRATO
) ENABLE
;

ALTER TABLE SIS_VARIACION_DET_AJUSTE
ADD CONSTRAINT SIS_VAR_DET_AJUSTE_AJUSTE_FK FOREIGN KEY
(
ID_AJUSTE
)
REFERENCES SIS_AJUSTE
(
ID_AJUSTE
) ENABLE
;

ALTER TABLE SIS_VARIACION_DET_AJUSTE
ADD CONSTRAINT SIS_VAR_DET_AJUSTE_VAR_NOM_FK FOREIGN KEY
(
ID_VARIACION_NOMINA
)
REFERENCES SIS_VARIACION_NOMINA
(
ID_VARIACION_NOMINA
) ENABLE
;

ALTER TABLE SIS_VARIACION_DET_AJUSTE
ADD CONSTRAINT SIS_VAR_DET_AJUSTE_ESTADO_FK FOREIGN KEY
(
ID_ESTADO
)
REFERENCES SIS_ESTADO
(
ID_ESTADO
) ENABLE
;

ALTER TABLE SIS_ARCHIVO_PRESTAMO
ADD CONSTRAINT SIS_ARCH_PREST_CARGA_ARCH_FK FOREIGN KEY
(
ID_CARGA_ARCHIVO_DATOS
)
REFERENCES SIS_CARGA_ARCHIVO_DATOS
(
ID_CARGA_ARCHIVO_DATOS
) ENABLE
;

ALTER TABLE SIS_ASIGNACION_NUM_CHEQUE
ADD CONSTRAINT SIS_ASIG_NUM_CHEQUE_BANCO_FK FOREIGN KEY
(
ID_BANCO
)
REFERENCES SIS_BANCO
(
ID_BANCO
) ENABLE
;

ALTER TABLE SIS_DET_ASIG_CHEQUE
ADD CONSTRAINT SIS_DET_ASIG_CHEQUE_FK FOREIGN KEY
(
ID_ASIGNACION_NUM_CHEQUE
)
REFERENCES SIS_ASIGNACION_NUM_CHEQUE
(
ID_ASIGNACION_NUM_CHEQUE
) ENABLE
;

ALTER TABLE SIS_DET_CHEQUES
ADD CONSTRAINT SIS_DET_CHEQUES_FK FOREIGN KEY
(
ID_ACTA_FACSIMIL
)
REFERENCES SIS_ACTA_FACSIMIL
(
ID_ACTA_FACSIMIL
) ENABLE
;

ALTER TABLE SIS_COMISION_FACSIMIL
ADD CONSTRAINT SIS_COM_FACSIMIL_EMPLEADO_FK FOREIGN KEY
(
REGISTRO_EMPLEADO
)
REFERENCES SIS_EMPLEADO
(
REGISTRO_EMPLEADO
) ENABLE
;

ALTER TABLE SIS_COMISION_FACSIMIL
ADD CONSTRAINT SIS_COM_FACSIMIL_ACTA_FK FOREIGN KEY
(
ID_ACTA_FACSIMIL
)
REFERENCES SIS_ACTA_FACSIMIL
(
ID_ACTA_FACSIMIL
) ENABLE
;

ALTER TABLE SIS_TIEMPO_EXTRAORDINARIO
ADD CONSTRAINT SIS_TIEMPO_EXTRA_SOLICITUD_FK FOREIGN KEY
(
ID_SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_DESCUENTO_TIEMPO_EXTRA
ADD CONSTRAINT SIS_DESC_TIEMPOX_AJUSTE_FK FOREIGN KEY
(
ID_AJUSTE
)
REFERENCES SIS_AJUSTE
(
ID_AJUSTE
) ENABLE
;

ALTER TABLE SIS_DESCUENTO_TIEMPO_EXTRA
ADD CONSTRAINT SIS_DESC_TIEMPOX_TIEMPOX_FK FOREIGN KEY
(
ID_TIEMPO_EXTRAORDINARIO
)
REFERENCES SIS_TIEMPO_EXTRAORDINARIO
(
ID_TIEMPO_EXTRAORDINARIO
) ENABLE
;

ALTER TABLE SIS_COMPLEMENTO
ADD CONSTRAINT SIS_COMP_SOLICITUD_FK FOREIGN KEY
(
ID_SOLICITUD
)
REFERENCES SIS_SOLICITUD
(
ID_SOLICITUD
) ENABLE
;

ALTER TABLE SIS_HISTORICO_CARGA_ARCHIVO
ADD CONSTRAINT SIS_HIST_CARGA_ARCHIVO_FK FOREIGN KEY
(
ID_CARGA_ARCHIVO_DATOS
)
REFERENCES SIS_CARGA_ARCHIVO_DATOS
(
ID_CARGA_ARCHIVO_DATOS
) ENABLE
;

ALTER TABLE SIS_HISTORICO_CARGA_ARCHIVO
ADD CONSTRAINT SIS_HIST_CARGA_PROCESO_FK FOREIGN KEY
(
ID_PROCESO
)
REFERENCES SIS_PROCESO
(
ID_PROCESO
) ENABLE
;

ALTER TABLE SIS_USUARIO_PERFIL
ADD CONSTRAINT SIS_USUARIOPER_PERFIL_FK FOREIGN KEY
(
ID_PERFIL
)
REFERENCES SIS_PERFIL
(
ID_PERFIL
) ENABLE
;

ALTER TABLE SIS_USUARIO_PERFIL
ADD CONSTRAINT SIS_USUARIOPER_USUARIO_FK FOREIGN KEY
(
ID_USUARIO
)
REFERENCES SIS_USUARIO
(
ID_USUARIO
) ENABLE
;

