CREATE TABLE SIS_HISTORICO_PUESTO
(
ID_PUESTO NUMBER(7, 0) NOT NULL,
ESCALAMIN NUMBER(12, 2) NOT NULL,
ESCALAMAX NUMBER(12, 2) NOT NULL,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE
)
;

ALTER TABLE SIS_HISTORICO_PUESTO
ADD CONSTRAINT SIS_HIST_PUESTO_PK PRIMARY KEY
(
ID_PUESTO,
FECHA_INICIO
)
 ENABLE
;

ALTER TABLE SIS_HISTORICO_PUESTO
ADD CONSTRAINT SIS_HIST_PUESTO_SIS_PUESTO_FK FOREIGN KEY
(
ID_PUESTO
)
REFERENCES SIS_PUESTO
(
ID_PUESTO
) ENABLE
;

