package enlace_datos.entidades.gestiones.indemnizaciones;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisTipoIndemnizacionImpl extends EntityImpl {
    public static final int IDTIPOINDEMNIZACION = 0;
    public static final int NOMBRE = 1;
    public static final int DESCRIPCION = 2;
    public static final int SISINDEMNIZACION = 3;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisTipoIndemnizacionImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.gestiones.indemnizaciones.SisTipoIndemnizacion");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdTipoIndemnizacion, using the alias name IdTipoIndemnizacion
     */
    public Number getIdTipoIndemnizacion() {
        return (Number)getAttributeInternal(IDTIPOINDEMNIZACION);
    }

    /**Sets <code>value</code> as the attribute value for IdTipoIndemnizacion
     */
    public void setIdTipoIndemnizacion(Number value) {
        setAttributeInternal(IDTIPOINDEMNIZACION, value);
    }

    /**Gets the attribute value for Nombre, using the alias name Nombre
     */
    public String getNombre() {
        return (String)getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Gets the attribute value for Descripcion, using the alias name Descripcion
     */
    public String getDescripcion() {
        return (String)getAttributeInternal(DESCRIPCION);
    }

    /**Sets <code>value</code> as the attribute value for Descripcion
     */
    public void setDescripcion(String value) {
        setAttributeInternal(DESCRIPCION, value);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDTIPOINDEMNIZACION:
            return getIdTipoIndemnizacion();
        case NOMBRE:
            return getNombre();
        case DESCRIPCION:
            return getDescripcion();
        case SISINDEMNIZACION:
            return getSisIndemnizacion();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDTIPOINDEMNIZACION:
            setIdTipoIndemnizacion((Number)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        case DESCRIPCION:
            setDescripcion((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getSisIndemnizacion() {
        return (RowIterator)getAttributeInternal(SISINDEMNIZACION);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idTipoIndemnizacion) {
        return new Key(new Object[]{idTipoIndemnizacion});
    }
}
