package enlace_datos.consultas.reportes;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class rpt_liquidacionImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public rpt_liquidacionImpl() {
    }

    /**Gets the bind variable value for usuario
     */
    public String getusuario() {
        return (String)getNamedWhereClauseParam("usuario");
    }

    /**Sets <code>value</code> for bind variable usuario
     */
    public void setusuario(String value) {
        setNamedWhereClauseParam("usuario", value);
    }

    /**Gets the bind variable value for idLiqui
     */
    public Number getidLiqui() {
        return (Number)getNamedWhereClauseParam("idLiqui");
    }

    /**Sets <code>value</code> for bind variable idLiqui
     */
    public void setidLiqui(Number value) {
        setNamedWhereClauseParam("idLiqui", value);
    }
}
