package enlace_datos.consultas.reportes;


import enlace_datos.consultas.reportes.common.SisDetProcesos;

import enlace_datos.util.utils;
import enlace_datos.util.utils_DB;

import oracle.jbo.JboException;
import oracle.jbo.NameValuePairs;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisDetProcesosImpl extends ViewObjectImpl implements SisDetProcesos {
    /**This is the default constructor (do not remove)
     */
    public SisDetProcesosImpl() {
    }

    /**Gets the bind variable value for fechaI
     */
    public Date getfechaI() {
        return (Date)getNamedWhereClauseParam("fechaI");
    }

    /**Sets <code>value</code> for bind variable fechaI
     */
    public void setfechaI(Date value) {
        setNamedWhereClauseParam("fechaI", value);
    }

    /**Gets the bind variable value for fechaF
     */
    public Date getfechaF() {
        return (Date)getNamedWhereClauseParam("fechaF");
    }

    /**Sets <code>value</code> for bind variable fechaF
     */
    public void setfechaF(Date value) {
        setNamedWhereClauseParam("fechaF", value);
    }
    
   public void generarSis24(Number pIdProceso,String vDesc,String pUsuario)
   {
       
       NameValuePairs vParametros;
       vParametros=new NameValuePairs();
       vParametros.setAttribute("1",pIdProceso);
       vParametros.setAttribute("2",vDesc);
       vParametros.setAttribute("3",pUsuario);   
       if (utils_DB.ejecutarProcedimiento(this.getDBTransaction(),"sis_util_report_pkg.CREAR_SISFORM24(?,?,?)",vParametros))
       {
           this.getDBTransaction().commit();   
           
       }else
       {
           
           this.getDBTransaction().rollback();
           throw new JboException("Ha ocurrido un error, por favor verifique.");
       }
       
   }


    /**Gets the bind variable value for pUsuario
     */
    public String getpUsuario() {
        return (String)getNamedWhereClauseParam("pUsuario");
    }

    /**Sets <code>value</code> for bind variable pUsuario
     */
    public void setpUsuario(String value) {
        setNamedWhereClauseParam("pUsuario", value);
    }


    /**Gets the bind variable value for pDep
     */
    public Number getpDep() {
        return (Number)getNamedWhereClauseParam("pDep");
    }

    /**Sets <code>value</code> for bind variable pDep
     */
    public void setpDep(Number value) {
        setNamedWhereClauseParam("pDep", value);
    }
}
