package enlace_datos.consultas.reportes;

import enlace_datos.consultas.reportes.common.SisProcesosNominaVw;

import enlace_datos.util.utils;

import enlace_datos.util.utils_DB;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisProcesosNominaVwImpl extends ViewObjectImpl implements SisProcesosNominaVw {
    /**This is the default constructor (do not remove)
     */
    public SisProcesosNominaVwImpl() {
    }

    /**Gets the bind variable value for pFechaI
     */
    public Date getpFechaI() {
        return (Date)getNamedWhereClauseParam("pFechaI");
    }

    /**Sets <code>value</code> for bind variable pFechaI
     */
    public void setpFechaI(Date value) {
        setNamedWhereClauseParam("pFechaI", value);
    }

    /**Gets the bind variable value for pFechaF
     */
    public Date getpFechaF() {
        return (Date)getNamedWhereClauseParam("pFechaF");
    }

    /**Sets <code>value</code> for bind variable pFechaF
     */
    public void setpFechaF(Date value) {
        setNamedWhereClauseParam("pFechaF", value);
    }
    
    
    public void filtrarSinDevISR()
    {
        this.setWhereClause("nombre <>'DEVOLUCION ISR'");
        this.setpUsuario(utils.getAuthUser(this.getDBTransaction()));
        this.executeQuery();
    }
    
    
    public void quitarFiltros()
    {
        
        this.setWhereClause("");
        
    }
    
    public void filtrarTesos(Date pFechaI,Date pFechaF,String pUsuario){
      Date vFechaTemp;
      Object vValor;
      
    //  vFechaTemp=new Date(new java.sql.Timestamp(System.currentTimeMillis()+(30*24*60*60*1000)));      
      
      
      if (pFechaI==null) {
      
          vValor=utils_DB.getEjecutarQuerry(this.getDBTransaction(),"select to_char(sysdate-30,'dd/mm/yyyy') from dual");
          vFechaTemp=utils.getFechaOracle(vValor.toString());
          this.setpFechaI(vFechaTemp);    
          
      }else{
          this.setpFechaI(pFechaI);    
      }
      
      this.setpFechaF(pFechaF);
      this.setpUsuario(pUsuario);
      this.setWhereClause("numDetNomina>0 and nombre <>'DEVOLUCION ISR'");  
      this.executeQuery();
     // System.out.println(this.getQuery());
      
    }

    /**Gets the bind variable value for pUsuario
     */
    public String getpUsuario() {
        return (String)getNamedWhereClauseParam("pUsuario");
    }

    /**Sets <code>value</code> for bind variable pUsuario
     */
    public void setpUsuario(String value) {
        setNamedWhereClauseParam("pUsuario", value);
    }
}
