package enlace_datos.consultas.procesos.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class modificar_nominavoRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "IdPuesto_FMT_FORMAT", "0" },
{ "pDependencia_LABEL", "Dependencia" },
{ "pRegPer_LABEL", "Registro personal" },
{ "IdPuesto_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
{ "pIdProceso_LABEL", "Proceso" }};

    /**This is the default constructor (do not remove)
     */
    public modificar_nominavoRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
