package enlace_datos.consultas.procesos.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class prestamo_banco_VwRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "IdCargaArchivoDatos_LABEL", "Identificador" },
{ "NomArchivo_LABEL", "Archivo" },
{ "fechaF_FMT_FORMAT", "dd/MM/yyyy" },
{ "fechaI_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "fechaF_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "FechaFin_FMT_FORMAT", "dd/MM/yyyy HH:mm" },
{ "Nombre_LABEL", "Banco" },
{ "fechaI_FMT_FORMAT", "dd/MM/yyyy" },
{ "FechaFin_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "FechaInicio_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "FechaInicio_FMT_FORMAT", "dd/MM/yyyy HH:mm" }};

    /**This is the default constructor (do not remove)
     */
    public prestamo_banco_VwRowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
