package enlace_datos.consultas.procesos.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface SisProcesoConciliacionVw extends ViewObject {
    void crear_nuevo_det(String pUsuario);

    void procesar_conciliacion(Number pIdConciliacion);

    void dar_visto_bueno(Number pIdConciliacion);
}
