package enlace_datos.consultas.procesos.client;

import enlace_datos.consultas.procesos.common.complementos_isr_vw;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class complementos_isr_vwClient extends ViewUsageImpl implements complementos_isr_vw {
    /**This is the default constructor (do not remove)
     */
    public complementos_isr_vwClient() {
    }

    public void proc_aplicar_isr(Number idProceso) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"proc_aplicar_isr",new String [] {"oracle.jbo.domain.Number"},new Object[] {idProceso});
        return;
    }

    public void aplicar_isr(Number pIdProceso, Number pAnio) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"aplicar_isr",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number"},new Object[] {pIdProceso, pAnio});
        return;
    }
}
