package enlace_datos.consultas.gestiones.empleado;

import enlace_datos.entidades.gestiones.empleado.SisHorarioDecJuradaImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisHorarioDecJuradaVwRowImpl extends ViewRowImpl {
    public static final int REGISTROEMPLEADO = 0;
    public static final int TIPODECLARACION = 1;
    public static final int ANIO = 2;
    public static final int ORDEN = 3;
    public static final int IDDIA = 4;
    public static final int HORAINICIO = 5;
    public static final int HORAFIN = 6;
    public static final int CREADOPOR = 7;
    public static final int FECHACREACION = 8;
    public static final int MODIFICADOPOR = 9;
    public static final int FECHAMODIFICACION = 10;
    public static final int HORAINICIO2 = 11;
    public static final int HORAFIN2 = 12;
    public static final int NOMBREDIA = 13;
    public static final int NUMHORAS = 14;
    public static final int SELECTED = 15;
    public static final int OBSERVACIONES = 16;
    public static final int DIAALTERNO = 17;
    private boolean isSelected=false;

    /**This is the default constructor (do not remove)
     */
    public SisHorarioDecJuradaVwRowImpl() {
    }

    /**Gets SisHorarioDecJurada entity object.
     */
    public SisHorarioDecJuradaImpl getSisHorarioDecJurada() {
        return (SisHorarioDecJuradaImpl)getEntity(0);
    }

    /**Gets the attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for TIPO_DECLARACION using the alias name TipoDeclaracion
     */
    public String getTipoDeclaracion() {
        return (String) getAttributeInternal(TIPODECLARACION);
    }

    /**Sets <code>value</code> as attribute value for TIPO_DECLARACION using the alias name TipoDeclaracion
     */
    public void setTipoDeclaracion(String value) {
        setAttributeInternal(TIPODECLARACION, value);
    }

    /**Gets the attribute value for ANIO using the alias name Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as attribute value for ANIO using the alias name Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for ORDEN using the alias name Orden
     */
    public Number getOrden() {
        return (Number) getAttributeInternal(ORDEN);
    }

    /**Sets <code>value</code> as attribute value for ORDEN using the alias name Orden
     */
    public void setOrden(Number value) {
        setAttributeInternal(ORDEN, value);
    }

    /**Gets the attribute value for ID_DIA using the alias name IdDia
     */
    public String getIdDia() {
        return (String) getAttributeInternal(IDDIA);
    }

    /**Sets <code>value</code> as attribute value for ID_DIA using the alias name IdDia
     */
    public void setIdDia(String value) {
        setAttributeInternal(IDDIA, value);
    }

    /**Gets the attribute value for HORA_INICIO using the alias name HoraInicio
     */
    public String getHoraInicio() {
        return (String) getAttributeInternal(HORAINICIO);
    }

    /**Sets <code>value</code> as attribute value for HORA_INICIO using the alias name HoraInicio
     */
    public void setHoraInicio(String value) {
        setAttributeInternal(HORAINICIO, value);
    }

    /**Gets the attribute value for HORA_FIN using the alias name HoraFin
     */
    public String getHoraFin() {
        return (String) getAttributeInternal(HORAFIN);
    }

    /**Sets <code>value</code> as attribute value for HORA_FIN using the alias name HoraFin
     */
    public void setHoraFin(String value) {
        setAttributeInternal(HORAFIN, value);
    }

    /**Gets the attribute value for CREADO_POR using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String) getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as attribute value for CREADO_POR using the alias name CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for MODIFICADO_POR using the alias name ModificadoPor
     */
    public String getModificadoPor() {
        return (String) getAttributeInternal(MODIFICADOPOR);
    }

    /**Sets <code>value</code> as attribute value for MODIFICADO_POR using the alias name ModificadoPor
     */
    public void setModificadoPor(String value) {
        setAttributeInternal(MODIFICADOPOR, value);
    }

    /**Gets the attribute value for FECHA_MODIFICACION using the alias name FechaModificacion
     */
    public Date getFechaModificacion() {
        return (Date) getAttributeInternal(FECHAMODIFICACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_MODIFICACION using the alias name FechaModificacion
     */
    public void setFechaModificacion(Date value) {
        setAttributeInternal(FECHAMODIFICACION, value);
    }

    /**Gets the attribute value for HORAINICIO2 using the alias name HoraInicio2
     */
    public String getHoraInicio2() {
        return (String) getAttributeInternal(HORAINICIO2);
    }

    /**Sets <code>value</code> as attribute value for HORAINICIO2 using the alias name HoraInicio2
     */
    public void setHoraInicio2(String value) {
        setAttributeInternal(HORAINICIO2, value);
    }

    /**Gets the attribute value for HORAFIN2 using the alias name HoraFin2
     */
    public String getHoraFin2() {
        return (String) getAttributeInternal(HORAFIN2);
    }

    /**Sets <code>value</code> as attribute value for HORAFIN2 using the alias name HoraFin2
     */
    public void setHoraFin2(String value) {
        setAttributeInternal(HORAFIN2, value);
    }

    /**Gets the attribute value for NOMBREDIA using the alias name NombreDia
     */
    public String getNombreDia() {
        return (String) getAttributeInternal(NOMBREDIA);
    }

    /**Sets <code>value</code> as attribute value for NOMBREDIA using the alias name NombreDia
     */
    public void setNombreDia(String value) {
        setAttributeInternal(NOMBREDIA, value);
    }

    /**Gets the attribute value for NUM_HORAS using the alias name NumHoras
     */
    public Number getNumHoras() {
        return (Number) getAttributeInternal(NUMHORAS);
    }

    /**Sets <code>value</code> as attribute value for NUM_HORAS using the alias name NumHoras
     */
    public void setNumHoras(Number value) {
        setAttributeInternal(NUMHORAS, value);
    }

    /**Gets the attribute value for the calculated attribute Selected
     */
    public Boolean getSelected() {
        return isSelected;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Selected
     */
    public void setSelected(Boolean value) {
        isSelected=value;        
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case TIPODECLARACION:
            return getTipoDeclaracion();
        case ANIO:
            return getAnio();
        case ORDEN:
            return getOrden();
        case IDDIA:
            return getIdDia();
        case HORAINICIO:
            return getHoraInicio();
        case HORAFIN:
            return getHoraFin();
        case CREADOPOR:
            return getCreadoPor();
        case FECHACREACION:
            return getFechaCreacion();
        case MODIFICADOPOR:
            return getModificadoPor();
        case FECHAMODIFICACION:
            return getFechaModificacion();
        case HORAINICIO2:
            return getHoraInicio2();
        case HORAFIN2:
            return getHoraFin2();
        case NOMBREDIA:
            return getNombreDia();
        case NUMHORAS:
            return getNumHoras();
        case SELECTED:
            return getSelected();
        case OBSERVACIONES:
            return getObservaciones();
        case DIAALTERNO:
            return getDiaAlterno();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            setRegistroEmpleado((Number)value);
            return;
        case TIPODECLARACION:
            setTipoDeclaracion((String)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case ORDEN:
            setOrden((Number)value);
            return;
        case IDDIA:
            setIdDia((String)value);
            return;
        case HORAINICIO:
            setHoraInicio((String)value);
            return;
        case HORAFIN:
            setHoraFin((String)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case MODIFICADOPOR:
            setModificadoPor((String)value);
            return;
        case FECHAMODIFICACION:
            setFechaModificacion((Date)value);
            return;
        case HORAINICIO2:
            setHoraInicio2((String)value);
            return;
        case HORAFIN2:
            setHoraFin2((String)value);
            return;
        case NOMBREDIA:
            setNombreDia((String)value);
            return;
        case NUMHORAS:
            setNumHoras((Number)value);
            return;
        case SELECTED:
            setSelected((Boolean)value);
            return;
        case OBSERVACIONES:
            setObservaciones((String)value);
            return;
        case DIAALTERNO:
            setDiaAlterno((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for OBSERVACIONES using the alias name Observaciones
     */
    public String getObservaciones() {
        return (String) getAttributeInternal(OBSERVACIONES);
    }

    /**Sets <code>value</code> as attribute value for OBSERVACIONES using the alias name Observaciones
     */
    public void setObservaciones(String value) {
        setAttributeInternal(OBSERVACIONES, value);
    }

    /**Gets the attribute value for DIA_ALTERNO using the alias name DiaAlterno
     */
    public Number getDiaAlterno() {
        return (Number) getAttributeInternal(DIAALTERNO);
    }

    /**Sets <code>value</code> as attribute value for DIA_ALTERNO using the alias name DiaAlterno
     */
    public void setDiaAlterno(Number value) {
        setAttributeInternal(DIAALTERNO, value);
    }
}
