package enlace_datos.consultas.gestiones.contrato;

import enlace_datos.consultas.gestiones.contrato.common.SisHistActaHorarioContratoVwRow;

import enlace_datos.entidades.gestiones.contrato.SisHistActaHorarioContratoImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisHistActaHorarioContratoVwRowImpl extends ViewRowImpl implements SisHistActaHorarioContratoVwRow {
    public static final int IDCONTRATO = 0;
    public static final int TIPOACTUALIZACION = 1;
    public static final int NUMEROACTA = 2;
    public static final int OBSERVACIONES = 3;
    public static final int IDHISTACTAHORACONTRATO = 4;
    public static final int CREADOPOR = 5;

    /**This is the default constructor (do not remove)
     */
    public SisHistActaHorarioContratoVwRowImpl() {
    }

    /**Gets SisHistActaHorarioContrato entity object.
     */
    public SisHistActaHorarioContratoImpl getSisHistActaHorarioContrato() {
        return (SisHistActaHorarioContratoImpl)getEntity(0);
    }

    /**Gets the attribute value for ID_HIST_ACTAHORACONTRATO using the alias name IdHistActahoracontrato
     */
    public Number getIdHistActahoracontrato() {
        return (Number) getAttributeInternal(IDHISTACTAHORACONTRATO);
    }

    /**Sets <code>value</code> as attribute value for ID_HIST_ACTAHORACONTRATO using the alias name IdHistActahoracontrato
     */
    public void setIdHistActahoracontrato(Number value) {
        setAttributeInternal(IDHISTACTAHORACONTRATO, value);
    }

    /**Gets the attribute value for ID_CONTRATO using the alias name IdContrato
     */
    public Number getIdContrato() {
        return (Number) getAttributeInternal(IDCONTRATO);
    }

    /**Sets <code>value</code> as attribute value for ID_CONTRATO using the alias name IdContrato
     */
    public void setIdContrato(Number value) {
        setAttributeInternal(IDCONTRATO, value);
    }

    /**Gets the attribute value for TIPO_ACTUALIZACION using the alias name TipoActualizacion
     */
    public Number getTipoActualizacion() {
        return (Number) getAttributeInternal(TIPOACTUALIZACION);
    }

    /**Sets <code>value</code> as attribute value for TIPO_ACTUALIZACION using the alias name TipoActualizacion
     */
    public void setTipoActualizacion(Number value) {
        setAttributeInternal(TIPOACTUALIZACION, value);
    }

    /**Gets the attribute value for NUMERO_ACTA using the alias name NumeroActa
     */
    public String getNumeroActa() {
        return (String) getAttributeInternal(NUMEROACTA);
    }

    /**Sets <code>value</code> as attribute value for NUMERO_ACTA using the alias name NumeroActa
     */
    public void setNumeroActa(String value) {
        setAttributeInternal(NUMEROACTA, value);
    }

    /**Gets the attribute value for OBSERVACIONES using the alias name Observaciones
     */
    public String getObservaciones() {
        return (String) getAttributeInternal(OBSERVACIONES);
    }

    /**Sets <code>value</code> as attribute value for OBSERVACIONES using the alias name Observaciones
     */
    public void setObservaciones(String value) {
        setAttributeInternal(OBSERVACIONES, value);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDCONTRATO:
            return getIdContrato();
        case TIPOACTUALIZACION:
            return getTipoActualizacion();
        case NUMEROACTA:
            return getNumeroActa();
        case OBSERVACIONES:
            return getObservaciones();
        case IDHISTACTAHORACONTRATO:
            return getIdHistActahoracontrato();
        case CREADOPOR:
            return getCreadoPor();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDCONTRATO:
            setIdContrato((Number)value);
            return;
        case TIPOACTUALIZACION:
            setTipoActualizacion((Number)value);
            return;
        case NUMEROACTA:
            setNumeroActa((String)value);
            return;
        case OBSERVACIONES:
            setObservaciones((String)value);
            return;
        case IDHISTACTAHORACONTRATO:
            setIdHistActahoracontrato((Number)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for CREADO_POR using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String) getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as attribute value for CREADO_POR using the alias name CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }
}
