package enlace_datos.consultas.mensajes.client;

import enlace_datos.consultas.mensajes.common.SisMensajesRelacionadosVw;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisMensajesRelacionadosVwClient extends ViewUsageImpl implements SisMensajesRelacionadosVw {
    /**This is the default constructor (do not remove)
     */
    public SisMensajesRelacionadosVwClient() {
    }

    public String getMensajes() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getMensajes",null,null);
        return (String)_ret;
    }
}
