package enlace_datos.consultas.gestiones.contrato.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface SisUnidadesEjecutoras_Id_vw extends ViewObject {
    void QuitarFiltro();

    void filtrar_x_acceso(String pUsuario);

    void filtrar_x_acceso_dep45(Number pDependencia, String pUsuario);
}
