package enlace_datos.consultas.gestiones.empleado;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Sis_descuentos_empleadoRowImpl extends ViewRowImpl {
    public static final int REGISTROEMPLEADO = 0;
    public static final int IDAJUSTE = 1;
    public static final int IDCORRELATIVO = 2;
    public static final int REMOVIBLE = 3;
    public static final int MODIFICABLE = 4;
    public static final int NIVEL = 5;
    public static final int RENUNCIA = 6;
    public static final int NOMBRE = 7;

    /**This is the default constructor (do not remove)
     */
    public Sis_descuentos_empleadoRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for the calculated attribute IdAjuste
     */
    public Number getIdAjuste() {
        return (Number) getAttributeInternal(IDAJUSTE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdAjuste
     */
    public void setIdAjuste(Number value) {
        setAttributeInternal(IDAJUSTE, value);
    }

    /**Gets the attribute value for the calculated attribute Removible
     */
    public String getRemovible() {
        return (String) getAttributeInternal(REMOVIBLE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Removible
     */
    public void setRemovible(String value) {
        setAttributeInternal(REMOVIBLE, value);
    }

    /**Gets the attribute value for the calculated attribute Modificable
     */
    public String getModificable() {
        return (String) getAttributeInternal(MODIFICABLE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Modificable
     */
    public void setModificable(String value) {
        setAttributeInternal(MODIFICABLE, value);
    }

    /**Gets the attribute value for the calculated attribute Nivel
     */
    public String getNivel() {
        return (String) getAttributeInternal(NIVEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nivel
     */
    public void setNivel(String value) {
        setAttributeInternal(NIVEL, value);
    }

    /**Gets the attribute value for the calculated attribute Renuncia
     */
    public String getRenuncia() {
        return (String) getAttributeInternal(RENUNCIA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Renuncia
     */
    public void setRenuncia(String value) {
        setAttributeInternal(RENUNCIA, value);
    }

    /**Gets the attribute value for the calculated attribute Nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case IDAJUSTE:
            return getIdAjuste();
        case IDCORRELATIVO:
            return getIdCorrelativo();
        case REMOVIBLE:
            return getRemovible();
        case MODIFICABLE:
            return getModificable();
        case NIVEL:
            return getNivel();
        case RENUNCIA:
            return getRenuncia();
        case NOMBRE:
            return getNombre();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute IdCorrelativo
     */
    public Number getIdCorrelativo() {
        return (Number) getAttributeInternal(IDCORRELATIVO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdCorrelativo
     */
    public void setIdCorrelativo(Number value) {
        setAttributeInternal(IDCORRELATIVO, value);
    }
}
