package enlace_datos.consultas.gestiones.empleado;

import enlace_datos.entidades.gestiones.empleado.SisDeclaracionJuradaImpl;

import enlace_datos.util.utils;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisDeclaracionJuradaVwRowImpl extends ViewRowImpl {
    public static final int REGISTROEMPLEADO = 0;
    public static final int TIPODECLARACION = 1;
    public static final int ANIO = 2;
    public static final int ORDEN = 3;
    public static final int IDPARTIDA = 4;
    public static final int EMPRESA = 5;
    public static final int TELEFONO = 6;
    public static final int EXT = 7;
    public static final int FECHAINICIO = 8;
    public static final int FECHAFIN = 9;
    public static final int FECHACREACION = 10;
    public static final int FECHAMODIFICACION = 11;
    public static final int DIRECCION = 12;
    public static final int MODIFICADOPOR = 13;
    public static final int CREADOPOR = 14;
    public static final int NOMSUBPROGRAMA = 15;
    public static final int HORASCONTRATADAS = 16;
    public static final int NUMEROPLAZA = 17;
    public static final int SELECTED = 18;
    public static final int NOMBRECARGO = 19;
    public static final int LABELLISTADECLARA = 20;
    public static final int TOTALHORAD = 21;
    public static final int SISHORARIODECJURADAVW = 22;
    private boolean isSelected=false;

    /**This is the default constructor (do not remove)
     */
    public SisDeclaracionJuradaVwRowImpl() {
    }

    /**Gets SisDeclaracionJurada entity object.
     */
    public SisDeclaracionJuradaImpl getSisDeclaracionJurada() {
        return (SisDeclaracionJuradaImpl)getEntity(0);
    }

    /**Gets the attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for TIPO_DECLARACION using the alias name TipoDeclaracion
     */
    public String getTipoDeclaracion() {
        return (String) getAttributeInternal(TIPODECLARACION);
    }

    /**Sets <code>value</code> as attribute value for TIPO_DECLARACION using the alias name TipoDeclaracion
     */
    public void setTipoDeclaracion(String value) {
        setAttributeInternal(TIPODECLARACION, value);
    }

    /**Gets the attribute value for ANIO using the alias name Anio
     */
    public Number getAnio() {
        return (Number) getAttributeInternal(ANIO);
    }

    /**Sets <code>value</code> as attribute value for ANIO using the alias name Anio
     */
    public void setAnio(Number value) {
        setAttributeInternal(ANIO, value);
    }

    /**Gets the attribute value for ORDEN using the alias name Orden
     */
    public Number getOrden() {
        return (Number) getAttributeInternal(ORDEN);
    }

    /**Sets <code>value</code> as attribute value for ORDEN using the alias name Orden
     */
    public void setOrden(Number value) {
        setAttributeInternal(ORDEN, value);
    }

    /**Gets the attribute value for ID_PARTIDA using the alias name IdPartida
     */
    public Number getIdPartida() {
        return (Number) getAttributeInternal(IDPARTIDA);
    }

    /**Sets <code>value</code> as attribute value for ID_PARTIDA using the alias name IdPartida
     */
    public void setIdPartida(Number value) {
        setAttributeInternal(IDPARTIDA, value);
    }

    /**Gets the attribute value for EMPRESA using the alias name Empresa
     */
    public String getEmpresa() {
        return (String) getAttributeInternal(EMPRESA);
    }

    /**Sets <code>value</code> as attribute value for EMPRESA using the alias name Empresa
     */
    public void setEmpresa(String value) {
        setAttributeInternal(EMPRESA, value);
    }

    /**Gets the attribute value for TELEFONO using the alias name Telefono
     */
    public String getTelefono() {
        return (String) getAttributeInternal(TELEFONO);
    }

    /**Sets <code>value</code> as attribute value for TELEFONO using the alias name Telefono
     */
    public void setTelefono(String value) {
        setAttributeInternal(TELEFONO, value);
    }

    /**Gets the attribute value for EXT using the alias name Ext
     */
    public String getExt() {
        return (String) getAttributeInternal(EXT);
    }

    /**Sets <code>value</code> as attribute value for EXT using the alias name Ext
     */
    public void setExt(String value) {
        setAttributeInternal(EXT, value);
    }

    /**Gets the attribute value for FECHA_INICIO using the alias name FechaInicio
     */
    public Date getFechaInicio() {
        return (Date) getAttributeInternal(FECHAINICIO);
    }

    /**Sets <code>value</code> as attribute value for FECHA_INICIO using the alias name FechaInicio
     */
    public void setFechaInicio(Date value) {
        setAttributeInternal(FECHAINICIO, value);
    }

    /**Gets the attribute value for FECHA_FIN using the alias name FechaFin
     */
    public Date getFechaFin() {
        return (Date) getAttributeInternal(FECHAFIN);
    }

    /**Sets <code>value</code> as attribute value for FECHA_FIN using the alias name FechaFin
     */
    public void setFechaFin(Date value) {
        setAttributeInternal(FECHAFIN, value);
    }

    /**Gets the attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_CREACION using the alias name FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for FECHA_MODIFICACION using the alias name FechaModificacion
     */
    public Date getFechaModificacion() {
        return (Date) getAttributeInternal(FECHAMODIFICACION);
    }

    /**Sets <code>value</code> as attribute value for FECHA_MODIFICACION using the alias name FechaModificacion
     */
    public void setFechaModificacion(Date value) {
        setAttributeInternal(FECHAMODIFICACION, value);
    }

    /**Gets the attribute value for the calculated attribute Selected
     */
    public Boolean getSelected() {
        return isSelected;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Selected
     */
    public void setSelected(Boolean value) {
        isSelected=value;    
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link SisHorarioDecJuradaVw
     */
    public RowIterator getSisHorarioDecJuradaVw() {
        return (RowIterator)getAttributeInternal(SISHORARIODECJURADAVW);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case TIPODECLARACION:
            return getTipoDeclaracion();
        case ANIO:
            return getAnio();
        case ORDEN:
            return getOrden();
        case IDPARTIDA:
            return getIdPartida();
        case EMPRESA:
            return getEmpresa();
        case TELEFONO:
            return getTelefono();
        case EXT:
            return getExt();
        case FECHAINICIO:
            return getFechaInicio();
        case FECHAFIN:
            return getFechaFin();
        case FECHACREACION:
            return getFechaCreacion();
        case FECHAMODIFICACION:
            return getFechaModificacion();
        case DIRECCION:
            return getDireccion();
        case MODIFICADOPOR:
            return getModificadoPor();
        case CREADOPOR:
            return getCreadoPor();
        case NOMSUBPROGRAMA:
            return getNomSubprograma();
        case HORASCONTRATADAS:
            return getHorasContratadas();
        case NUMEROPLAZA:
            return getNumeroPlaza();
        case SELECTED:
            return getSelected();
        case NOMBRECARGO:
            return getNombreCargo();
        case LABELLISTADECLARA:
            return getLabelListaDeclara();
        case TOTALHORAD:
            return getTotalHoraD();
        case SISHORARIODECJURADAVW:
            return getSisHorarioDecJuradaVw();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            setRegistroEmpleado((Number)value);
            return;
        case TIPODECLARACION:
            setTipoDeclaracion((String)value);
            return;
        case ANIO:
            setAnio((Number)value);
            return;
        case ORDEN:
            setOrden((Number)value);
            return;
        case IDPARTIDA:
            setIdPartida((Number)value);
            return;
        case EMPRESA:
            setEmpresa((String)value);
            return;
        case TELEFONO:
            setTelefono((String)value);
            return;
        case EXT:
            setExt((String)value);
            return;
        case FECHAINICIO:
            setFechaInicio((Date)value);
            return;
        case FECHAFIN:
            setFechaFin((Date)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case FECHAMODIFICACION:
            setFechaModificacion((Date)value);
            return;
        case DIRECCION:
            setDireccion((String)value);
            return;
        case MODIFICADOPOR:
            setModificadoPor((String)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case NOMSUBPROGRAMA:
            setNomSubprograma((String)value);
            return;
        case HORASCONTRATADAS:
            setHorasContratadas((Number)value);
            return;
        case NUMEROPLAZA:
            setNumeroPlaza((Number)value);
            return;
        case SELECTED:
            setSelected((Boolean)value);
            return;
        case TOTALHORAD:
            setTotalHoraD((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute NombreCargo
     */
    public String getNombreCargo() {
       String vNombreCargo=null;
    
       if (this.getTipoDeclaracion()!=null){
           vNombreCargo=this.getTipoDeclaracion().equals("E")?"Cargos Extrauniversitarios":"Cargos Universitarios";
           
       }
        return vNombreCargo;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NombreCargo
     */
    public void setNombreCargo(String value) {
        setAttributeInternal(NOMBRECARGO, value);
    }

    /**Gets the attribute value for DIRECCION using the alias name Direccion
     */
    public String getDireccion() {
        return (String) getAttributeInternal(DIRECCION);
    }

    /**Sets <code>value</code> as attribute value for DIRECCION using the alias name Direccion
     */
    public void setDireccion(String value) {
        setAttributeInternal(DIRECCION, value);
    }

    /**Gets the attribute value for MODIFICADO_POR using the alias name ModificadoPor
     */
    public String getModificadoPor() {
        return (String) getAttributeInternal(MODIFICADOPOR);
    }

    /**Sets <code>value</code> as attribute value for MODIFICADO_POR using the alias name ModificadoPor
     */
    public void setModificadoPor(String value) {
        setAttributeInternal(MODIFICADOPOR, value);
    }

    /**Gets the attribute value for CREADO_POR using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String) getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as attribute value for CREADO_POR using the alias name CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }


    /**Gets the attribute value for NOM_SUBPROGRAMA using the alias name NomSubprograma
     */
    public String getNomSubprograma() {
        return (String) getAttributeInternal(NOMSUBPROGRAMA);
    }

    /**Sets <code>value</code> as attribute value for NOM_SUBPROGRAMA using the alias name NomSubprograma
     */
    public void setNomSubprograma(String value) {
        setAttributeInternal(NOMSUBPROGRAMA, value);
    }

    /**Gets the attribute value for the calculated attribute LabelListaDeclara
     */
    public String getLabelListaDeclara() {
       String vEtiqueta;
       try{           
           vEtiqueta=this.getNombreCargo()+" - " + (this.getEmpresa()!=null?this.getEmpresa():"")+ (this.getNumeroPlaza()!=null?" - "+this.getNumeroPlaza().toString():"");
       }catch(Exception exep){
           vEtiqueta="";
       }
    
        return  vEtiqueta;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LabelListaDeclara
     */
    public void setLabelListaDeclara(String value) {
        setAttributeInternal(LABELLISTADECLARA, value);
    }


    /**Gets the attribute value for TOTAL_HORA_D using the alias name TotalHoraD
     */
    public Number getTotalHoraD() {
        return (Number) getAttributeInternal(TOTALHORAD);
    }

    /**Sets <code>value</code> as attribute value for TOTAL_HORA_D using the alias name TotalHoraD
     */
    public void setTotalHoraD(Number value) {
        setAttributeInternal(TOTALHORAD, value);
    }

    /**Gets the attribute value for HORAS_CONTRATADAS using the alias name HorasContratadas
     */
    public Number getHorasContratadas() {
        return (Number) getAttributeInternal(HORASCONTRATADAS);
    }

    /**Sets <code>value</code> as attribute value for HORAS_CONTRATADAS using the alias name HorasContratadas
     */
    public void setHorasContratadas(Number value) {
        setAttributeInternal(HORASCONTRATADAS, value);
    }


    /**Gets the attribute value for NUMERO_PLAZA using the alias name NumeroPlaza
     */
    public Number getNumeroPlaza() {
        return (Number) getAttributeInternal(NUMEROPLAZA);
    }

    /**Sets <code>value</code> as attribute value for NUMERO_PLAZA using the alias name NumeroPlaza
     */
    public void setNumeroPlaza(Number value) {
        setAttributeInternal(NUMEROPLAZA, value);
    }
}
