package enlace_datos.consultas.gestiones.empleado;

import enlace_datos.entidades.gestiones.empleado.SisEmpleadoCambiosImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisEmpleadoCambiosVwRowImpl extends ViewRowImpl {
    public static final int REGISTROEMPLEADO = 0;
    public static final int LOG = 1;
    public static final int FECHACAMBIO = 2;
    public static final int MODIFICADOPOR = 3;
    public static final int NOMBRECOMPLETOANTERIOR = 4;
    public static final int NOMBRECOMPLETOACTUAL = 5;
    public static final int CODCAMBIO = 6;

    /**This is the default constructor (do not remove)
     */
    public SisEmpleadoCambiosVwRowImpl() {
    }

    /**Gets SisEmpleadoCambios entity object.
     */
    public SisEmpleadoCambiosImpl getSisEmpleadoCambios() {
        return (SisEmpleadoCambiosImpl)getEntity(0);
    }

    /**Gets the attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public Number getRegistroEmpleado() {
        return (Number) getAttributeInternal(REGISTROEMPLEADO);
    }

    /**Sets <code>value</code> as attribute value for REGISTRO_EMPLEADO using the alias name RegistroEmpleado
     */
    public void setRegistroEmpleado(Number value) {
        setAttributeInternal(REGISTROEMPLEADO, value);
    }

    /**Gets the attribute value for LOG using the alias name Log
     */
    public String getLog() {
        return (String) getAttributeInternal(LOG);
    }

    /**Sets <code>value</code> as attribute value for LOG using the alias name Log
     */
    public void setLog(String value) {
        setAttributeInternal(LOG, value);
    }

    /**Gets the attribute value for FECHA_CAMBIO using the alias name FechaCambio
     */
    public Date getFechaCambio() {
        return (Date) getAttributeInternal(FECHACAMBIO);
    }

    /**Sets <code>value</code> as attribute value for FECHA_CAMBIO using the alias name FechaCambio
     */
    public void setFechaCambio(Date value) {
        setAttributeInternal(FECHACAMBIO, value);
    }

    /**Gets the attribute value for MODIFICADO_POR using the alias name ModificadoPor
     */
    public String getModificadoPor() {
        return (String) getAttributeInternal(MODIFICADOPOR);
    }

    /**Sets <code>value</code> as attribute value for MODIFICADO_POR using the alias name ModificadoPor
     */
    public void setModificadoPor(String value) {
        setAttributeInternal(MODIFICADOPOR, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            return getRegistroEmpleado();
        case LOG:
            return getLog();
        case FECHACAMBIO:
            return getFechaCambio();
        case MODIFICADOPOR:
            return getModificadoPor();
        case NOMBRECOMPLETOANTERIOR:
            return getNombrecompletoanterior();
        case NOMBRECOMPLETOACTUAL:
            return getNombrecompletoactual();
        case CODCAMBIO:
            return getCodCambio();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REGISTROEMPLEADO:
            setRegistroEmpleado((Number)value);
            return;
        case LOG:
            setLog((String)value);
            return;
        case FECHACAMBIO:
            setFechaCambio((Date)value);
            return;
        case MODIFICADOPOR:
            setModificadoPor((String)value);
            return;
        case NOMBRECOMPLETOANTERIOR:
            setNombrecompletoanterior((String)value);
            return;
        case NOMBRECOMPLETOACTUAL:
            setNombrecompletoactual((String)value);
            return;
        case CODCAMBIO:
            setCodCambio((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Nombrecompletoanterior
     */
    public String getNombrecompletoanterior() {
        return (String) getAttributeInternal(NOMBRECOMPLETOANTERIOR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombrecompletoanterior
     */
    public void setNombrecompletoanterior(String value) {
        setAttributeInternal(NOMBRECOMPLETOANTERIOR, value);
    }

    /**Gets the attribute value for the calculated attribute Nombrecompletoactual
     */
    public String getNombrecompletoactual() {
        return (String) getAttributeInternal(NOMBRECOMPLETOACTUAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nombrecompletoactual
     */
    public void setNombrecompletoactual(String value) {
        setAttributeInternal(NOMBRECOMPLETOACTUAL, value);
    }

    /**Gets the attribute value for COD_CAMBIO using the alias name CodCambio
     */
    public Number getCodCambio() {
        return (Number) getAttributeInternal(CODCAMBIO);
    }

    /**Sets <code>value</code> as attribute value for COD_CAMBIO using the alias name CodCambio
     */
    public void setCodCambio(Number value) {
        setAttributeInternal(CODCAMBIO, value);
    }
}
