package enlace_datos.consultas.gestiones.empleado;


import enlace_datos.consultas.gestiones.empleado.common.SisNivelAcad;

import java.sql.ResultSet;
import oracle.jbo.domain.Number;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisNivelAcadImpl extends ViewObjectImpl implements SisNivelAcad {
    /**This is the default constructor (do not remove)
     */
    public SisNivelAcadImpl() {
    }

    /**executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object params[], int noUserParams) {super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc, 
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**getEstimatedRowCount - overridden for custom java data source support.
     */
    public long getEstimatedRowCount() {
        long value = super.getEstimatedRowCount();
        return value;
    }
    
    public void setRowxValue(Number pValor){
      Row [] vFilas;  
      vFilas=this.getAllRowsInRange();
     
     if (pValor!=null){ 
              for (int i=0;i<vFilas.length;i++){
                if (vFilas[i].getAttribute("IdNivel").equals(pValor)){
                  this.setCurrentRow(vFilas[i]) ;
                  break;
                }
              }
          }
    }
    
}
