package enlace_datos.consultas.gestiones.empleado;

import enlace_datos.consultas.gestiones.empleado.common.SisPlazasEmpleadoComplVw;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisPlazasEmpleadoComplVwImpl extends ViewObjectImpl implements SisPlazasEmpleadoComplVw {
    /**This is the default constructor (do not remove)
     */
    public SisPlazasEmpleadoComplVwImpl() {
    }

    /**Gets the bind variable value for pUsuario
     */
    public String getpUsuario() {
        return (String)getNamedWhereClauseParam("pUsuario");
    }

    /**Sets <code>value</code> for bind variable pUsuario
     */
    public void setpUsuario(String value) {
        setNamedWhereClauseParam("pUsuario", value);
    }

    /**Gets the bind variable value for pRegistroEmpl
     */
    public Number getpRegistroEmpl() {
        return (Number)getNamedWhereClauseParam("pRegistroEmpl");
    }

    /**Sets <code>value</code> for bind variable pRegistroEmpl
     */
    public void setpRegistroEmpl(Number value) {
        setNamedWhereClauseParam("pRegistroEmpl", value);
    }

    /**Gets the bind variable value for pAnio
     */
    public Number getpAnio() {
        return (Number)getNamedWhereClauseParam("pAnio");
    }

    /**Sets <code>value</code> for bind variable pAnio
     */
    public void setpAnio(Number value) {
        setNamedWhereClauseParam("pAnio", value);
    }
    
    public void paramPlazas(Number pRegistroEmpl, String pUsuario, Number pAnio){
        this.setpAnio(pAnio);
        this.setpRegistroEmpl(pRegistroEmpl);
        this.setpUsuario(pUsuario);        
        
        String str_querry="correlativo="+pAnio;       
        this.setWhereClause(str_querry);        
        this.executeQuery();        
    }

    /**Gets the bind variable value for vIdTipoProceso
     */
    public String getvIdTipoProceso() {
        return (String)getNamedWhereClauseParam("vIdTipoProceso");
    }

    /**Sets <code>value</code> for bind variable vIdTipoProceso
     */
    public void setvIdTipoProceso(String value) {
        setNamedWhereClauseParam("vIdTipoProceso", value);
    }
}
