package enlace_datos.consultas.reportes.client;

import enlace_datos.consultas.reportes.common.SisProyeccionISR;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisProyeccionISRClient extends ViewUsageImpl implements SisProyeccionISR {
    /**This is the default constructor (do not remove)
     */
    public SisProyeccionISRClient() {
    }

    public void verificarProyeccion(Number pRegistroEmpleado, Number pAnio) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"verificarProyeccion",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number"},new Object[] {pRegistroEmpleado, pAnio});
        return;
    }
}
