package enlace_datos.entidades.gestiones;

import enlace_datos.entidades.nomina.SisDetCalculoAjusteImpl;

import enlace_datos.util.utils;

import enlace_datos.util.utils_DB;

import java.sql.ResultSet;

import java.sql.SQLException;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisDetalleReintegroImpl extends EntityImpl {
    public static final int IDDETALLEREINTEGRO = 0;
    public static final int IDREINTEGRO = 1;
    public static final int IDNOMINA = 2;
    public static final int SUELDOBASE = 3;
    public static final int ESCALAFON = 4;
    public static final int COMPLSALARIAL = 5;
    public static final int CREADOPOR = 6;
    public static final int FECHACREACION = 7;
    public static final int MODPOR = 8;
    public static final int FECHAMOD = 9;
    public static final int NOMINAL = 10;
    public static final int TOTALBONO = 11;
    public static final int TOTALDESCUENTOS = 12;
    public static final int LIQUIDO = 13;
    public static final int DIASLABORADOS = 14;
    public static final int SISREINTEGRO = 15;
    public static final int SISDESCUENTOREINTEGRO = 16;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisDetalleReintegroImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.gestiones.SisDetalleReintegro");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdDetalleReintegro, using the alias name IdDetalleReintegro
     */
    public Number getIdDetalleReintegro() {
        return (Number)getAttributeInternal(IDDETALLEREINTEGRO);
    }

    /**Sets <code>value</code> as the attribute value for IdDetalleReintegro
     */
    public void setIdDetalleReintegro(Number value) {
        setAttributeInternal(IDDETALLEREINTEGRO, value);
    }

    /**Gets the attribute value for IdReintegro, using the alias name IdReintegro
     */
    public Number getIdReintegro() {
        return (Number)getAttributeInternal(IDREINTEGRO);
    }

    /**Sets <code>value</code> as the attribute value for IdReintegro
     */
    public void setIdReintegro(Number value) {
        setAttributeInternal(IDREINTEGRO, value);
    }

    /**Gets the attribute value for IdNomina, using the alias name IdNomina
     */
    public Number getIdNomina() {
        return (Number)getAttributeInternal(IDNOMINA);
    }

    /**Sets <code>value</code> as the attribute value for IdNomina
     */
    public void setIdNomina(Number value) {
        setAttributeInternal(IDNOMINA, value);
    }

    /**Gets the attribute value for SueldoBase, using the alias name SueldoBase
     */
    public Number getSueldoBase() {
        return (Number)getAttributeInternal(SUELDOBASE);
    }

    /**Sets <code>value</code> as the attribute value for SueldoBase
     */
    public void setSueldoBase(Number value) {
        setAttributeInternal(SUELDOBASE, value);
    }

    /**Gets the attribute value for Escalafon, using the alias name Escalafon
     */
    public Number getEscalafon() {
        return (Number)getAttributeInternal(ESCALAFON);
    }

    /**Sets <code>value</code> as the attribute value for Escalafon
     */
    public void setEscalafon(Number value) {
        setAttributeInternal(ESCALAFON, value);
    }

    /**Gets the attribute value for ComplSalarial, using the alias name ComplSalarial
     */
    public Number getComplSalarial() {
        return (Number)getAttributeInternal(COMPLSALARIAL);
    }

    /**Sets <code>value</code> as the attribute value for ComplSalarial
     */
    public void setComplSalarial(Number value) {
        setAttributeInternal(COMPLSALARIAL, value);
    }

    /**Gets the attribute value for CreadoPor, using the alias name CreadoPor
     */
    public String getCreadoPor() {
        return (String)getAttributeInternal(CREADOPOR);
    }

    /**Sets <code>value</code> as the attribute value for CreadoPor
     */
    public void setCreadoPor(String value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**Gets the attribute value for FechaCreacion, using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**Gets the attribute value for ModPor, using the alias name ModPor
     */
    public String getModPor() {
        return (String)getAttributeInternal(MODPOR);
    }

    /**Sets <code>value</code> as the attribute value for ModPor
     */
    public void setModPor(String value) {
        setAttributeInternal(MODPOR, value);
    }

    /**Gets the attribute value for FechaMod, using the alias name FechaMod
     */
    public Date getFechaMod() {
        return (Date)getAttributeInternal(FECHAMOD);
    }

    /**Sets <code>value</code> as the attribute value for FechaMod
     */
    public void setFechaMod(Date value) {
        setAttributeInternal(FECHAMOD, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDDETALLEREINTEGRO:
            return getIdDetalleReintegro();
        case IDREINTEGRO:
            return getIdReintegro();
        case IDNOMINA:
            return getIdNomina();
        case SUELDOBASE:
            return getSueldoBase();
        case ESCALAFON:
            return getEscalafon();
        case COMPLSALARIAL:
            return getComplSalarial();
        case CREADOPOR:
            return getCreadoPor();
        case FECHACREACION:
            return getFechaCreacion();
        case MODPOR:
            return getModPor();
        case FECHAMOD:
            return getFechaMod();
        case NOMINAL:
            return getNominal();
        case TOTALBONO:
            return getTotalBono();
        case TOTALDESCUENTOS:
            return getTotalDescuentos();
        case LIQUIDO:
            return getLiquido();
        case DIASLABORADOS:
            return getDiaslaborados();
        case SISDESCUENTOREINTEGRO:
            return getSisDescuentoReintegro();
        case SISREINTEGRO:
            return getSisReintegro();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDDETALLEREINTEGRO:
            setIdDetalleReintegro((Number)value);
            return;
        case IDREINTEGRO:
            setIdReintegro((Number)value);
            return;
        case IDNOMINA:
            setIdNomina((Number)value);
            return;
        case SUELDOBASE:
            setSueldoBase((Number)value);
            return;
        case ESCALAFON:
            setEscalafon((Number)value);
            return;
        case COMPLSALARIAL:
            setComplSalarial((Number)value);
            return;
        case CREADOPOR:
            setCreadoPor((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        case MODPOR:
            setModPor((String)value);
            return;
        case FECHAMOD:
            setFechaMod((Date)value);
            return;
        case NOMINAL:
            setNominal((Number)value);
            return;
        case TOTALBONO:
            setTotalBono((Number)value);
            return;
        case TOTALDESCUENTOS:
            setTotalDescuentos((Number)value);
            return;
        case LIQUIDO:
            setLiquido((Number)value);
            return;
        case DIASLABORADOS:
            setDiaslaborados((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity SisReintegroImpl
     */
    public SisReintegroImpl getSisReintegro() {
        return (SisReintegroImpl)getAttributeInternal(SISREINTEGRO);
    }

    /**Sets <code>value</code> as the associated entity SisReintegroImpl
     */
    public void setSisReintegro(SisReintegroImpl value) {
        setAttributeInternal(SISREINTEGRO, value);
    }
    
    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        int EjecutarOperacion = 1;
        
        if (operation != this.DML_DELETE){
           EjecutarOperacion= verificarValoresEnNomina();
        }
        
        if (operation==this.DML_UPDATE){
            actualizar_liquido();
            this.setModPor(utils.getAuthUser(this.getDBTransaction()));
            this.setFechaMod(utils.getFechaActual());
        }
        
        if (EjecutarOperacion == 1)      
            super.doDML(operation, e);
    }

    /**Gets the attribute value for Nominal, using the alias name Nominal
     */
    public Number getNominal() {
        Number vSueldoBase;
        Number vEscalafon;
        Number vComplSal;
        Number vLiquido;
        
         vSueldoBase=this.getSueldoBase()==null?new Number(0):this.getSueldoBase();
         vEscalafon=this.getEscalafon()==null?new Number(0):this.getEscalafon();
         vComplSal=this.getComplSalarial()==null?new Number(0):this.getComplSalarial();
         vLiquido=vSueldoBase.add(vEscalafon).add(vComplSal);
        
         if (getAttributeInternal(NOMINAL)==null){
             setAttributeInternal(NOMINAL, vLiquido);            
         }else if (getAttributeInternal(NOMINAL)!=null && vLiquido.compareTo((Number)getAttributeInternal(NOMINAL))!=0){
             setAttributeInternal(NOMINAL, vLiquido);
         }
         
         return (Number)getAttributeInternal(NOMINAL);
        //return (Number)getAttributeInternal(NOMINAL);
    }

    public void actualizar_liquido() {        
        
        Number vTotalDescuentos = new Number(0);
        Number vTotalBonos = new Number(0);
        
        ResultSet vFilaDescuentos =
        utils_DB.getEjecutarQuerry(this.getDBTransaction(),"select abs(nvl(sum(valor_aplicado),0)) valor from sis_descuento_reintegro where valor_aplicado<0 and id_detalle_reintegro="+this.getIdDetalleReintegro(),0);

        ResultSet vFilaBono =
        utils_DB.getEjecutarQuerry(this.getDBTransaction(),"select abs(nvl(sum(valor_aplicado),0)) valor from sis_descuento_reintegro where valor_aplicado>0 and id_detalle_reintegro="+this.getIdDetalleReintegro(),0);
        try {
            if(vFilaDescuentos.next()){
                vTotalDescuentos= utils.getNumberOracle(vFilaDescuentos.getObject("valor"));
            }
            
            if(vFilaBono.next()){
                vTotalBonos= utils.getNumberOracle(vFilaBono.getObject("valor"));
            }
            vFilaBono.close();
            vFilaDescuentos.close();
            
        } catch (SQLException e) {
            // TODO
        }
        
        
        this.setTotalBono(vTotalBonos);
        this.setTotalDescuentos(vTotalDescuentos);
        this.setLiquido(this.getNominal().subtract(this.getTotalDescuentos()).add(this.getTotalBono()));        
    }

    public int verificarValoresEnNomina(){
        String strQuery = "select sueldo_base, escalafon, compl_salarial from sis_nomina where id_nomina= "+getIdNomina().toString();
        ResultSet tblNomina = utils_DB.getEjecutarQuerry(this.getDBTransaction(), strQuery,0);    
        int intResult = 1;
        String strNomina_SueldoBase="-1";
        String strNomina_Escalafon="-1";
        String strNomina_Compl_salarial="-1";
        
        float fltNomina_SueldoBase=-1;
        float fltNomina_Escalafon=-1;
        float fltNomina_Compl_salarial=-1;
        
        try {
            if(tblNomina.next()){
                strNomina_SueldoBase = tblNomina.getString("sueldo_base");
                strNomina_Escalafon =  tblNomina.getString("escalafon");
                strNomina_Compl_salarial = tblNomina.getString("compl_salarial");
            }
            
        } catch (SQLException e) {
            System.out.println("Error! al consultar Nomina");
            strNomina_SueldoBase = "-1";
            strNomina_Escalafon = "-1";
            strNomina_Compl_salarial = "-1";
        }
        
        try{  fltNomina_SueldoBase = Float.parseFloat(strNomina_SueldoBase); }
        catch(Exception e){ fltNomina_SueldoBase = -1; }
        
        try{  fltNomina_Escalafon = Float.parseFloat(strNomina_Escalafon);}
        catch(Exception e){ fltNomina_Escalafon = -1; }
        
        try{ fltNomina_Compl_salarial = Float.parseFloat(strNomina_Compl_salarial); }
        catch(Exception e){ fltNomina_Compl_salarial = -1;}
        
        intResult = (fltNomina_Escalafon == -1 || Float.parseFloat(getEscalafon().toString()) > fltNomina_Escalafon ) ? 0 : 1;
        intResult = (fltNomina_SueldoBase == -1 || Float.parseFloat(getSueldoBase().toString()) > fltNomina_SueldoBase ) ? 0 : 1;
        intResult = (fltNomina_Compl_salarial == -1 || Float.parseFloat(getComplSalarial().toString()) > fltNomina_Compl_salarial ) ? 0 : 1;

        return intResult;
    }
    

    /**Sets <code>value</code> as the attribute value for Nominal
     */
    public void setNominal(Number value) {
        setAttributeInternal(NOMINAL, value);
    }

    /**Gets the attribute value for TotalBono, using the alias name TotalBono
     */
    public Number getTotalBono() {
        return (Number)getAttributeInternal(TOTALBONO);
    }

    /**Sets <code>value</code> as the attribute value for TotalBono
     */
    public void setTotalBono(Number value) {
        setAttributeInternal(TOTALBONO, value);
    }

    /**Gets the attribute value for TotalDescuentos, using the alias name TotalDescuentos
     */
    public Number getTotalDescuentos() {
        return (Number)getAttributeInternal(TOTALDESCUENTOS);
    }

    /**Sets <code>value</code> as the attribute value for TotalDescuentos
     */
    public void setTotalDescuentos(Number value) {
        setAttributeInternal(TOTALDESCUENTOS, value);
    }

    /**Gets the attribute value for Liquido, using the alias name Liquido
     */
    public Number getLiquido() {
        return (Number)getAttributeInternal(LIQUIDO);
    }

    /**Sets <code>value</code> as the attribute value for Liquido
     */
    public void setLiquido(Number value) {
        setAttributeInternal(LIQUIDO, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getSisDescuentoReintegro() {
        return (RowIterator)getAttributeInternal(SISDESCUENTOREINTEGRO);
    }

    /**Gets the attribute value for Diaslaborados, using the alias name Diaslaborados
     */
    public Number getDiaslaborados() {
        return (Number)getAttributeInternal(DIASLABORADOS);
    }

    /**Sets <code>value</code> as the attribute value for Diaslaborados
     */
    public void setDiaslaborados(Number value) {
        setAttributeInternal(DIASLABORADOS, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idDetalleReintegro) {
        return new Key(new Object[]{idDetalleReintegro});
    }
}
