package enlace_datos.entidades.gestiones.empleado;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisTipoArchivoAdjuntoImpl extends EntityImpl {
    public static final int IDTIPOARCHIVO = 0;
    public static final int NOMBRE = 1;
    public static final int CONTENTTYPE = 2;
    public static final int FECHACREACION = 3;
    private static EntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SisTipoArchivoAdjuntoImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("enlace_datos.entidades.gestiones.empleado.SisTipoArchivoAdjunto");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for IdTipoArchivo, using the alias name IdTipoArchivo
     */
    public Number getIdTipoArchivo() {
        return (Number)getAttributeInternal(IDTIPOARCHIVO);
    }

    /**Sets <code>value</code> as the attribute value for IdTipoArchivo
     */
    public void setIdTipoArchivo(Number value) {
        setAttributeInternal(IDTIPOARCHIVO, value);
    }

    /**Gets the attribute value for Nombre, using the alias name Nombre
     */
    public String getNombre() {
        return (String)getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Gets the attribute value for ContentType, using the alias name ContentType
     */
    public String getContentType() {
        return (String)getAttributeInternal(CONTENTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for ContentType
     */
    public void setContentType(String value) {
        setAttributeInternal(CONTENTTYPE, value);
    }

    /**Gets the attribute value for FechaCreacion, using the alias name FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDTIPOARCHIVO:
            return getIdTipoArchivo();
        case NOMBRE:
            return getNombre();
        case CONTENTTYPE:
            return getContentType();
        case FECHACREACION:
            return getFechaCreacion();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDTIPOARCHIVO:
            setIdTipoArchivo((Number)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        case CONTENTTYPE:
            setContentType((String)value);
            return;
        case FECHACREACION:
            setFechaCreacion((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Add attribute defaulting logic in this method.
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idTipoArchivo) {
        return new Key(new Object[]{idTipoArchivo});
    }
}
