// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.4.0, build 080709.0800.28953)

package webservices.PhoneVal;


public class PhoneVerify implements java.io.Serializable {
    protected java.lang.String phoneNumber;
    
    public PhoneVerify() {
    }
    
    public java.lang.String getPhoneNumber() {
        return phoneNumber;
    }
    
    public void setPhoneNumber(java.lang.String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}
