package enlace_datos.consultas.nomina;

import java.sql.ResultSet;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisConsulPlazaImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
     
     Object pParametro1;
     Object pParametro2;
    public SisConsulPlazaImpl() {
    }

    /**Gets the bind variable value for pAnio
     */
    public Number getpAnio() {
        return (Number)getNamedWhereClauseParam("pAnio");
    }

    /**Sets <code>value</code> for bind variable pAnio
     */
    public void setpAnio(Number value) {
        setNamedWhereClauseParam("pAnio", value);
    }

    /**Gets the bind variable value for pIdPartida
     */
    public String getpIdPartida() {
        return (String)getNamedWhereClauseParam("pIdPartida");
    }

    /**Sets <code>value</code> for bind variable pIdPartida
     */
    public void setpIdPartida(String value) {
        setNamedWhereClauseParam("pIdPartida", value);
    }

    /**executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object params[], int noUserParams) {
    
        super.executeQueryForCollection(qc, params, noUserParams);      
        //System.out.println("Consulta plazas");        
    /*
        Object [] vValores;
        vValores=this.getNamedWhereClauseParams().getAttributeValues();
        if (vValores.length==2){
          if (vValores[0]!=this.pParametro1 && vValores[1]!=this.pParametro2){
              this.pParametro1=vValores[0];
              this.pParametro2=vValores[1];
            super.executeQueryForCollection(qc, params, noUserParams);      
            System.out.println("Consulta plazas");        
          }
        }
        */
    }

    /**hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc, 
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**getEstimatedRowCount - overridden for custom java data source support.
     */
    public long getEstimatedRowCount() {
        long value = super.getEstimatedRowCount();
        return value;
    }
}
