package enlace_datos.consultas.nomina;


import enlace_datos.consultas.nomina.common.SisNominaVw;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SisNominaVwImpl extends ViewObjectImpl implements SisNominaVw {
    /**This is the default constructor (do not remove)
     */
    public SisNominaVwImpl() {
    }
    
    
    public void filtrarxProceso(Number pIdProceso){
        this.setWhereClause( "id_proceso="+pIdProceso);
        this.executeQuery();
    }
}
